#730: Copiar OpenGnsys 1.1.0 en rama {{{tags/opengnsys-1.1.0}}}
git-svn-id: https://opengnsys.es/svn/tags/opengnsys-1.1.0@5607 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/admin/Interface/CrearImagen b/admin/Interface/CrearImagen
--- a/admin/Interface/CrearImagen
+++ b/admin/Interface/CrearImagen
@@ -42,7 +42,7 @@ echo " " > $OGLOGSESSION; echo " " > $OGLOGCOMMAND; echo " " > ${OGLOGCOMMAND}.t
 # Registro de inicio de ejecución
 ogEcho log session "$MSG_INTERFACE_START $0 $*"
 
-# Solo ejecutable por OpenGnSys Client.
+# Solo ejecutable por OpenGnsys Client.
 PATH=$PATH:$(dirname $0)
 PROG=$(basename $0)
 CALLER=$(ogGetCaller)
@@ -53,9 +53,16 @@ fi
 
 # Valor por defecto para el repositorio.
 REPO=${4:-"REPO"}
-[ "$REPO" == "$(ogGetRepoIp)" ] && REPO="REPO"
 [ "$REPO" == "$(ogGetIpAddress)" ] && REPO="CACHE"
-[ "$REPO" == "CACHE" ] && REPO="CACHE"
+# Si es una ip y es distinta a la del recurso samba cambiamos de REPO.
+ogCheckIpAddress $REPO
+if [ $? == 0 -o $REPO == "REPO" ] ; then
+	# Unidad organizativa
+	[ "$ogunit" != "" ] && OGUNIT="$ogunit"
+        # Si falla el cambio -> salimos con error repositorio no valido
+        ogChangeRepo $REPO $OGUNIT || exit $(ogRaiseError $OG_ERR_NOTFOUND '$REPO'; echo $?)
+        REPO="REPO"
+fi
 
 # Si el destino es REPO y el cliente no está en modo "admin"; activar repositorio para escritura,
 if [ "$REPO" == "REPO" -a "$boot" != "admin"  ] 
@@ -65,11 +72,12 @@ then
 	[ $RETVAL -gt 0 ] && exit $RETVAL 	
 fi
 
+ogEcho	createImage "$1" "$2" "$4" /"$3" 
 # Si existe, ejecuta script personalizado "createImageCustom"; si no, llama al genérico "createImage".
 if which createImageCustom &>/dev/null; then
-	createImageCustom "$1" "$2" "$REPO" /"$3" &>> $OGLOGCOMMAND
+	createImageCustom "$1" "$2" "$4" /"$3" &>> $OGLOGCOMMAND
 else
-	createImage "$1" "$2" "$REPO" /"$3" &>> $OGLOGCOMMAND
+	createImage "$1" "$2" "$4" /"$3" &>> $OGLOGCOMMAND
 fi
 RETVAL=$?
 
diff --git a/client/shared/scripts/createImage b/client/shared/scripts/createImage
--- a/client/shared/scripts/createImage
+++ b/client/shared/scripts/createImage
@@ -3,7 +3,7 @@
 #/**
 #@file    createImage
 #@brief   Scirpt de ejemplo para crear una imagen de un sistema de archivos.
-#@brief   (puede usarse como base para el programa de creación de imágenes usado por OpenGnSys Admin).
+#@brief   Se usa como base para el programa de creación de imágenes de OpenGnsys Admin).
 #@param 1 disco 
 #@param 2 particion 
 #@param 3 REPO|CACHE
@@ -26,12 +26,15 @@
 #@version 1.0.1 - Control de espacio requerido
 #@author  Antonio J.Doblas Viso
 #@date   2011-05-10
- #@version 1.0.2 - Separacion de log
+#@version 1.0.2 - Separacion de log
 #@author  Antonio J.Doblas Viso
 #@date   2011-08-4
-#@version 1.0.6b - La copia de seguridad de la imagen antigua se hace después de las comprobaciones.
+#@version 1.1.0 - La copia de seguridad de la imagen antigua se hace después de las comprobaciones.
 #@author  Irina Gomez - ETSII Universidad de Sevilla
 #@date    2016-10-14
+#@version 1.1.0 - Se muestra el espacio necesario para alojar la imagen y el disponible (ticket #771)
+#@author  Irina Gomez - ETSII Universidad de Sevilla
+#@date    2017-03-28
 #*/ ##
 
 # Test 1.  crear una imagen en un REPO sin espacio libre. 
@@ -58,15 +61,32 @@ TIME1=$SECONDS
 #IMGCOMP="lzop"
 IMGEXT=${IMGEXT:-"img"}
 #IMGREDUCE="TRUE"
+REPO="${3^^}"
+
+# Unidad organizativa
+[ "$ogunit" != "" ] && OGUNIT="$ogunit"
 
 # Clear temporary file used as log track by httpdlog
 # Limpia los ficheros temporales usados como log de seguimiento para httpdlog
-echo " " > $OGLOGSESSION; echo " " > $OGLOGCOMMAND; echo " " > ${OGLOGCOMMAND}.tmp
+# salvo si es llamado desde createImageCustom
+if [ "$(ogGetCaller)" != "createImageCustom" ]; then
+    echo " " > $OGLOGSESSION; echo " " > $OGLOGCOMMAND; echo " " > ${OGLOGCOMMAND}.tmp
+fi
 
 ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
+# Si es una ip y es igual a la del equipo restaura desde cache
+[ "$REPO" == "$(ogGetIpAddress)" ] && REPO="CACHE"
+# Si es una ip y es distinta a la del recurso samba cambiamos de REPO.
+ogCheckIpAddress $REPO
+if [ $? == 0 -o $REPO == "REPO" ] ; then
+        # Si falla el cambio -> salimos con error repositorio no valido
+        ogChangeRepo $REPO $OGUNIT || exit $(ogRaiseError $OG_ERR_NOTFOUND '$REPO'; echo $?)
+        REPO="REPO"
+fi
+
 # Si el repositorio es CACHE comprobamos que exista
-if [ "${3^^}" == "CACHE" ]; then 
+if [ "$REPO" == "CACHE" ]; then 
     ! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE "; echo $?)
 fi
 
@@ -75,14 +95,14 @@ PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || exit $(ogRaiseError $OG_ERR_PARTITI
 
 #Comprobamos acceso de escritura.
 DIRTEMP=$(date +%Y%m%d-%H%M%S)
-ogMakeDir $3 /$4$DIRTEMP 2>/dev/null || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3"; echo $?) && ogDeleteTree $3 /$4$DIRTEMP 
+ogMakeDir $REPO /$4$DIRTEMP 2>/dev/null || exit $(ogRaiseError $OG_ERR_NOTWRITE "$REPO"; echo $?) && ogDeleteTree $REPO /$4$DIRTEMP 
 
-IMGDIR=$(ogGetParentPath "$3" "/$4")
+IMGDIR=$(ogGetParentPath "$REPO" "/$4")
 # Si no existe, crear subdirectorio de la imagen.
 if [ $? != 0 ]; then
-    ogEcho log session "[5] $MSG_HELP_ogMakeDir \"$3 $(dirname "$4")."
-    ogMakeDir "$3" $(dirname "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3 /$4"; echo $?)
-    IMGDIR=$(ogGetParentPath "$3" "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3 /$4"; echo $?)
+    ogEcho log session "[5] $MSG_HELP_ogMakeDir \"$REPO $(dirname "$4")."
+    ogMakeDir "$REPO" $(dirname "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$REPO /$4"; echo $?)
+    IMGDIR=$(ogGetParentPath "$REPO" "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$REPO /$4"; echo $?)
 fi
 IMGFILE=$IMGDIR/$(basename "/$4").$IMGEXT
 
@@ -91,10 +111,10 @@ echo " " > $OGLOGCOMMAND
 ogCleanOs $1 $2
 
 #Comprobar espacio que requerira la imagen para ser almacenada
-read SIZEDATA SIZEREQUIRED ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$3")
+read SIZEDATA SIZEREQUIRED SIZEFREE ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$REPO" "$4")
 
-ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE $SIZEREQUIRED"
-[ "$ISENOUGHSPACE" == "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
+ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE $SIZEREQUIRED $SIZEFREE"
+[ "$ISENOUGHSPACE" == "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$REPO"; echo $?)
 
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
@@ -125,8 +145,8 @@ fi
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
-ogEcho log session "[40] $MSG_HELP_ogCreateImage : ogCreateImage $1 $2 $3 $4 $IMGPROG $IMGCOMP"
-ogCreateImage "$1" "$2" "$3" "/$4" "$IMGPROG" "$IMGCOMP" &>> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_IMAGE "ogCreteImage"; echo $?)
+ogEcho log session "[40] $MSG_HELP_ogCreateImage : ogCreateImage $1 $2 $REPO $4 $IMGPROG $IMGCOMP"
+ogCreateImage "$1" "$2" "$REPO" "/$4" "$IMGPROG" "$IMGCOMP" &>> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_IMAGE "ogCreteImage"; echo $?)
 RESUMECREATEIMAGE=$(grep "Total Time:" $OGLOGCOMMAND)
 TIMEAUX2=$[SECONDS-TIME2]
 ogEcho log session "      $RESUMECREATEIMAGE "
@@ -143,8 +163,8 @@ ogEcho log session "      $MSG_HELP_ogExtendFs  $NEWSIZEFS ->  $SIZEFS = $SIZEFS
 #TODO que hacer si error al extender sistemade archivos
 
 #resumen de la operacion
-IMGSIZE=$(ls -s `ogGetPath $3 /$4.$IMGEXT`| cut -f1 -d" ")
-IMGOS=$(ogGetImageInfo `ogGetPath $3 /$4.$IMGEXT`)
+IMGSIZE=$(ls -s `ogGetPath $REPO /$4.$IMGEXT`| cut -f1 -d" ")
+IMGOS=$(ogGetImageInfo `ogGetPath $REPO /$4.$IMGEXT`)
 
 TIME=$[SECONDS-TIME1]
 ogEcho log session "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s"
diff --git a/client/shared/scripts/deployImage b/client/shared/scripts/deployImage
--- a/client/shared/scripts/deployImage
+++ b/client/shared/scripts/deployImage
@@ -31,6 +31,12 @@
 #@version 1.0.6 - Se añade la gestión de errores de la CACHE cuando en el engine.cfg se define RESTOREPROTOCOLNOCACHE=NONE.
 #@author  Antonio J. Doblas Viso.
 #@date    2015-02-23
+#@version 1.1 - Cambio de repositorio para el recurso remoto images si es necesario
+#@author  Irina Gomez, ETSII Universidad de Sevilla
+#@date    2015-06-16
+#@version 1.1 - Control de errores en transferencia multicast (ticket #781) 
+#@author  Irina Gomez, ETSII Universidad de Sevilla 
+#@date    2017/04/20 
 #**/
 
 
@@ -57,6 +63,8 @@ PART="$4"
 PROTO="${5^^}"
 PROTO="${PROTO:-"UNICAST"}"
 PROTOOPT="$6"
+# Unidad organizativa.
+[ "$ogunit" != "" ] && OGUNIT="$ogunit"
 
 #Load engine configurator from engine.cfg file.
 #Carga el configurador del engine desde el fichero engine.cfg
@@ -77,17 +85,25 @@ ogEcho log session "$MSG_HELP_ogUnmount $DISK $PART"
 ogUnmount $DISK $PART 2>/dev/null
 
 # Valor por defecto para el repositorio.
-[ "$REPO" == "$(ogGetRepoIp)" ] && REPO="REPO"
-[ "$REPO" == "$(ogGetIpAddress)" ] && REPO="CACHE"
+if [ "$REPO" == "$(ogGetIpAddress)" -o "$REPO" == "CACHE" ]; then
+    MODE="CACHE"
+else
+    ogCheckIpAddress "$REPO"
+    if [ $? == 0 -o "$REPO" == "REPO"  ]; then
+        # Si falla el cambio -> salimos con error repositorio no valido
+        ogChangeRepo $REPO ${OGUNIT} || exit $(ogRaiseError $OG_ERR_NOTFOUND "$REPO $OGUNIT"; echo $?)
+        MODE="REPO"
+    fi
+fi
 
 #Informacioin previa de la imagen
-IMGOS=$(ogGetImageInfo `ogGetPath $REPO $IMGNAME.img`) || exit $(ogRaiseError session $OG_ERR_NOTFOUND "$REPO $2"; echo $?)
-IMGSIZE=$(ls -s `ogGetPath $REPO $IMGNAME.img`| cut -f1 -d" ")
+IMGOS=$(ogGetImageInfo `ogGetPath $MODE $IMGNAME.img`) || exit $(ogRaiseError session $OG_ERR_NOTFOUND "$REPO $2"; echo $?)
+IMGSIZE=$(ls -s `ogGetPath $MODE $IMGNAME.img`| cut -f1 -d" ")
 
 ogEcho log session "[1] REPO=$REPO IMG-FILE=$IMGNAME.img  SIZE=$IMGSIZE (KB)   METADATA=$IMGOS"
 
 # Procesar repositorio.
-case "$REPO" in
+case "$MODE" in
     CACHE)  # Repositorio en caché local.
         NEXTOPERATION=CACHE
     ;;
@@ -102,9 +118,9 @@ case "$REPO" in
 
             # Si protocolo es torrent|torrent-cache o multicast|multicast-cache
             TORRENT|TORRENT-CACHE|MULTICAST|MULTICAST-CACHE|UNICAST|UNICAST-CACHE)
-                ogEcho log session "[2] updateCache REPO \"/$IMGNAME.img\" $PROTO $PROTOOPT"
+                ogEcho log session "[2] updateCache "$REPO" \"/$IMGNAME.img\" $PROTO $PROTOOPT"
                 TIME2=$SECONDS
-                updateCache REPO "/$IMGNAME.img" "$PROTO" "$PROTOOPT"	 	
+                updateCache "$REPO" "/$IMGNAME.img" "$PROTO" "$PROTOOPT"	 	
                 RETVAL=$?
                 TIME2=$[SECONDS-TIME2]
                 ogEcho log session "   [ ]  $MSG_SCRIPTS_TIME_PARTIAL updateCache $[TIME2/60]m $[TIME2%60]s"
@@ -144,6 +160,10 @@ case "$REPO" in
                           	;;
                         esac # del RESTOREPROTOCOLNOTCACHE
                     ;;
+		    57|60)
+			# Time-out en la transferencia multicast (El mensaje de error está enviado)
+			exit $RETVAL
+		    ;;
                 esac
             ;;
             *)  # Error: protocolo desconocido.
@@ -165,9 +185,9 @@ case "$NEXTOPERATION" in
     CACHE)
         PARAMS="CACHE $IMGNAME $DISK $PART" ;;
     UNICAST)
-        PARAMS="REPO $IMGNAME $DISK $PART" ;;
+        PARAMS="$REPO $IMGNAME $DISK $PART" ;;
     MULTICAST)
-        PARAMS="REPO $IMGNAME $DISK $PART $PROTO $PROTOOPT" ;;
+        PARAMS="$REPO $IMGNAME $DISK $PART $PROTO $PROTOOPT" ;;
 esac
 
 # Si existe, ejecuta script personalizado "restoreImageCustom"; si no, llama al genérico "restoreImage".
diff --git a/client/shared/scripts/restoreImage b/client/shared/scripts/restoreImage
--- a/client/shared/scripts/restoreImage
+++ b/client/shared/scripts/restoreImage
@@ -1,6 +1,25 @@
 #!/bin/bash
-# Script de ejemplo para restaurar una imagen.
-# (puede usarse como base para el programa de restauración de imágenes usado por OpenGNSys Admin).
+#/**
+#@file    restoreImage
+#@brief   Script de ejemplo para restaurar una imagen.
+#@param   $1 Repositorio (CACHE, REPO o dirección IP)
+#@param   $2 Nombre canónico de la imagen (sin extensión)
+#@param   $3 Número de disco
+#@param   $4 Número de particion
+#@param   $5 Protocolo (UNICAST, UNICAST-DIRECT, MULTICAST o MULTICAST-DIRECT)
+#@param   $6 Opciones del protocolo
+#@exception OG_ERR_FORMAT   1 formato incorrecto.
+#@exception OG_ERR_NOTFOUND  2 cambio de repositorio: repositorio no encontrado
+#@exception OG_ERR_NOTFOUND  2 fichero de imagen o partición no detectados.
+#@exception $OG_ERR_MCASTRECEIVERFILE  57 Error en la recepción Multicast de un fichero
+#@exception $OG_ERR_PROTOCOLJOINMASTER 60 Error en la conexión de una sesión Unicast|Multicast con el Master
+#@version 1.1 - Cambio de repositorio para el recurso remoto images si es necesario
+#@author  Irina Gomez, ETSII Universidad de Sevilla
+#@date    2015-06-16
+#@version 1.1 - Control de errores en transferencia multicast (ticket #781)
+#@author  Irina Gomez, ETSII Universidad de Sevilla
+#@date    2017/04/20
+#**/
 
 TIME1=$SECONDS
 PROG="$(basename $0)"
@@ -17,7 +36,7 @@ fi
 # Clear temporary file used as log track by httpdlog
 # Limpia los ficheros temporales usados como log de seguimiento para httpdlog
 echo " " > $OGLOGCOMMAND
-[ "$(ogGetCaller)" == "deployImage" ] || echo -n "" > $OGLOGSESSION; 
+ogCheckStringInGroup "$(ogGetCaller)" "deployImage restoreImageCustom" || echo -n "" > $OGLOGSESSION; 
 
 ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
@@ -29,7 +48,25 @@ PART="$4"
 PROTO="${5^^}"
 PROTO=${PROTO:-"UNICAST"}
 PROTOOPT="$6"
+# Si MCASTWAIT menos que tiempo de espera del servidor lo aumento
+if [ "${PROTO%-*}" == "MULTICAST" ] && [[ ${PROTOOPT##*:} =~ ^-?[0-9]+$ ]]; then
+    [ ${MCASTWAIT:-0} -lt ${PROTOOPT##*:} ] && let MCASTWAIT=${PROTOOPT##*:}+5
+fi
 IMGTYPE="${IMGTYPE:-"img"}"
+
+# Unidad organizativa
+[ "$ogunit" != "" ] && OGUNIT="$ogunit/"
+
+# Si es una ip y es igual a la del equipo restaura desde cache
+[ "$REPO" == "$(ogGetIpAddress)" ] && REPO="CACHE"
+# Si es una ip y es distinta a la del recurso samba cambiamos de REPO.
+ogCheckIpAddress $REPO 
+if [ $? == 0 -o $REPO == "REPO" ] ; then
+        # Si falla el cambio -> salimos con error repositorio no valido
+        ogChangeRepo $REPO ${OGUNIT%/} || exit $(ogRaiseError $OG_ERR_NOTFOUND '$REPO $OGUNIT'; echo $?)
+        REPO="REPO"
+fi
+
 # Comprobar que existe la imagen del origen.
 IMGFILE=$(ogGetPath "$REPO" "$IMGNAME.$IMGTYPE")
 IMGDIR=$(ogGetParentPath "$REPO" "$IMGNAME")
@@ -52,7 +89,7 @@ case "$PROTO" in
         COMPRESS=$(ogGetImageCompressor REPO $IMGNAME)
         #TODO comprobar parametros anteriores
         ogEcho log session "[40] ogMcastReceiverPartition $DISK $PART $PORT $TOOL $COMPRESS"
-        ogMcastRequest "$IMGNAME.img" "$PROTOOPT" 
+        ogMcastRequest "$IMGNAME.img" "$PROTOOPT" || exit $?
         ogExecAndLog command ogMcastReceiverPartition "$DISK" "$PART" "$PORT" "$TOOL" "$COMPRESS"
         RETVAL=$?
         ;;
diff --git a/client/shared/scripts/updateCache b/client/shared/scripts/updateCache
--- a/client/shared/scripts/updateCache
+++ b/client/shared/scripts/updateCache
@@ -12,6 +12,8 @@
 #@exception OG_ERR_FORMAT       formato incorrecto.
 #@exception OG_ERR_NOTCACHE     No existe cache -15-
 #@exception $OG_ERR_CACHESIZE   Tamaño de la paticion menor al archivo a descargar -16-
+#@exception $OG_ERR_MCASTRECEIVERFILE  Error en la recepción Multicast de un fichero -57- 
+#@exception $OG_ERR_PROTOCOLJOINMASTER Error en la conexión de una sesión Unicast|Multicast con el Master -60- 
 #@note   
 #@todo: 
 #@version 0.9.1 - integracion EAC
@@ -27,7 +29,12 @@
 #@date    2013-02-20
 #@version 1.0.5 - uso de md5 full para las transferencias torrent, en la llamada => ogUpdateCacheIsNecesary 
 #@date    2014-07-09
-
+#@version 1.1 - Cambio de repositorio para el recurso remoto images si es necesario
+#@author  Irina Gomez, ETSII Universidad de Sevilla
+#@date    2015-06-16
+#@version 1.1 - Control de errores en transferencia multicast (ticket #781) 
+#@author  Irina Gomez, ETSII Universidad de Sevilla 
+#@date    2017/04/20 
 #*/ ##
 
 PROG="$(basename $0)"
@@ -42,11 +49,32 @@ fi
 # Clear temporary file used as log track by httpdlog
 # Limpia los ficheros temporales usados como log de seguimiento para httpdlog
 echo " " > $OGLOGCOMMAND
-[ "$(ogGetCaller)" == "deployImage" -o "$(ogGetCaller)" == "restoreBaseImage" -o "$(ogGetCaller)" == "restoreDiffImage" ] || echo -n "" > $OGLOGSESSION;
+
+if ! [ "$(ogGetCaller)" == "deployImage" -o "$(ogGetCaller)" == "restoreBaseImage" -o "$(ogGetCaller)" == "restoreDiffImage" ]; then
+    echo -n "" > $OGLOGSESSION;
+
+    # Registro de inicio de ejecución
+    ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
+fi
 
 REPOSITORIO="${1^^}"
 PROTOCOLO="${3^^}"
 OPTPROTOCOLO="$4"
+# Si MCASTWAIT menos que tiempo de espera del servidor lo aumento
+if [ "${PROTOCOLO%-*}" == "MULTICAST" ] && [[ ${OPTPROTOCOLO##*:} =~ ^-?[0-9]+$  ]]; then
+    [ ${MCASTWAIT:0} -lt ${OPTPROTOCOLO##*:} ] && let MCASTWAIT=${OPTPROTOCOLO##*:}+5
+fi
+
+# Unidad organizativa.
+[ "$ogunit" != "" ] && OGUNIT="$ogunit/"
+
+# Si es una ip y es distinta a la del recurso samba cambiamos de REPO.
+ogCheckIpAddress $REPOSITORIO
+if [ $? == 0 -o $REPOSITORIO == "REPO" ] ; then
+        # Si falla el cambio -> salimos con error repositorio no valido
+        ogChangeRepo $REPOSITORIO $OGUNIT || exit $(ogRaiseError $OG_ERR_NOTFOUND $REPOSITORIO; echo $?)
+        REPOSITORIO="REPO"
+fi
 REPOIP=$(ogGetRepoIp)
 ogEcho log session  $REPOSITORIO $REPOIP $PROTOCOLO $OPTPROTOCOLO
 
@@ -75,7 +103,7 @@ else
 	# Si la imagen es monolitica y ha elegido protocolo = RSYNC salimos con error.
 	[ $PROTOCOLO == "RSYNC" ] && exit $(ogRaiseError session $OG_ERR_DONTSYNC_IMAGE "REPO $2"; echo $?)
 	IMGSYNC=FALSE
-	ogUpdateCacheIsNecesary "$1" "$2" "$PROTOCOLO"
+	ogUpdateCacheIsNecesary "$REPOSITORIO" "$2" "$PROTOCOLO"
 	RETVAL=$?
 fi
 # si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
@@ -174,7 +202,7 @@ TIME1=$SECONDS
 
 case "$PROTOCOLO" in
 	TORRENT)
-		ogEcho log session "ogCopyFile $1 $2.torrent absolute $OGCAC/$OGIMG"
+		ogEcho log session "ogCopyFile $REPOSITORIO $2.torrent absolute $OGCAC/$OGIMG"
 		# tiempos 
 		timewait=$(expr $(printf '%d\n' 0x$(ogGetMacAddress | awk -F: '{print $5$6}')) \* 120 / 65535)                         
 		ogExecAndLog command ogCopyFile $REPOSITORIO "$2.torrent" "$IMGDIR"
@@ -182,7 +210,7 @@ case "$PROTOCOLO" in
     		#TODO comprobar que el fichero torrent está en cache
 		# retardamos el inicio -aleatorio de 0 a 120 segundos- al tracker para gestionar mas de +-40 equipos 
 		P2PWAIT=$[ ( $RANDOM % 120 )  + 1 ]
-		ogEcho log session "   [ ] $MSG_SCRIPTS_TASK_SLEEP :  $P2PWAIT seconds ogTorrentStart CACHE $2.torrent $4"
+		ogEcho log session "   [ ] $MSG_SCRIPTS_TASK_SLEEP :  $P2PWAIT seconds"
 		sleep $P2PWAIT
 		ogEcho log session "   [  ] $MSG_SCRIPTS_TASK_START:  ogTorrentStart CACHE $2.torrent $4"
 		ogExecAndLog command ogTorrentStart CACHE "$2.torrent" $4
@@ -193,34 +221,15 @@ case "$PROTOCOLO" in
 		fi
 	;;
 	MULTICAST)
-		PORT=$(echo $OPTPROTOCOLO | cut -f1 -d":")
-		let PORTAUX=$PORT+1
 		ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_CHECKMCASTSESSION : $REPOIP:$PORTAUX:$PORT"
 		#TODO: ticket 379
 		NUMBER=$[ ( $RANDOM % 30 )  + 1 ]
 		sleep $NUMBER
 		#FIN TODO
-		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
-		then 
-			ogExecAndLog command ogMcastReceiverFile $PORT CACHE "$2"
-
-		else
-		    # TODO ticket 379 Realizar la petición basada en identificador de operacion
-	   		ogEcho log session "$MSG_SCRIPTS_TASK_START :  hose $REPOIP 2009 --out sh -c \"echo -ne START_MULTICAST $2 $OPTPROTOCOLO\""
-	   		hose $REPOIP 2009 --out sh -c "echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
-	   		#echo "espero y llamo a: ogMcastReceiverFile $PORT CACHE $2"
-	   		sleep 10
-	   		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
-	   		then 
-	   			ogExecAndLog command ogMcastReceiverFile $PORT CACHE "$2"
-			else
-				ogEcho log session "$MSG_SCRIPTS_TASK_ERR : hose $REPOIP 2009 --out sh -c echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
-	   			exit $OG_ERR_UPDATECACHE
-	   		fi
-		fi
-		#cat $OGLOGCOMMAND.tmp | grep -B1 "Transfer complete"
-		sleep 5
-		#cat $OGLOGCOMMAND.tmp | grep -B1 "Transfer complete"
+		ogEcho log session ogMcastRequest "$2" $OPTPROTOCOLO
+		ogExecAndLog command ogMcastRequest "$2" $OPTPROTOCOLO || exit $?
+		ogEcho log session ogMcastReceiverFile ${OPTPROTOCOLO%%:*} CACHE "$2"
+		ogExecAndLog command ogMcastReceiverFile ${OPTPROTOCOLO%%:*} CACHE "$2" || exit $?
 		RESUMEUPDATECACHE=$(grep -m 1  -B1 "Transfer complete" $OGLOGCOMMAND.tmp)
 	;;
 	UNICAST)
@@ -242,8 +251,8 @@ case "$PROTOCOLO" in
 	   if [ -d $REPOFILE ]; then
 		# Si es sincronizada tipo directorio.
 		[ -d "$OGCAC$OGIMG/$2" ] || mkdir "$OGCAC$OGIMG/$2"
-		ogEcho log session "rsync -aHAX$OPTRSYNC  $USERRSYNC@$REPOIP::ogimages/$2/ $OGCAC$OGIMG/$2"
-		rsync -aHAX$OPTRSYNC  $PASSWORD "$USERRSYNC@$REPOIP::ogimages/$2/" "$OGCAC$OGIMG/$2" 2>> $OGLOGCOMMAND  | egrep "^sent|^sending|^total%" >>  $OGLOGCOMMAND
+		ogEcho log session "rsync -aHAX$OPTRSYNC  $USERRSYNC@$REPOIP::ogimages/$OGUNIT$2/ $OGCAC$OGIMG/$2"
+		rsync -aHAX$OPTRSYNC  $PASSWORD "$USERRSYNC@$REPOIP::ogimages/$OGUNIT$2/" "$OGCAC$OGIMG/$2" 2>> $OGLOGCOMMAND  | egrep "^sent|^sending|^total%" >>  $OGLOGCOMMAND
            else
 		# Si es sincronizada tipo archivo.
 		[ "${2##*.}" == "img" ] && IMGTYPE="img" ||  IMGTYPE="diff"
@@ -273,7 +282,8 @@ case "$PROTOCOLO" in
 		[ ${PIPESTATUS[0]} -eq 0 ] && RETVAL="1"|| RETVAL="2"
 		# Desmonto las imagenes
 		ogUnmountImage CACHE  "$IMGNAME" $IMGTYPE
-		ogUnmountImage REPO  "$IMGNAME" $IMGTYPE
+	 	ogUnmountImage REPO  "$IMGNAME" $IMGTYPE
+		ogUnlockImage CACHE "$2"
 	   fi
 	;;
 esac
