Versión 1.0.4, #531: Integrar versión 1.0.4 en rama principal.
git-svn-id: https://opengnsys.es/svn/trunk@3259 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/admin/Interface/RestaurarImagen b/admin/Interface/RestaurarImagen
--- a/admin/Interface/RestaurarImagen
+++ b/admin/Interface/RestaurarImagen
@@ -54,7 +54,7 @@ echo "$MSG_INTERFACE_START $0 $*" | tee -a $OGLOGSESSION $OGLOGFILE
 
 
 # Si el origen(pariticion) esta bloqueada salir.
-echo "TODO comprobando si esta bloqueado el $1 $2" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[1] TODO: $MSG_HEL_ogIsLocked: ogIsLocked $1 $2" | tee -a $OGLOGSESSION $OGLOGFILE
 #if ogIsLocked $1 $2; then
 #	ogRaiseError $OG_ERR_LOCKED "$MSG_PARTITION, $1 $2"
 #	exit $?
@@ -66,9 +66,10 @@ REPO=${4:-"REPO"}
 [ "$REPO" == "$(ogGetIpAddress)" ] && REPO="CACHE"
 [ "$REPO" == "CACHE" ] && REPO="CACHE"
 
-#Informacioin previa de la imagen
-IMGSIZE=$(ls -s `ogGetPath $REPO $3.img`| cut -f1 -d" ")
-IMGOS=$(ogGetImageInfo `ogGetPath $REPO $3.img`)
+#Informacion previa de la imagen
+IMGOS=$(ogGetImageInfo `ogGetPath $REPO $3.img`) || exit $(echo "ERROR: $OG_ERR_NOTFOUND $MSG_ERR_NOTFOUND, IMAGEN $REPO $3" | tee -a $OGLOGSESSION $OGLOGFILE; ogRaiseError $OG_ERR_NOTFOUND "$MSG_ERR_NOTFOUND, $REPO $3"; echo $?)
+#IMGOS=$(ogGetImageInfo `ogGetPath $REPO $3.img`) || exit $(ogRaiseError $OG_ERR_NOTFOUND "$MSG_ERR_NOTFOUND, $REPO $3"; echo $?)
+IMGSIZE=$(ls -s `ogGetPath $REPO $3.img`| cut -f1 -d" ") 
 
 echo "[1] IMG-FILE=$3  SIZE=$IMGSIZE (KB)   METADATA=$IMGOS"  | tee -a $OGLOGSESSION $OGLOGFILE
 
diff --git a/server/bin/setsmbpass b/server/bin/setsmbpass
--- a/server/bin/setsmbpass
+++ b/server/bin/setsmbpass
@@ -11,7 +11,8 @@
 PROG=$(basename $0)
 OPENGNSYS=${OPENGNSYS:-"/opt/opengnsys"}
 SAMBAUSER="opengnsys"				# Usuario por defecto.
-CLIENTINITRD=$OPENGNSYS/tftpboot/ogclient/oginitrd.img
+TFTPDIR=$OPENGNSYS/tftpboot
+CLIENTINITRD=$TFTPDIR/ogclient/oginitrd.img
 TMPDIR=/tmp/ogclient$$
 
 # Control básico de errores.
@@ -30,6 +31,13 @@ if [ -r $CLIENTINITRD ]; then
 	stty -echo 2>/dev/null
 	echo -n "Clave del usuario Samba: "
 	read SAMBAPASS
+	# Solo se deben aceptar números y letras para la clave de acceso.
+	if [ -n "${SAMBAPASS//[a-zA-Z0-9]/}" ]; then
+		echo
+		echo "$PROG: Error: la clave solo debe contener caracteres alfanuméricos" >&2
+		stty echo 2>/dev/null
+		exit 2
+	fi
 	echo
 	echo -n "Confirmar clave: "
 	read SAMBAPASS2
@@ -51,6 +59,9 @@ if [ -r $CLIENTINITRD ]; then
 		echo "$PROG: Aviso: no se ha modificado la clave del cliente."
 	fi
 	rm -fr $TMPDIR
+	md5sum $CLIENTINITRD | cut -f1 -d" " > $CLIENTINITRD.sum
+	cp -a $CLIENTINITRD $TFTPDIR
+	cp -a $CLIENTINITRD.sum $TFTPDIR
 else
 	SAMBAPASS="og"                  # Clave por defecto.
         echo "$PROG: Aviso: no se ha modificado la clave del cliente."
