version1.0 #369  transferencias multicast
git-svn-id: https://opengnsys.es/svn/branches/version1.0@1851 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/admin/Sources/Services/ogAdmRepoAux b/admin/Sources/Services/ogAdmRepoAux
--- a/admin/Sources/Services/ogAdmRepoAux
+++ b/admin/Sources/Services/ogAdmRepoAux
@@ -21,5 +21,9 @@ case $PARM1 in
 		MCASTOPT=$PARM3
 		echo "/opt/opengnsys/bin/sendFileMcast $FILE $MCASTOPT" >> $REPOLOG
 		/opt/opengnsys/bin/sendFileMcast $FILE $MCASTOPT >> $REPOLOG
+		echo $? >> $REPOLOG
+	;;
+	default)
+	    echo "Solicitud con parametros: -  $PARM  - no realizada: No registrada o con errores" >> $REPOLOG
 	;;
 esac
