#730: No iniciar servicio {{{ogAdmRepo}}} y solo mantener activo {{{ogAdmRepoAux}}} en el repositorio; actualizar lista de tickets cerrados.
git-svn-id: https://opengnsys.es/svn/branches/version1.1@4821 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/admin/Sources/Services/opengnsys.init b/admin/Sources/Services/opengnsys.init
--- a/admin/Sources/Services/opengnsys.init
+++ b/admin/Sources/Services/opengnsys.init
@@ -159,9 +159,10 @@ arranca_demonios() {
      sleep 5 # Damos tiempo a que ogAdmServer este funcionando
   fi
   if [ $RUN_OGADMREPO = "yes" ]; then
-     $ACTIONMSG "Iniciando demonio: $REPONAME"
-     $DAEMONSTART $REPODAEMON $EXTRAOPTS $REPODAEMON_OPTIONS $ENDOPTS
-     [ $? = 0 ] && $SUCCESSMSG || $FAILMSG
+     # No iniciar ogAdmRepo
+     #$ACTIONMSG "Iniciando demonio: $REPONAME"
+     #$DAEMONSTART $REPODAEMON $EXTRAOPTS $REPODAEMON_OPTIONS $ENDOPTS
+     #[ $? = 0 ] && $SUCCESSMSG || $FAILMSG
      $ACTIONMSG "Iniciando demonio: $REPOAUXNAME"
      faucet $REPOAUXPORT --daemon --in bash -c "$REPOAUXDAEMON"
      [ $? = 0 ] && $SUCCESSMSG || $FAILMSG
