#565 se crean script: partclone2sync y clean-mountdirimage. Se controla el error al crear la imagen.
git-svn-id: https://opengnsys.es/svn/branches/version1.0@4119 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/server/bin/createfileimage b/server/bin/createfileimage
--- a/server/bin/createfileimage
+++ b/server/bin/createfileimage
@@ -55,7 +55,7 @@ SIZEREQUIRED=$3
 [ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
 
 echo  CREATE_IMAGE "$1" $IMGEXT $SIZEREQUIRED
-echo -ne CREATE_IMAGE "$1" $IMGEXT $SIZEREQUIRED| /opt/opengnsys/sbin/ogAdmRepoAux
+echo -ne CREATE_IMAGE "$1" $IMGEXT $SIZEREQUIRED| /opt/opengnsys/sbin/ogAdmRepoAux  || exit $?
 echo "Los resultado se registran en $REPOLOG. "
 
 rm $IMGFILE.lock
