#565 #564 cambio de extension las imagenes diferenciales a img.diff
git-svn-id: https://opengnsys.es/svn/branches/version1.0@4039 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/server/bin/createfileimage b/server/bin/createfileimage
--- a/server/bin/createfileimage
+++ b/server/bin/createfileimage
@@ -36,14 +36,18 @@ fi
 
 IMGEXT="$2"
 
-# Si existe imagen, Comprobamos que  es sincronizable
+# Si existe imagen, Comprobamos que no esta bloqueada y que es sincronizable
 IMGFILE="$REPODIR/$1.$IMGEXT"
 if [ -f $IMGFILE ]; then
+   [ -f $IMGFILE.lock ] && echo "$PROG: Error: $MSG_ERR_LOCKED $1 $IMGEXT" && exit 4
+	
    if ! file $IMGFILE | grep " BTRFS Filesystem" >/dev/null ; then
 	echo "$PROG: Error: $MSG_ERR_DONTSYNC_IMAGE $1 $2"
 	exit 71
    fi
 fi
+
+touch $IMGFILE.lock
 
 # El tamaño minimo de la imagen es 300000 para poder formatear en fs btrfs.
 SIZEREQUIRED=$3
@@ -52,3 +56,5 @@ SIZEREQUIRED=$3
 echo  CREATE_IMAGE "$1" $IMGEXT $SIZEREQUIRED
 echo -ne CREATE_IMAGE "$1" $IMGEXT $SIZEREQUIRED| /opt/opengnsys/sbin/ogAdmRepoAux
 echo "Los resultado se registran en $REPOLOG. "
+
+rm $IMGFILE.lock
diff --git a/server/bin/reduceimage b/server/bin/reduceimage
--- a/server/bin/reduceimage
+++ b/server/bin/reduceimage
@@ -7,6 +7,7 @@
 #@return  
 #@exception OG_ERR_FORMAT     # 1 formato incorrecto.
 #@exception OG_ERR_NOTFOUND # 2 Fichero o dispositivo no encontrado
+#@exception OG_ERR_LOCKED          # 4 Partición o fichero bloqueado
 #@exception OG_ERR_DONTSYNC_IMAGE  #71 Imagen no sincronizable (es monolitica)
 #@version 1.0 - Reducir tamaño imagen sincronizable
 #@author  Irina Gomez
@@ -34,16 +35,20 @@ if [ "$USER" != "root" ]; then
         exit 1
 fi
 
-[ "$2" == "" ] && IMGEXT="img" || IMGEXT="$2"
-# Comprobamos que existe imagen
+[ "$2" == "" -o "$2" == "img" ] && IMGEXT="img" || IMGEXT="img.diff"
+# Comprobamos que existe imagen y que no este bloqueada
 IMGFILE="$REPODIR/$1.$IMGEXT"
 [ ! -f $IMGFILE ] && echo "$PROG: Error: $MSG_ERR_NOTFOUND $1 $IMGEXT" && exit 2
-
+[ -f $IMGFILE.lock ] && echo "$PROG: Error: $MSG_ERR_LOCKED $1 $IMGEXT" && exit 4 
 
 # Comprobar que la imagen  es sincronizable
 if ! file $IMGFILE | grep " BTRFS Filesystem" >/dev/null ; then
 	echo "$PROG: Error: $MSG_ERR_DONTSYNC_IMAGE $1 $2"
 	exit 71
 fi
-echo -ne REDUCE_IMAGE "$1" $IMGEXT | /opt/opengnsys/sbin/ogAdmRepoAux
+
+touch $IMGFILE.lock
+echo -ne REDUCE_IMAGE "$1" ${IMGEXT#*\.} | /opt/opengnsys/sbin/ogAdmRepoAux
 echo "Los resultado se registran en $REPOLOG. "
+
+rm $IMGFILE.lock
