Versión 1.0.4, #514: Script {{{setsmbpass}}} comprueba que la clave Samba sea alfanumérica.
git-svn-id: https://opengnsys.es/svn/branches/version1.0@2831 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/server/bin/setsmbpass b/server/bin/setsmbpass
--- a/server/bin/setsmbpass
+++ b/server/bin/setsmbpass
@@ -30,6 +30,13 @@ if [ -r $CLIENTINITRD ]; then
 	stty -echo 2>/dev/null
 	echo -n "Clave del usuario Samba: "
 	read SAMBAPASS
+	# Solo se deben aceptar números y letras para la clave de acceso.
+	if [ -n "${SAMBAPASS//[a-zA-Z0-9]/}" ]; then
+		echo
+		echo "$PROG: Error: la clave solo debe contener caracteres alfanuméricos" >&2
+		stty echo 2>/dev/null
+		exit 2
+	fi
 	echo
 	echo -n "Confirmar clave: "
 	read SAMBAPASS2
