Cambios en la estructura del cliente con initrd. Borrado codigo antiguo del navegador.
git-svn-id: https://opengnsys.es/svn/trunk@186 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/opengnsys-client/boot/initrd-generator b/opengnsys-client/boot/initrd-generator
--- a/opengnsys-client/boot/initrd-generator
+++ b/opengnsys-client/boot/initrd-generator
@@ -13,8 +13,33 @@ INITSCRIPT=$NEWROOT$CHROOTINITSCRIPT
 # Comprueba los argumentos pasados para modificar los valores por defecto
 function parsearParametros
 {
-    #TODO
-    sleep 1
+    while [ $# -ne 0 ];do
+        case $1 in
+            ("-d")
+            shift
+            if [ $# -eq 0 ];then
+                echo "Error en los argumentos"
+                return -1
+            else
+                DIST=$1
+                return -1
+            fi
+            ;;
+            ("-v")
+            shift
+            if [ $# -eq 0 ];then
+                echo "Error en los argumentos"
+                return -1
+            else
+                DIST=$1
+                return -1
+            fi
+            ;;
+            ("-l")
+            shift
+            ;;
+        esac
+    done
 }
 
 function descargar
@@ -173,17 +198,17 @@ function agregarNuevoArranque
     #echo "::shutdown:/sbin/swapoff -a" >> inittab
 
     # Primero ejecutamos el dhcp
-    echo "#! /bin/sh" > $INITSCRIPT
-    echo "set -e" >> $INITSCRIPT
-    echo "mkdir -p /var/state/dhcp" >> $INITSCRIPT
-    echo "/sbin/dhclient" >> $INITSCRIPT
+    echo '#! /bin/sh' > $INITSCRIPT
+    echo 'set -e' >> $INITSCRIPT
+    echo 'mkdir -p /var/state/dhcp' >> $INITSCRIPT
+    echo '/sbin/dhclient' >> $INITSCRIPT
 
     # Montamos NFS y ejecutamos el script con nombre nuestra ip
     echo "DHCP_SERVER=\`grep -h dhcp-server-identifier /var/lib/dhcp3/dhclient.* | sed 's/[^0-9]*\(.*\);/\1/' | head -1\`" >> $INITSCRIPT
     echo "IP=\`grep -h fixed-address /var/lib/dhcp3/dhclient.* | sed 's/[^0-9]*\(.*\);/\1/' | head -1\`" >> $INITSCRIPT
     echo "mkdir -p /opt/opengnsys" >> $INITSCRIPT
     echo "mount -t nfs -onolock \$DHCP_SERVER:/opt/opengnsys/client/ /opt/opengnsys/" >> $INITSCRIPT
-    echo "/opt/opengnsys/init/\$IP.sh" >> $INITSCRIPT
+    echo "/opt/opengnsys/etc/preinit/default.sh" >> $INITSCRIPT
 
     chmod +x $INITSCRIPT
 }
