#739: Retocar fichero Vagrant para permitir reaprovisionamiento de servidor y solucionar problemas que pueden producirse durante una instalación previa de paquetes.
git-svn-id: https://opengnsys.es/svn/branches/version1.1@5279 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/installer/vagrant/Vagrantfile-trunk-vbox b/installer/vagrant/Vagrantfile-trunk-vbox
--- a/installer/vagrant/Vagrantfile-trunk-vbox
+++ b/installer/vagrant/Vagrantfile-trunk-vbox
@@ -22,15 +22,19 @@ LOCALWEBPORT = 8443
 
 # OpenGnsys Server provisioning script: prepare repo disk, install OpenGnsys, change default interface, configure DHCP server.
 OGSERVERSCRIPT = <<EOT
-# Mount repository disk.
-test -n "$(blkid /dev/sdb1 | grep ext4)" && exit
-echo -e "o\nn\np\n\n\n\nw" | fdisk /dev/sdb
-mkfs -t ext4 /dev/sdb1
-mkdir -p /opt/opengnsys/images
-echo "/dev/sdb1  /opt/opengnsys/images  ext4  defaults  0  0" >> /etc/fstab
-mount -a
+# Exit if OpenGnsys is installed.
+[ -f /opt/opengnsys/doc/VERSION.txt ] && echo "Cannot provision, OpenGnsys is already installed." && exit 1
+# Mount repository disk, if necesary.
+if [ -n "$(blkid /dev/sdb1 | grep ext4)" ]; then
+    echo -e "o\nn\np\n\n\n\nw" | fdisk /dev/sdb
+    mkfs -t ext4 /dev/sdb1
+    mkdir -p /opt/opengnsys/images
+    echo "/dev/sdb1  /opt/opengnsys/images  ext4  defaults  0  0" >> /etc/fstab
+    mount -a
+fi
 # Install OpenGnsys and change server address.
-wget -q http://opengnsys.es/svn/trunk/installer/opengnsys_installer.sh -O - | bash
+wget -q http://opengnsys.es/svn/trunk/installer/opengnsys_installer.sh -O - | bash || exit $?
+mv /opt/opengnsys/log/bash.log /opt/opengnsys/log/opengnsys_installer.log
 echo y | sudo /opt/opengnsys/bin/setserveraddr eth1
 # Insert DHCP data.
 for ((i=#{NCLIENTS}; i>0; i--)); do
