version 1.0.1 #381   cloneRemoteFromMaster
git-svn-id: https://opengnsys.es/svn/branches/version1.0@1971 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/cloneRemoteFromMaster b/client/shared/scripts/cloneRemoteFromMaster
--- a/client/shared/scripts/cloneRemoteFromMaster
+++ b/client/shared/scripts/cloneRemoteFromMaster
@@ -50,10 +50,20 @@
 
 #*/ ##
 
+#test 1. cliente sin particiones.    Detectado  TODO: crear estrucutras de particiones
+#test 2. cliente con particion mas pequeña. Detectado.
+#test 3. cleinte con particion destinio no formateado.  Detectado.
+#test 4. cliente con particion destino ocupado por el usuario pwd .  FALLO.
+#test 5. master sin origen particion.
+#test 6. master sin origen fichero.
+
+
+
+trap "pkill faucet; exit 1" 0 1 2 3 6 9 14 15
 
 TIME1=$SECONDS
 PROG="$(basename $0)"
-if [ $# -lt 1 ]; then
+if [ $# -lt 1 -o "$1" == "help" ]; then
 	echo "cloneRemoteFromMaster ipmaster disk init [MULTICAST|UNICAST] session disk part tool comp"
 	exit 1
 fi
@@ -80,7 +90,10 @@ case $PROTOCOL in
 	UNICAST|unicast) 
 		SESSIONUCASTSERVER=$5
     	SESSIONUCASTCLIENT=`echo $5 | awk -F: '{print $1}'`:$MASTERIP
-	;;
+    ;;
+    *)
+     exit $(ogRaiseError $OG_ERR_FORMAT "Protocolo $PROTOCOL no soportado en esta operacion"; echo $?)
+    ;;
 esac
 # contenedor destino (disco particion)
 DISKTARGET=$6
@@ -106,20 +119,23 @@ case $MASTERIP in
 			ogRaiseError $OG_ERR_NOTFOUND "$2 $3"; exit $?
 		fi 
 		echo $MODEMASTER
-		# Preparando instrucción del Master segun $MODEMASTER{SENDPARTITION SENDFILE}
-					
+		# Preparando instrucción del Master segun $MODEMASTER{SENDPARTITION SENDFILE}					
 		case "$MODEMASTER" in
 			SENDPARTITION)
 				echo "[5] Master en modo  $MODEMASTER: informacion inicial a los clientes-slaves"
-				faucet 4000 --out echo "WORKING" &			
+				if ps aux | grep -v grep | grep "faucet 4000" 
+				then
+					ogRaiseError $OG_ERR_NOTFOUND "MASTER: puerto en uso: 118"; exit $?	
+				else
+					faucet 4000 --out echo "WORKING" &	
+				fi				
 				echo "[10]: Desmontando DISK:$DISKSOURCE PARTITION:$PARTSOURCE"
-				ogUnmount $2 $3 || exit $?
-				echo "[15]: Calculando la reduccion del sistema de archivos DISK:$DISKSOURCE PARTITION:$PARTSOURCE SIZE:$SIZE"
+				ogUnmount $2 $3 ||  exit $(ogRaiseError $OG_ERR_LOCKED "no se puede desmontar $2 $3  l124"; echo $?)
 				#Obtener tamaño de la partición.
-				SIZE=$(ogGetPartitionSize $2 $3)  
-				# Reducir el sistema de archvios.
-				ogReduceFs $2 $3 || exit $?
-				REDSIZE=$(ogGetFsSize $2 $3) 	
+				SIZE=$(ogGetPartitionSize $2 $3)  || exit $(ogRaiseError $OG_ERR_REDUCEFS "Error al detectar tamaño partcion $2 $3  l127"; echo $?)
+				echo "[15]: Calculando la reduccion del sistema de archivos DISK:$DISKSOURCE PARTITION:$PARTSOURCE SIZE:$SIZE"
+				ogReduceFs $2 $3 || exit $(ogRaiseError $OG_ERR_REDUCEFS "Error al reducir el FS $2 $3  l129"; echo $?)
+				REDSIZE=$(ogGetFsSize $2 $3) || exit $(ogRaiseError $OG_ERR_REDUCEFS "Error al detectar el nuevo FS $2 $3  l130"; echo $?)	
 				echo "[20]: Reducido el  sistema de archivos a $REDSIZE  $DISKSOURCE $PARTSOURCE"
 				if [ $REDSIZE -lt $SIZE ]; then
     					echo "[24] Redimensionar partición a $REDSIZE KB."
@@ -127,8 +143,12 @@ case $MASTERIP in
 				fi
 				echo "[25] Master en Modo $MODEMASTER: informacion de transferencia a los clientes-slaves $PROTOCOL $TOOLCLONE $COMPRESOR $REDSIZE"
 				pkill faucet
-				faucet 4000 --out echo "READY $TOOLCLONE $COMPRESOR $REDSIZE" &
-						
+				if ps aux | grep -v grep | grep "faucet 4000" 
+				then
+					ogRaiseError $OG_ERR_NOTFOUND "MASTER: puerto en uso: 140"; exit $?	
+				else
+					faucet 4000 --out echo "READY $TOOLCLONE $COMPRESOR $REDSIZE" &
+				fi
 				case $PROTOCOL in
 					MULTICAST|multicast)
 						echo "[29] ogMcastSendPartition $DISKSOURCE $PARTSOURCE $SESSIONMCASTSERVER $TOOLCLONE $COMPRESOR" 
@@ -148,15 +168,27 @@ case $MASTERIP in
    		 			ogExtendFs $2 $3
 				fi
 				pkill faucet
+				if [ $RETVAL == 0 ]
+				then 
+					exit 0
+				else
+				    exit $(ogRaiseError $OG_ERR_MCASTSENDPARTITION "Error al enviar la particion  $2 $3 con protocolo $PROTOCOL l167"; echo $?)
+				fi
+				
 			;;
 			SENDFILE)				
 				echo "[5] Master en modo  $MODEMASTER: informacion inicial a los clientes-slaves"
 				echo "[10]: Preparando Imagen: $IMG"
-				TOOLCLONE=$(ogGetImageProgram $2 $3)
-				COMPRESOR=$(ogGetImageCompressor $2 $3)
-				REDSIZE=$(ogGetImageSize $2 $3)
+				TOOLCLONE=$(ogGetImageProgram $2 $3) || exit $(ogRaiseError $OG_ERR_LOCKED "TOOLCLONE no detectado l174"; echo $?)
+				COMPRESOR=$(ogGetImageCompressor $2 $3) exit $(ogRaiseError $OG_ERR_LOCKED "COMPRESOR NO DETECTADO l175"; echo $?)
+				REDSIZE=$(ogGetImageSize $2 $3) exit $(ogRaiseError $OG_ERR_LOCKED "REDSIZE NO DETECTADO l176"; echo $?)
 				echo "[25] Master en Modo $MODEMASTER: informacion de transferencia a los clientes-slaves $PROTOCOL $TOOLCLONE $COMPRESOR $REDSIZE"
-				faucet 4000 --out echo "READY $TOOLCLONE $COMPRESOR $REDSIZE" &
+				if ps aux | grep -v grep | grep "faucet 4000" 
+				then
+					ogRaiseError $OG_ERR_NOTFOUND "MASTER: puerto en uso: 140"; exit $?	
+				else
+					faucet 4000 --out echo "READY $TOOLCLONE $COMPRESOR $REDSIZE" &
+				fi				
 				case $PROTOCOL in
 					MULTICAST|multicast)
 						echo "[29] ogMcastSendFile $2 $3.img $SESSIONMCASTSERVER "
@@ -169,22 +201,27 @@ case $MASTERIP in
  					;;
  				esac							
 				pkill faucet	
+				if [ $RETVAL == 0 ]
+				then 
+					exit 0
+				else
+				    exit $(ogRaiseError $OG_ERR_MCASTSENDFILE "Error al enviar la image $2 $3.img con protocolo $PROTOCOL l200"; echo $?)
+				fi
 			;;
 		esac
-		#exit $RETVAL
-        exit 0
 		# FIN Preparando instrucción del Master segun $MODEMASTER{SENDPARTITION SENDFILE}
 	;;
 	*)
 		echo "[1] Equipo -Client- preparando para recibir datos $PROTOCOL"
+		ogDiskToDev $DISKTARGET $PARTTARGET &>/dev/null || exit $(ogRaiseError $OG_ERR_LOCKED "El cliente no tiene esas particiones $DISKTARGET $PARTTARGET l211"; echo $?) 	
 		# TODO: si el cliente no está en la lista de clientes UNICAST salir.
 		case $PROTOCOL in
 			UNICAST|unicast)
- 				echo "$SESSIONUCASTSERVER" | grep $HOSTIP || exit 1			
- 			;;
+ 				echo "$SESSIONUCASTSERVER" | grep $HOSTIP || exit $(ogRaiseError $OG_ERR_PROTOCOLJOINMASTER "Este cliente no pertence a la sesion UNICAST l214"; echo $?)
+			;;
  		esac	
  		echo "[2] Desmontando particion destino"	 
-		ogUnmount $DISKTARGET $PARTTARGET 
+		ogUnmount $DISKTARGET $PARTTARGET || exit $(ogRaiseError $OG_ERR_LOCKED "no se puede desmontar la particion destino $2 $3  l218"; echo $?)
 		echo -n "[25] Buscando informacion extra sobre la clonacion con el master $MASTERIP: "
 		sleep 10
 		TIMEWAITMASTER=120
@@ -194,9 +231,9 @@ case $MASTERIP in
 		do
 			INFOEXTRA=`hose $MASTERIP 4000 --in cat 2>/dev/null`
 			sleep 10; echo -n "."
-			#Si no consigue conectar con Master, comienza el timeout $TIMEWAITMASTER para abortar
+			echo comienza el timeout $TIMEWAITMASTER para abortar
 			[ -z "$INFOEXTRA" ] && let TIMEWAITMASTER=$TIMEWAITMASTER-10
-			[ "$TIMEWAITMASTER" -gt "0" ] || ogRaiseError $OG_ERR_PROTOCOLJOINMASTER " " || exit $?
+			[ "$TIMEWAITMASTER" -gt "0" ] || exit $(ogRaiseError $OG_ERR_PROTOCOLJOINMASTER " l230 "; echo $?)
 			#Si primer parametro desde el server es READY, salimos del bucle
 			GETINFO=$(echo $INFOEXTRA | awk '{print $1}')
 			[ "$GETINFO" == "READY" ] && GETINFO=OK 
@@ -206,12 +243,8 @@ case $MASTERIP in
 		COMPRESOR=$(echo $INFOEXTRA | awk '{print $3}')
 		SIZEIMAGE=$(echo $INFOEXTRA | awk '{print $4}')
 		echo -n "[26] $INFOEXTRA = herramienta= $TOOLCLONE  compresor= $COMPRESOR size= $SIZEIMAGE "
+		ogMount $DISKTARGET $PARTTARGET || ogFormat $DISKTARGET $PARTTARGET
 		SIZEPARTTARGET=$(parted `ogDiskToDev $DISKTARGET $PARTTARGET` unit kB print | awk '{y=x; x=$4};END{print y}' | tr -d kB) 
-		if [ -z $SIZEPARTTARGET ]; then
-			echo "[5] TODO Formateando particion destino si no es accesible por parted"	 
-			ogFormat $DISKTARGET $PARTTARGET 
-			SIZEPARTTARGET=$(parted `ogDiskToDev $DISKTARGET $PARTTARGET` unit kB print | awk '{y=x; x=$4};END{print y}' | tr -d kB) 
-		fi 
 		echo "[29] comprobando que el tamaño de la imagen $SIZEIMAGE es menor que el de la particion destino $SIZEPARTTARGET"	 
 		# comprobamos que el tamaño de a imagen es menor que la del cliente.
 		if [ "$SIZEIMAGE" -lt "$SIZEPARTTARGET" ]
@@ -220,24 +253,15 @@ case $MASTERIP in
 				case $PROTOCOL in
 					MULTICAST|multicast)
 						echo ogMcastReceiverPartition $DISKTARGET $PARTTARGET $SESSIONMCASTCLIENT $TOOLCLONE $COMPRESOR 
-						ogMcastReceiverPartition "$DISKTARGET" "$PARTTARGET" "$SESSIONMCASTCLIENT" "$TOOLCLONE" "$COMPRESOR"  || exit $?
-		 					;;
+						ogMcastReceiverPartition "$DISKTARGET" "$PARTTARGET" "$SESSIONMCASTCLIENT" "$TOOLCLONE" "$COMPRESOR"  || exit $(ogRaiseError $OG_ERR_MCASTRECEIVERPARTITION " l251 "; echo $?)
+		 			;;
  					UNICAST|unicast)
  						echo ogUcastReceiverPartition $DISKTARGET $PARTTARGET $SESSIONUCASTCLIENT $TOOLCLONE $COMPRESOR
- 						ogUcastReceiverPartition $DISKTARGET $PARTTARGET $SESSIONUCASTCLIENT $TOOLCLONE $COMPRESOR || exit $?
+ 						ogUcastReceiverPartition $DISKTARGET $PARTTARGET $SESSIONUCASTCLIENT $TOOLCLONE $COMPRESOR || exit $(ogRaiseError $OG_ERR_UCASTRECEIVERPARTITION " l230 "; echo $?)
  					;;
- 				esac
-			
-			
-			echo "[90] Extender sistema de archivos"
-			ogExtendFs $DISKTARGET $PARTTARGET
-			# Cambiar nombre en sistemas Windows.
-			if [ "$(ogGetOsType $DISKTARGET $PARTTARGET)" = "Windows" ]; then
-    				HOST=$(ogGetHostname)
-    				HOST=${HOST:-"UNKNOWN"}
-    				echo "[90] Cambiar nombre Windows a \"$HOST\"."
-    				ogSetWindowsName $DISKTARGET $PARTTARGET "$HOST"
-			fi		
+ 				esac						
+			echo "[90] llamando a configureOS $DISKTARGET $PARTTARGET"
+			configureOS $DISKTARGET $PARTTARGET			
 		else
 		    # Si el tamaño de los datos recibidos es más grande que la particion destino
 			ogRaiseError $OG_ERR_IMGSIZEPARTITION "ERROR tamanio particion= $SIZEPARTTARGET  menor que la imagen= $SIZEIMAGE"; exit $?
