ogGetSizeParameter: devuelve el tamaño del sf, el de la imagen y si cabe en el repositorio elegido - se elimina codigo repetido en script
git-svn-id: https://opengnsys.es/svn/branches/version1.0@4420 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createImage b/client/shared/scripts/createImage
--- a/client/shared/scripts/createImage
+++ b/client/shared/scripts/createImage
@@ -91,25 +91,15 @@ if [ -f "$IMGFILE" ]; then
     mv "$IMGFILE.sum" "$IMGFILE.sum.ant" 2>/dev/null
 fi
 
-#Comprobar espacio que requerira la imagen para ser almacenada
 echo " " > $OGLOGCOMMAND
-if ogMount $1 $2 &>/dev/null
-then
-    SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
-    #Aplicar factor de compresion
-    FACTORGZIP=55/100
-    FACTORLZOP=65/100
-    let SIZEREQUIRED=$SIZEDATA*$FACTORLZOP
-    #Comprobar espacio libre en el contenedor.
-    [ "${3^^}" == "CACHE" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
-    [ "${3^^}" == "REPO" ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-else
-    ogRaiseError $OG_ERR_PARTITION "$1 $2"
-    exit $?
-fi
+# Borramos ficheros de paginacion y configuracion
+ogCleanOs $1 $2
 
-ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE"
-[ "$SIZEREQUIRED" -gt "$SIZEFREE" ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
+#Comprobar espacio que requerira la imagen para ser almacenada
+read SIZEDATA SIZEREQUIRED ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$3" ; echo $?)
+
+ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE $SIZEREQUIRED"
+[ "$ISENOUGHSPACE" == "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
 
 # Ejecuta script personalizado de preconfiguración del sistema operativo modelo. 
 if which createImageCustomPre &>/dev/null; then
