#565 Internacionalizacion script imagenes sincronizadas
git-svn-id: https://opengnsys.es/svn/branches/version1.0@3731 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createBaseImage b/client/shared/scripts/createBaseImage
--- a/client/shared/scripts/createBaseImage
+++ b/client/shared/scripts/createBaseImage
@@ -24,6 +24,7 @@
 #*/ ##
 
 trap "ogUnlockImage $3 \"/$4.$IMGEXT\"; ogUnlock $1 $2;  hose $REPOIP 2009 --out sh -c 	\"echo -ne UMOUNT_IMAGE $4 $IMGEXT\" ; umount \"$DIRMOUNT\"; exit 1" 1 2 3 6 9 14 15
+#ogUnmountImage $3 "$4" $IMGEXT
 
 
 TIME1=$SECONDS
@@ -43,8 +44,10 @@ fi
 IMGEXT="img"
 REPOIP=$(ogGetRepoIp)
 
-echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a  $OGLOGFILE
+# Limpiamos fichero de log
+echo  -n ""> $OGLOGSESSION
 
+echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION  $OGLOGFILE
 
 # Comprobamos si la imagen o la particion estan bloqueada:
 ogIsImageLocked "$3" "$4.$IMGEXT" && echo  "$MSG_ERR_LOCKED $3 $4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE && exit $(ogRaiseError $OG_ERR_LOCKED "$3 $4.$IMGEXT" ; echo $?)
@@ -52,7 +55,7 @@ ogIsLocked "$1" "$2" &&  echo  "$MSG_ERR_LOCKED $1 $2"  | tee -a $OGLOGSESSION $
 
 # Si el repositorio es CACHE comprobamos que exista
 if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
-	! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE " | tee -a $OGLOGSESSION $OGLOGFIL | tee -a $OGLOGSESSION $OGLOGFILEE ; echo $?)
+	! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE " | tee -a $OGLOGSESSION $OGLOGFILE ; echo $?)
 fi
 
 echo " " > $OGLOGCOMMAND
@@ -81,24 +84,16 @@ else
  	ogRaiseError $OG_ERR_PARTITION "$1 $2"
     	exit $?
 fi
-echo "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[16]$MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
 [ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
 
 IMGDIR=$(ogGetParentPath "$3" "/$4")
 IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
 
-ogLockImage "$3"  "/$4.$IMGEXT"
-
-# Si existe el fichero de la imagen se hace copia de seguridad y se redimensiona, si  no existe se crea.
-ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
-
-
-DIRMOUNT="mount/$4"
-
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
 SIZEFS=$(ogGetFsSize  $1 $2)
-FSTYPE=$(ogGetFsType $1 $2)   
+#FSTYPE=$(ogGetFsType $1 $2)   
 echo "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGLOGFILE
 ogUnmount $1 $2
 ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2" && echo $?)
@@ -106,38 +101,46 @@ ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_PARTITION "ogChe
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
-echo "[40] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
+
+
+ogLockImage "$3"  "/$4.$IMGEXT"
+
+# Si existe el fichero de la imagen se hace copia de seguridad y se redimensiona, si  no existe se crea.
+echo "[30] $MSG_HELP_ogCreateFileImage." | tee -a $OGLOGSESSION $OGLOGFILE
+ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
 
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
+echo "[50] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_HELP_ogCreateInfoImage"  | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateInfoImage $1 $2 $IMGEXT
 
 TIMEAUX3=$[SECONDS-TIME2]
-echo "      Fin listado  contenido y lista de control de acceso: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 
 # Esperamos que el servidor termine de crear y montar la imagen
 #ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED || exit $(ogRaiseError "Error al montar la imagen $1 $2 $3: time_out $TIMEAUX seg."; echo $?)
-ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED
+ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED  || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out $TIMEAUX seg."; echo $?)
+
 
 # Sincronizamos los datos de la particion con la imagen.
-echo "[70] Sincronizamos los datos de la particion con la imagen."
+echo "      $MSG_HELP_ogSyncCreate."  | tee -a $OGLOGSESSION $OGLOGFILE
 ogSyncCreate $1 $2 $3 "$4"  $IMGEXT
 
-echo "      Desmontamos la imagen en $3" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_HELP_ogUnmountImage: $3 /$4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE
 ogUnmountImage $3 "$4" $IMGEXT
 
 ogUnlockImage "$3" "/$4.$IMGEXT"
 ogUnlock $1 $2
-
 TIMEAUX5=$[SECONDS-TIMEAUX3]
-echo "      Fin copia de ficheros a la imagen: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+
 # Comprobamos que la imagen esta bien detectacdo que es un sistema de ficheros.
 file $IMGFILE|grep "BTRFS Filesystem" 2>&1 >/dev/null
 [ $? == 0 ] || exit $(ogRaiseError $OG_ERR_IMAGE "$3 $4" ; echo $?)
 
 TIMEAUX7=$[SECONDS-TIME2]
 echo "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
 
 
 #resumen de la operacion
@@ -147,5 +150,5 @@ IMGSIZE=$(ls -s $IMGFILE | cut -f1 -d" ")
 
 TIME=$[SECONDS-TIME1]
 echo "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      FileSystem $PART with $NEWSIZEFS KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync " | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      Image-file $4 metada: $IMGOS " | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      FileSystem $PART with $SIZEDATA KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync " | tee -a $OGLOGSESSION $OGLOGFILE
+#echo "      Image-file $4 metada: $IMGOS " | tee -a $OGLOGSESSION $OGLOGFILE
diff --git a/client/shared/scripts/createDiffImage b/client/shared/scripts/createDiffImage
--- a/client/shared/scripts/createDiffImage
+++ b/client/shared/scripts/createDiffImage
@@ -32,7 +32,6 @@ CREATESPEED=${CREATESPEED:-"100000*4"}
 
 TIME1=$SECONDS
 
-
 PROG="$(basename $0)"
 if [ $# -lt 5 ]; then
     ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE base_image diff_image"
@@ -53,7 +52,6 @@ ogIsLocked "$1" "$2" && exit $(ogRaiseError $OG_ERR_LOCKED  "$1 $2"; echo $?)
 IMGFILE=$(ogGetPath "$3" "$4.$IMGEXT") || exit $(ogRaiseError $OG_ERR_NOTFOUND "$3 $4.$IMGEXT"; echo $?)
 
 # Comprobar que es sincronizable
-#echo "      Comprobamos que la imagen es sincronizable" 
 file $IMGFILE | grep " BTRFS Filesystem" >/dev/null 
 [ $? == 0 ] ||  exit  $(ogRaiseError $OG_ERR_IMAGE "$3 $4"; echo $?) 
 # Comprobar que no está bloqueada
@@ -92,34 +90,37 @@ ogUnmount $1 $2
 ogCheckFs $1 $2 >$OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2" && echo $?)
 
 TIMEAUX1=$[SECONDS-TIME1]
-echo "      Fin chequeo sistema de ficheros : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
-echo "[40] Genera imagen diferencial de la particion $1 $2 respecto a la imagen $3 $4" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[40] $MSG_HELP_restoreDiffImage: $1 $2 $3 $4" | tee -a $OGLOGSESSION $OGLOGFILE
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
 FSTYPE=$(ogGetFsType $1 $2)
 
 IMGDIRAUX=$(ogGetMountDir "$4" $IMGEXT)
 
 # Montamos imagen completa (con la que vamos a comparar)
-ogMountImage $3 "$4" $IMGEXT
+ogMountImage $3 "$4" $IMGEXT >/dev/null
 
 # Comprobar que la imagen completa se ha montado 
-ogWaitMountImage $3 "$4" $IMGEXT || exit $(ogRaiseError "Error al montar la imagen $1 $2 $3: time_out $TIMEAUX seg."; echo $?)
-echo "[50] Creamos información de las diferencias"
-echo ogCreateInfoImage $1 $2 $3 "$4" "$DIFFEXT"
+#ogWaitMountImage $3 "$4" $IMGEXT || exit $(ogRaiseError "$MSG_ERR_DONTMOUNT_IMAGE $3 $4 $IMGEXT: time_out $TIMEAUX seg."; echo $?)
+ogWaitMountImage $3 "$4" $IMGEXT || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out $TIMEAUX seg."; echo $?)
+
+# Creamos la informacion de la imagen.
+echo "[50] $MSG_HELP_ogCreateInfoImage " | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateInfoImage $1 $2 $3 "$4" "$DIFFEXT"
 TIMEAUX3=$[SECONDS-TIME2]
-echo "      Fin listado contenido y lista de control de acceso: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 #Calculamos el tamaño de la imagen:
-ogMount $1 $2
+ogMount $1 $2 >/dev/null
 ogLock $1 $2
-cd $ORIG
 
-SIZEREQUIRED=$(cat /tmp/ogimg.info | tr '\n' '\0'| du -c --files0-from=- 2>/dev/null|tail -n1 |cut -f1)
-let SIZEREQUIRED=SIZEREQUIRED*115/100
+echo -n "     $MSG_SCRIPTS_CREATE_SIZE" | tee -a $OGLOGSESSION $OGLOGFILE
+cd $ORIG
+SIZEDATA=$(cat /tmp/ogimg.info | tr '\n' '\0'| du -c --files0-from=- 2>/dev/null|tail -n1 |cut -f1)
+let SIZEREQUIRED=SIZEDATA*115/100
 # El tamaño mínimo del sistema de ficheros btrfs es 250M, ponemos 300
 [ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
 TIMEAUX4=$[SECONDS-TIMEAUX3]
@@ -127,29 +128,34 @@ TIMEAUX4=$[SECONDS-TIMEAUX3]
 # TODO: Comprueba que quepa en el repositorio
 [ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`) && ogMountCache >/dev/null
 [ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-echo "     $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
+echo  " $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
+
 [ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
-echo "      Fin calculo tamaño imagen $SIZEREQUIRED: $[TIMEAUX4/60]m $[TIMEAUX4%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL $SIZEREQUIRED: $[TIMEAUX4/60]m $[TIMEAUX4%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+
+# Configuro la informacion del tamaño de los datos en /tmp/ogimg.info
+sed -i s/SIZEDATA/"$SIZEDATA"/g /tmp/ogimg.info
 
 # Creamos o redimensionamos la imagen
-echo "[60] Creamos el archivo de la imagen."  | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[60] $MSG_HELP_ogCreateFileImage."  | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateFileImage $3 "$5" $DIFFEXT $SIZEREQUIRED
 
 # Esperamos que se monte la imagen despues de crarla en el servidor
-ogWaitMountImage "$3" "$5" "$DIFFEXT" $SIZEREQUIRED  ||exit $(ogRaiseError "Error al montar la imagen $1 $2 $3: time_out $TIMEAUX seg."; echo $?)
+ogWaitMountImage "$3" "$5" "$DIFFEXT" $SIZEREQUIRED  ||exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $3: time_out $TIMEAUX seg."; echo $?)
 
 TIMEAUX6=$[SECONDS-TIMEAUX5]
-echo  -e "      Fin preparacion imagen: $[TIMEAUX6/60]m $[TIMEAUX6%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo  -e "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX6/60]m $[TIMEAUX6%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
-echo "[80] Sincronizo los datos de la imagen."
+echo  "[80] $MSG_HELP_ogSyncCreate" | tee -a $OGLOGSESSION $OGLOGFILE
 # Copio los datos a la imagen diferecial :
 ogSyncCreate $1 $2 $3 "$5" $DIFFEXT
 
 ogUnmountImage $3 "$5" $DIFFEXT
 ogUnmountImage $3 "$4" $IMGEXT
 
+
 TIMEAUX7=$[SECONDS-TIMEAUX6]
-echo "      Fin copia dato a diferencial: $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 
 TIMEAUX8=$[SECONDS-TIME2]
@@ -160,7 +166,6 @@ ogUnlockImage "$3" "/$5.$DIFFEXT"
 ogUnlock $1 $2
 
 # Comprobamos que la imagen esta bien
-echo file "$DIFFFILE" |grep "BTRFS Filesystem"
 file "$DIFFFILE" |grep "BTRFS Filesystem" >/dev/null
 [ $? == 0 ] ||  exit  $(ogRaiseError $OG_ERR_IMAGE "$3 $4"; echo $?)
 
@@ -170,4 +175,4 @@ IMGSIZE=$(ls -s ${DIFFFILE[CACHE]}| cut -f1 -d" ")
 
 TIME=$[SECONDS-TIME1]
 echo "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      FileSystem $PART with $NEWSIZEFS KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync " | tee -a $OGLOGSESSION $OGLOGFILE
+echo "      FileSystem $PART with $SIZEDATA KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync " | tee -a $OGLOGSESSION $OGLOGFILE
diff --git a/client/shared/scripts/restoreBaseImage b/client/shared/scripts/restoreBaseImage
--- a/client/shared/scripts/restoreBaseImage
+++ b/client/shared/scripts/restoreBaseImage
@@ -46,6 +46,21 @@ ogIsLocked "$3" "$4" && exit $(ogRaiseError $OG_ERR_LOCKED  "$3 $4"; echo $?)
 
 # Procesar parámetros de entrada
 REPOFILE=$(ogGetPath "REPO" "$2.$IMGEXT") || exit $(ogRaiseError $OG_ERR_NOTFOUND "REPO, $2.$IMGEXT"; echo $?)
+# Comprobamos si el sistema de ficheros se puede montar
+ogMount "$3" "$4" &>/dev/null
+if [  $? -ne 0 ] ; then
+	# TODO ogGetImageInfo
+	DIRMOUNT="/tmp/mount$$"
+	mkdir $DIRMOUNT
+	mount -o compress=lzo $REPOFILE $DIRMOUNT
+	FSTYPE=$(head -1 $DIRMOUNT/ogimg.info |cut -d: -f3)	
+	umount $DIRMOUNT
+	echo "      $MSG_FORMAT: $3 $4 $FSTYPE" | tee -a $OGLOGFILE
+	ogFormat "$3" "$4" "$FSTYPE" || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
+	ogMount "$3" "$4"  || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
+fi
+
+
 
 # Comprobar que es sincronizable (con REPO)
 # TODO: crear mensaje de error
@@ -56,65 +71,56 @@ PROTO=${5:-"UNICAST"}
 if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
    # Las imagenes sincronizables aunque sean iguales no tienen el mismo sum. 
    # Sincronizamos si existe el fichero y si no usamos updateCache.
-   echo "[10] Realizando un updateCache REPO $2.img $PROTO $6" | tee -a $OGLOGFILE
+   echo "[10] $MSG_SCRIPTS_TASK_START updateCache REPO $2.img $PROTO $6" | tee -a $OGLOGFILE
    echo "      updateCache REPO" "/$2.img" "$PROTO" "$6"   | tee -a $OGLOGFILE
    updateCache REPO "/$2.img" "$PROTO" "$6"     &>> $OGLOGCOMMAND
    RETVAL=$?
    if [ "$RETVAL" != "0" ] 
         then 
-        echo "[49] Fin del updateCache REPO $2.img $5 $6 con error $RETVAL" | tee -a $OGLOGFILE 
+        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.img $5 $6 con error $RETVAL" | tee -a $OGLOGFILE 
         # RC=15 No hay cache 
         # RC=16 no hay espacio sufiente 
         exit $RETVAL 
    fi 
+   TIMEAUX1=$[SECONDS-TIME]
+   echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGFILE
+
 fi 
+
+
 
 TIME2=$SECONDS
 
-PART=$(ogDiskToDev "$3" "$4") || exit $?
 
 # Restaurar la imagen.
-echo "[40] Restaurar imagen en $PART"  | tee -a $OGLOGFILE
-DEST=$(ogMount "$3" "$4") 
-# Formateamos si es necesario
-if [  $? -ne 0 ] ; then
-	# TODO ogGetImageInfo
-	DIRMOUNT="/tmp/mount$$"
-	mkdir $DIRMOUNT
-	mount -o compress=lzo $REPOFILE $DIRMOUNT
-	FSTYPE=$(head -1 $DIRMOUNT/ogimg.info |cut -d: -f3)	
-	umount $DIRMOUNT
-	echo "      Es necesario formatear la partición en $FSTYPE" | tee -a $OGLOGFILE
-	ogFormat "$3" "$4" "$FSTYPE"
-	ogMount "$3" "$4"  || exit $?
-fi
+echo "[40] $MSG_HELP_ogRestoreImage: $1 $2 $3 $4"  | tee -a $OGLOGFILE
 
 ogLock $3 $4
 
 # Montamos la imagen basica.
-ogMountImage "$1" "$2" "img" 
+ogMountImage "$1" "$2" "img"  >/dev/null
 #  Comprobar que la imagen completa se ha montado.
 ogWaitMountImage "$1" "$2" "img" 
 # Sincronizamos la partición con la imagen.
-echo  "[60] Sincronizando la partición con la imagen"  |tee -a $OGLOGFILE
+echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 img $3 $4"  |tee -a $OGLOGFILE
 ogSyncRestore "$1" "$2" "img" $3 $4 
 
 TIMEAUX2=$[SECONDS-TIME2]
-echo "      Fin Restauracion: tiempo parcial : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a $OGLOGFILE
 
 # Desmontamos imagen basica.
 ogUnmountImage "$1" "$2" "img"
 
 # Restableciendo acl
 ogUnlock $3 $4
-echo "[70] Restableciendo lista de control de acceso." |tee -a $OGLOGFILE
+echo "[70] $MSG_HELP_ogRestoreInfoImage" |tee -a $OGLOGFILE
 ogRestoreInfoImage $3 $4  &>>$OGLOGCOMMAND
 
 
 # Llamar al script de post-configuración del sistema operativo.
-echo "[90] Post-configuracion de arranque del sistema." |tee -a $OGLOGFILE
+echo "[90] $MSG_HELP_configureOs" |tee -a $OGLOGFILE
 configureOs $3 $4  &>>$OGLOGCOMMAND
 
 TIME=$[SECONDS-TIME1]
-echo "[100] Duracion de la operacion $[TIME/60]m $[TIME%60]s" |tee -a $OGLOGFILE
+echo "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s" |tee -a $OGLOGFILE
 
diff --git a/client/shared/scripts/restoreDiffImage b/client/shared/scripts/restoreDiffImage
--- a/client/shared/scripts/restoreDiffImage
+++ b/client/shared/scripts/restoreDiffImage
@@ -53,56 +53,56 @@ file $REPODIFFFILE | grep " BTRFS Filesystem" >/dev/null
 PROTO=${5:-"UNICAST"}
 
 if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
-   echo "[10] Realizando la actualizacion de la cache." | tee -a  $OGLOGFILE
+   echo "[10] $MSG_HELP_updateCache." | tee -a  $OGLOGFILE
    echo "     updateCache REPO" "/$2.$DIFFEXT" "$PROTO" "$6"  | tee -a  $OGLOGFILE   
    updateCache REPO "/$2.$DIFFEXT" "$PROTO" "$6"  &>> $OGLOGCOMMAND
    RETVAL=$?
    if [ "$RETVAL" != "0" ] 
         then 
-        echo "[49] Fin del updateCache REPO $2.$DIFFEXT $5 $6 con error $RETVAL" | tee -a  $OGLOGFILE 
+        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.$DIFFEXT $5 $6 con error $RETVAL" | tee -a  $OGLOGFILE 
         # RC=15 No hay cache 
         # RC=16 no hay espacio sufiente 
         exit $RETVAL 
    fi 
 
    TIMEAUX1=$[SECONDS-TIME]
-   echo "     Fin actualizacion cache $1 $2 $3 $4 tiempo parcial : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a  $OGLOGFILE
+   echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGFILE
+
 fi 
 TIME2=$SECONDS
 
 PART=$(ogDiskToDev "$3" "$4" 2>/dev/null )  || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2"; echo $?)
 
 # Restaurar la imagen.
-echo "[40] Restaurar imagen en $PART"
-
+echo "[40] $MSG_RESTORE $PART"
 
 # Montamos la diferencial
-ogMountImage "$1" "$2" "diff"
+ogMountImage "$1" "$2" "diff" &>/dev/null
 #  Comprobar que la imagen diferencial se ha montado 
-ogWaitMountImage "$1" "$2" "diff"
+ogWaitMountImage "$1" "$2" "diff" || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 diff: time_out $TIMEAUX seg."; echo $?)
 
 ogMount $3 $4 >/dev/null
 ogLock $3 $4
 # Sincronizamos la partición con la imagen.
+echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 diff $3 $4"  |tee -a $OGLOGFILE
 ogSyncRestore "$1" "$2" "diff" $3 $4
 
 # Desmontamos la imagen
 ogUnmountImage "$1" "$2" "diff"
-
 ogUnlock $3 $4
-# creando enlaces y restableciendo ACL (en windows)
-echo "     Diferencial: creando enlaces y borrando"  | tee -a  $OGLOGFILE
-ogRestoreInfoImage  "$3" "$4" &>$OGLOGCOMMAND
 
 TIMEAUX2=$[SECONDS-TIME2]
-echo "     Fin Restauracion $1 $2 $3 $4 tiempo parcial : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a  $OGLOGFILE
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a  $OGLOGFILE
 
+# creando enlaces y restableciendo ACL (en windows)
+echo "[70] $MSG_HELP_ogRestoreInfoImage" |tee -a $OGLOGFILE
+ogRestoreInfoImage  "$3" "$4" &>$OGLOGCOMMAND
 
 # Llamar al script de post-configuración del sistema operativo.
-echo "[90] Post-configuracion de arranque del sistema."
+echo "[90] $MSG_HELP_configureOs."
 configureOs $3 $4
 
 
 TIME=$[SECONDS-TIME1]
-echo "[100] Duracion de la operacion $[TIME/60]m $[TIME%60]s"
+echo "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s" |tee -a $OGLOGFILE
 
