#673: Integrar código de la versión 1.0.6 en rama principal.
git-svn-id: https://opengnsys.es/svn/trunk@4641 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createBaseImage b/client/shared/scripts/createBaseImage
--- a/client/shared/scripts/createBaseImage
+++ b/client/shared/scripts/createBaseImage
@@ -40,19 +40,6 @@ TIME1=$SECONDS
 #Carga el configurador del engine desde el fichero engine.cfg
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
-# Factor de calculo de Time out al crear imagen: valor por defecto en engine.cfg 
-CREATESPEED=${CREATESPEED:-"100000*4"}
-
-# Sistema de fichero de la imagen según kernel, menor que 3.7 EXT4. comparamos revision 
-KERNELVERSION=$(uname -r| awk '{printf("%d",$1);sub(/[0-9]*\./,"",$1);printf(".%02d",$1)}')
-[ $KERNELVERSION \< 3.07 ] &&  IMGFS="EXT4" || IMGFS="BTRFS"
-
-# % de compresion para estimacion tamaño imagen IMGFS="EXT4"
-ZSYNC=${ZSYNC:-"120"}
-
-# Si IMGFS="BTRFS" la compresion es mayor.
-[ $IMGFS == "BTRFS" ] && let ZSYNC=$ZSYNC-30
-
 PROG="$(basename $0)"
 # Si se solicita, mostrar ayuda.
 if [ "$*" == "help" ]; then
@@ -66,12 +53,12 @@ fi
 
 # Limpiamos fichero de log
 echo  " " > $OGLOGCOMMAND
-[ "$(ogGetCaller)" == "RestaurarImagenBasica" ] || echo  -n ""> $OGLOGSESSION
+[ "$(ogGetCaller)" == "CrearImagenBasica" ] || echo  -n ""> $OGLOGSESSION
 
 ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
 # Valores por defecto en etc/engine.cfg
-IMGEXT="img"
+IMGEXT=${IMGEXT:-"img"}
 REPOIP=$(ogGetRepoIp)
 
 
@@ -97,29 +84,14 @@ ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError session $OG_ERR_PARTITIO
 ORIG=$(ogMount $1 $2) || exit $(ogRaiseError session $OG_ERR_PARTITION "$1 $2" ; echo $?)
 
 # Borramos ficheros de paginacion y configuracion
-case "$(ogGetFsType $1 $2)" in 
-    EXT[234])
-	ogCleanLinuxDevices $1 $2
-	rm -rf $ORIG/tmp/*
-	;;
-    NTFS)
-	[ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys
-	[ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys	
-	[ $(ogGetPath $1 $2 swapfile.sys) ] && ogDeleteFile $1 $2 swapfile.sys 
-	;;
-esac
+ogCleanOs $1 $2
 
 #Comprobar espacio que requerira la imagen para ser almacenada
-SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
-#Aplicar factor de compresion
-let SIZEREQUIRED=$SIZEDATA*$ZSYNC/100
-# El tamaño mínimo del sistema de ficheros btrfs es 250M, ponemos 300
-[ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
-#Comprobar espacio libre en el contenedor.
-[ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
-[ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-ogEcho log session "      $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE"
-[ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
+read SIZEDATA SIZEREQUIRED ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$3" SYNC)
+
+ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED"
+[ "$ISENOUGHSPACE" ==  "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
+
 IMGDIR="$(ogGetParentPath "$3" "/$4")"
 IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
 
@@ -128,9 +100,11 @@ echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
 
 ogEcho log session "[40] $MSG_HELP_ogCreateImage $1 $2 $3 $4 "
+
 # Si existe el fichero de la imagen se hace copia de seguridad y se redimensiona, si  no existe se crea.
+# Bloqueo la imagen. Si esta en modo lectura dara error y nos salimos
 ogEcho log session "[50] $MSG_HELP_ogCreateFileImage."
-ogLockImage "$3"  "/$4.$IMGEXT"
+ogLockImage "$3"  "/$4.$IMGEXT" || exit $? 
 ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
 
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
diff --git a/client/shared/scripts/createDiffImage b/client/shared/scripts/createDiffImage
--- a/client/shared/scripts/createDiffImage
+++ b/client/shared/scripts/createDiffImage
@@ -43,16 +43,6 @@ function onexit() {
 #Carga el configurador del engine desde el fichero engine.cfg
 [ -z $OGENGINECONFIGURATE ] &&  source /opt/opengnsys/etc/engine.cfg
 
-# Factor de calculo de Time out al crear imagen: valor por defecto en engine.cfg 
-CREATESPEED=${CREATESPEED:-"100000*4"}
-# Sistema de fichero de la imagen según kernel, menor que 3.7 EXT4. comparamos revision 
-KERNELVERSION=$(uname -r| awk '{printf("%d",$1);sub(/[0-9]*\./,"",$1);printf(".%02d",$1)}')
-[ $KERNELVERSION \< 3.07 ] &&  IMGFS="EXT4" || IMGFS="BTRFS"
-# % de compresion para estimacion tamaño imagen IMGFS="EXT4"
-ZSYNC=${ZSYNC:-"120"}
-# Si IMGFS="BTRFS" la compresion es mayor.
-[ $IMGFS == "BTRFS" ] && let ZSYNC=$ZSYNC-30
-
 TIME1=$SECONDS
 
 PROG="$(basename $0)"
@@ -105,8 +95,9 @@ ORIG=$(ogMount $1 $2) ||   exit $(ogRaiseError session $OG_ERR_PARTITION "$1 $2"
 DIFFDIR="$(ogGetParentPath "$3" "/$5")"
 DIFFFILE="$DIFFDIR/$5.$DIFFEXT"
 
-ogLockImage "$3"  "/$4.$IMGEXT"
-ogLockImage "$3"  "/$5.$DIFFEXT"
+# Bloqueo las imagenes -> Si no hay acceso de escritura dara error y nos saldremos.
+ogLockImage "$3"  "/$4.$IMGEXT" || exit $?
+ogLockImage "$3"  "/$5.$DIFFEXT" || exit $? 
 
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
@@ -116,18 +107,7 @@ ogUnmount $1 $2
 ogCheckFs $1 $2 >$OGLOGCOMMAND || exit $(ogRaiseError session $OG_ERR_PARTITION "ogCheckFs $1 $2" ; echo $?)
 
 # Borramos ficheros de paginacion y configuracion
-FSTYPE=$(ogGetFsType $1 $2)
-case "$FSTYPE" in
-    EXT[234])
-        ogCleanLinuxDevices $1 $2
-	rm -rf $ORIG/tmp/*
-        ;;
-    NTFS)
-	[ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys
-	[ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys
-	[ $(ogGetPath $1 $2 swapfile.sys) ] && ogDeleteFile $1 $2 swapfile.sys
-        ;;
-esac
+ogCleanOs $1 $2
 
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
@@ -142,36 +122,23 @@ ogMountImage $3 "$4" $IMGEXT >/dev/null
 ogWaitSyncImage $3 "$4" $IMGEXT "mounted" || exit $(ogRaiseError session $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out."; echo $?)
 
 # Creamos la informacion de la imagen.
-ogEcho log session "[50] $MSG_HELP_ogCreateInfoImage "
+ogEcho log session "[45] $MSG_HELP_ogCreateInfoImage "
 ogCreateInfoImage $1 $2 $3 "$4" "${DIFFTYPE}"
 [ $? -eq $OG_ERR_NOTDIFFERENT ] &&  exit $(ogRaiseError session $OG_ERR_NOTDIFFERENT; echo $?)
+
+#Comprobar espacio que requerira la imagen para ser almacenada
+read SIZEDATA SIZEREQUIRED ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$3" DIFF)
+
+ogEcho log session "[50] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED"
+[ "$ISENOUGHSPACE" == "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
 
 #Calculamos el tamaño de la imagen:
 ogMount $1 $2 >/dev/null
 ogLock $1 $2
-ogEcho log session  "     $MSG_SCRIPTS_CREATE_SIZE"
-cd $ORIG
-SIZEDATA=$(grep -v "\/$" /tmp/ogimg.info | tr '\n' '\0'| du -x -c --files0-from=- 2>/dev/null|tail -n1 |cut -f1)
-let SIZEREQUIRED=$SIZEDATA*$ZSYNC/100
-# Tamaño minimo fichero imagen 300000
-[ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
-
-# Comprueba que quepa en el repositorio
-[ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`) && ogMountCache >/dev/null
-[ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-ogEcho log session  "      $SIZEREQUIRED $SIZEFREE"
-[ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
 
 TIMEAUX3=$[SECONDS-TIME2]
 ogEcho log session "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s"
 
-# Del fichero de acl de la partición extraemos las acl de los ficheros de la diferencial
-if [ "$FSTYPE" == "NTFS" ]; then
-	ogEcho log session "[55] $MSG_HELP_ogAclFilter "
-	ogAclFilter
-	TIMEAUX4=$[SECONDS-TIMEAUX3]
-	ogEcho log session "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX4/60]m $[TIMEAUX4%60]s"
-fi
 TIMEAUX5=$[SECONDS-TIMEAUX3]
 
 # Configuro la informacion del tamaño de los datos en /tmp/ogimg.info
@@ -202,7 +169,6 @@ ogWaitSyncImage "$3" "$5" $DIFFTYPE "reduced" $SIZEREQUIRED || exit $(ogRaiseErr
 echo " " > $OGLOGCOMMAND
 # Comprobamos que la imagen esta bien
 ogEcho log session "[95] $MSG_HELP_ogCheckSyncImage"
-sleep 10
 ogCheckSyncImage $3 "$5" diff ||  exit $(ogRaiseError session $OG_ERR_IMAGE "$3 $5 diff"; echo $?)
 
 #resumen de la operacion
diff --git a/client/shared/scripts/createImage b/client/shared/scripts/createImage
--- a/client/shared/scripts/createImage
+++ b/client/shared/scripts/createImage
@@ -53,7 +53,7 @@ TIME1=$SECONDS
 # Valores por defecto en etc/engine.cfg
 #IMGPROG="partclone"
 #IMGCOMP="lzop"
-#IMGEXT="img"
+IMGEXT=${IMGEXT:-"img"}
 #IMGREDUCE="TRUE"
 
 # Clear temporary file used as log track by httpdlog
@@ -63,7 +63,7 @@ echo " " > $OGLOGSESSION; echo " " > $OGLOGCOMMAND; echo " " > ${OGLOGCOMMAND}.t
 ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
 # Si el repositorio es CACHE comprobamos que exista
-if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
+if [ "${3^^}" == "CACHE" ]; then 
     ! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE "; echo $?)
 fi
 
@@ -89,32 +89,18 @@ if [ -f "$IMGFILE" ]; then
     mv "$IMGFILE" "$IMGFILE.ant"
     mv "$IMGFILE.torrent" "$IMGFILE.torrent.ant" 2>/dev/null
     mv "$IMGFILE.sum" "$IMGFILE.sum.ant" 2>/dev/null
+    mv "$IMGFILE.full.sum" "$IMGFILE.full.sum.ant" 2>/dev/null
 fi
+
+echo " " > $OGLOGCOMMAND
+# Borramos ficheros de paginacion y configuracion
+ogCleanOs $1 $2
 
 #Comprobar espacio que requerira la imagen para ser almacenada
-echo " " > $OGLOGCOMMAND
-if ogMount $1 $2 &>/dev/null
-then
-    SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
-    #Aplicar factor de compresion
-    FACTORGZIP=55/100
-    FACTORLZOP=65/100
-    let SIZEREQUIRED=$SIZEDATA*$FACTORLZOP
-    #Comprobar espacio libre en el contenedor.
-    [ "$3" == "CACHE" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
-    [ "$3" == "REPO" ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-else
-    ogRaiseError $OG_ERR_PARTITION "$1 $2"
-    exit $?
-fi
+read SIZEDATA SIZEREQUIRED ISENOUGHSPACE <<< $(ogGetSizeParameters $1 $2 "$3")
 
-ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE"
-[ "$SIZEREQUIRED" -gt "$SIZEFREE" ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
-
-# Ejecuta script personalizado de preconfiguración del sistema operativo modelo. 
-if which createImageCustomPre &>/dev/null; then
-    createImageCustomPre "$1" "$2" "$3" "$4"
-fi
+ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE $SIZEREQUIRED"
+[ "$ISENOUGHSPACE" == "TRUE" ] || exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
 
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
@@ -154,16 +140,11 @@ ogEcho log session "      $MSG_HELP_ogExtendFs  $NEWSIZEFS ->  $SIZEFS = $SIZEFS
 #TODO que hacer si error al extender sistemade archivos
 
 #resumen de la operacion
-IMGSIZE=$(ls -s `ogGetPath $3 /$4.img`| cut -f1 -d" ")
-IMGOS=$(ogGetImageInfo `ogGetPath $3 /$4.img`)
+IMGSIZE=$(ls -s `ogGetPath $3 /$4.$IMGEXT`| cut -f1 -d" ")
+IMGOS=$(ogGetImageInfo `ogGetPath $3 /$4.$IMGEXT`)
 
 TIME=$[SECONDS-TIME1]
 ogEcho log session "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s"
 ogEcho log session "      FileSystem $PART with $NEWSIZEFS KB data created onto file-image as $4 and used $IMGSIZE KB across DFS $ogprotocol"
 ogEcho log session "      Image-file $4 metada: $IMGOS"
-
-# Ejecuta scripts personalizado de postconfiguracion del sistema operativo modelo. 
-if which createImageCustomPost &>/dev/null; then
-    createImageCustomPost "$1" "$2" "$3" "$4"
-fi
 
diff --git a/client/shared/scripts/updateCache b/client/shared/scripts/updateCache
--- a/client/shared/scripts/updateCache
+++ b/client/shared/scripts/updateCache
@@ -25,6 +25,9 @@
 #@date   2011-05-10
 #@version 2.0.1 - Imagenes sincronizadas
 #@date    2013-02-20
+#@version 1.0.5 - uso de md5 full para las transferencias torrent, en la llamada => ogUpdateCacheIsNecesary 
+#@date    2014-07-09
+
 #*/ ##
 
 PROG="$(basename $0)"
@@ -72,8 +75,7 @@ else
 	# Si la imagen es monolitica y ha elegido protocolo = RSYNC salimos con error.
 	[ $PROTOCOLO == "RSYNC" ] && exit $(ogRaiseError session $OG_ERR_DONTSYNC_IMAGE "REPO $2"; echo $?)
 	IMGSYNC=FALSE
-	#TODO: ogUpdateCacheIsNecesary debe borrar la imagen que tenga igual nombre pero distinto sum-
-	ogUpdateCacheIsNecesary $1 $2
+	ogUpdateCacheIsNecesary "$1" "$2" "$PROTOCOLO"
 	RETVAL=$?
 fi
 # si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
@@ -112,7 +114,7 @@ else
 	SIZEREQUIRED=$FILESIZE
 fi
 
-#ERROR CACHESIZE 16
+#ERROR CACHESIZE 16 (tamanyo de la CACHE insuficiente)
 if [ "$SIZEREQUIRED" -ge "$CACHESIZE" ]  
 then
 	ogEcho log session "$MSG_WARNING: $MSG_ERR_CACHESIZE:  $2 = $SIZEREQUIRED > CACHE = $CACHESIZE"
@@ -120,14 +122,16 @@ then
 	exit $?
 fi
 
-ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_IFNOTCACHEDO"
-#ERROR CACHESIZE 16
+
+#ERROR CACHESIZE 16 (Espacio libre en CACHE insuficiente)
 if [ "$SIZEREQUIRED" -ge "$CACHESIZEFREE" ]  
 then
-	# ogEcho log session "[ ] No hay espacio sufiente en la CACHE, detectar que hacer con engine.cfg"
+    ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_IFNOTCACHEDO: ACTIONCACHEFULL=$ACTIONCACHEFULL"
 	case "$ACTIONCACHEFULL" in 
 	NONE)
-		NEXTOPERATION=UNICAST
+		ogEcho log session "$MSG_WARNING: $MSG_ERR_CACHESIZE:  $2 = $SIZEREQUIRED > FREE SPACE CACHE = $CACHESIZEFREE"
+		ogRaiseError session $OG_ERR_CACHESIZE "CACHE FULL, NO SPACE FREE"
+		exit $?
 	;;
 	FORMAT)
 	    ogEcho log session  "[51] $MSG_HELP_ogFormatCache "
@@ -150,7 +154,7 @@ then
 fi
 
 # Comprobamos que imagen cache igual a la del repo. Si sincronizada no podemos comprobar. 
-[ "$IMGSYNC" == "TRUE" ] || ogUpdateCacheIsNecesary $REPOSITORIO "$2"
+[ "$IMGSYNC" == "TRUE" ] || ogUpdateCacheIsNecesary $REPOSITORIO "$2" "$PROTOCOLO"
 RETVAL=$?
 # si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
 [ "$RETVAL" == "1" ] && exit 0
@@ -173,7 +177,7 @@ case "$PROTOCOLO" in
 		ogEcho log session "ogCopyFile $1 $2.torrent absolute $OGCAC/$OGIMG"
 		# tiempos 
 		timewait=$(expr $(printf '%d\n' 0x$(ogGetMacAddress | awk -F: '{print $5$6}')) \* 120 / 65535)                         
-		ogCopyFile $REPOSITORIO "$2.torrent" "$IMGDIR" 2>&1 | tee -a   $OGLOGCOMMAND
+		ogExecAndLog command ogCopyFile $REPOSITORIO "$2.torrent" "$IMGDIR"
 		#TODO: comprobar que el tracker definido en el fichero es correcto.
     		#TODO comprobar que el fichero torrent está en cache
 		# retardamos el inicio -aleatorio de 0 a 120 segundos- al tracker para gestionar mas de +-40 equipos 
@@ -181,11 +185,11 @@ case "$PROTOCOLO" in
 		ogEcho log session "   [ ] $MSG_SCRIPTS_TASK_SLEEP :  $P2PWAIT seconds ogTorrentStart CACHE $2.torrent $4"
 		sleep $P2PWAIT
 		ogEcho log session "   [  ] $MSG_SCRIPTS_TASK_START:  ogTorrentStart CACHE $2.torrent $4"
-		ogTorrentStart CACHE "$2.torrent" $4 2>&1 | tee -a   $OGLOGCOMMAND
+		ogExecAndLog command ogTorrentStart CACHE "$2.torrent" $4
 		RESUMEUPDATECACHE=$(grep -m 1 -B1 "Download" $OGLOGCOMMAND) 
 		RESUMEUPDATECACHEbf=$(grep -m 1 "Download" $OGLOGCOMMAND) 
 		if [ "$RESUMEUPDATECACHEbf" == "Download complete." ]; then
-			rm $IMGDIR$2".torrent.bf" 2>&1 | tee -a   $OGLOGCOMMAND
+			rm -f $IMGDIR$2".torrent.bf"
 		fi
 	;;
 	MULTICAST)
@@ -198,7 +202,7 @@ case "$PROTOCOLO" in
 		#FIN TODO
 		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
 		then 
-	   		ogMcastReceiverFile $PORT CACHE "$2" 2>&1  | tee -a   $OGLOGCOMMAND
+			ogExecAndLog command ogMcastReceiverFile $PORT CACHE "$2"
 
 		else
 		    # TODO ticket 379 Realizar la petición basada en identificador de operacion
@@ -208,7 +212,7 @@ case "$PROTOCOLO" in
 	   		sleep 10
 	   		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
 	   		then 
-	   			ogMcastReceiverFile $PORT CACHE "$2" 2>&1  | tee -a   $OGLOGCOMMAND
+	   			ogExecAndLog command ogMcastReceiverFile $PORT CACHE "$2"
 			else
 				ogEcho log session "$MSG_SCRIPTS_TASK_ERR : hose $REPOIP 2009 --out sh -c echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
 	   			exit $OG_ERR_UPDATECACHE
@@ -221,7 +225,7 @@ case "$PROTOCOLO" in
 	;;
 	UNICAST)
 		#ogEcho log session "unicast"
-		ogCopyFile $REPOSITORIO "$2" "$IMGDIR" 2>&1  | tee -a   $OGLOGCOMMAND
+		ogExecAndLog command ogCopyFile $REPOSITORIO "$2" "$IMGDIR"
 		sleep 5
 		RESUMEUPDATECACHE=$(grep -m 1  "100%" $OGLOGCOMMAND.tmp)
 	;;
@@ -262,7 +266,7 @@ case "$PROTOCOLO" in
 		ogMountImage CACHE  "${IMGNAME#\/}" $IMGTYPE || exit $?
 		ogMountImage REPO  "${IMGNAME#\/}" $IMGTYPE 
 		# Esperamos que se monte la imagen en el servidor
-		ogWaitMountImage  REPO  "$IMGNAME" $IMGTYPE || exit $?
+		ogWaitSyncImage  REPO  "$IMGNAME" $IMGTYPE "mounted" || exit $?
 		ogEcho log session "      rsync -aHAX$OPTRSYNC  $USERRSYNC@$REPOIP::ogimages/$DIRMOUNT/ $DIRLOCAL"
 		rsync -aHAX$OPTRSYNC  $PASSWORD "$USERRSYNC@$REPOIP::ogimages/$DIRMOUNT/" "$DIRLOCAL" 2>>$OGLOGCOMMAND  | egrep "^sent|^sending|^total|%" >>   $OGLOGCOMMAND
 		# RETVAL="1" -> OK  RETVAL="2" -> error  # valores igual que ogUpdateCacheIsNecesary
@@ -285,7 +289,7 @@ if [ "$IMGSYNC" == "TRUE" ]; then
 	# RETVAL="1" -> OK  RETVAL="2" -> error  # valores igual que ogUpdateCacheIsNecesary
 	[ $PROTOCOLO == "RSYNC" ] || RETVAL=1
 else
-	ogUpdateCacheIsNecesary $REPOSITORIO "$2"
+	ogUpdateCacheIsNecesary $REPOSITORIO "$2" "$PROTOCOLO"
 	RETVAL=$?
 fi
 if [ "$(ogGetCaller)" != "deployImage" ]; then
