Versión 1.0.5, #616: Integrar código de la versión 1.0.5 en rama principal.
git-svn-id: https://opengnsys.es/svn/trunk@4309 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createImage b/client/shared/scripts/createImage
--- a/client/shared/scripts/createImage
+++ b/client/shared/scripts/createImage
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 #/**
-#         createImage
+#@file    createImage
 #@brief   Scirpt de ejemplo para crear una imagen de un sistema de archivos.
-#@brief (puede usarse como base para el programa de creación de imágenes usado por OpenGnSys Admin).
+#@brief   (puede usarse como base para el programa de creación de imágenes usado por OpenGnSys Admin).
 #@param 1 disco 
 #@param 2 particion 
 #@param 3 REPO|CACHE
@@ -37,13 +37,6 @@
 # test 4.  crear una imagen en la Cache sin espacio sufiente. 
 # test 5.  intentar crear una imagen, en la que no se puede reducir el FS.
 
-TIME1=$SECONDS
-
-#Load engine configurator from engine.cfg file.
-#Carga el configurador del engine desde el fichero engine.cfg
-[ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
-
-
 
 PROG="$(basename $0)"
 if [ $# -ne 4 ]; then
@@ -51,121 +44,126 @@ if [ $# -ne 4 ]; then
     exit $?
 fi
 
+TIME1=$SECONDS
+
+#Load engine configurator from engine.cfg file.
+#Carga el configurador del engine desde el fichero engine.cfg
+[ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
+
 # Valores por defecto en etc/engine.cfg
 #IMGPROG="partclone"
 #IMGCOMP="lzop"
 #IMGEXT="img"
 #IMGREDUCE="TRUE"
 
-echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION $OGLOGFILE
+# Clear temporary file used as log track by httpdlog
+# Limpia los ficheros temporales usados como log de seguimiento para httpdlog
+echo " " > $OGLOGSESSION; echo " " > $OGLOGCOMMAND; echo " " > ${OGLOGCOMMAND}.tmp
 
+ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
 # Si el repositorio es CACHE comprobamos que exista
 if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
     ! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE "; echo $?)
 fi
 
-echo " " > $OGLOGCOMMAND
-
 # Obtener información de los parámetros de entrada.
 PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2"; echo $?)
-
-echo " " > $OGLOGCOMMAND
 
 #Comprobamos acceso de escritura.
 DIRTEMP=$(date +%Y%m%d-%H%M%S)
 ogMakeDir $3 /$4$DIRTEMP 2>/dev/null || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3"; echo $?) && ogDeleteTree $3 /$4$DIRTEMP 
 
-echo " " > $OGLOGCOMMAND
-
 IMGDIR=$(ogGetParentPath "$3" "/$4")
 # Si no existe, crear subdirectorio de la imagen.
 if [ $? != 0 ]; then
-    echo "[5] $MSG_HELP_ogMakeDir \"$3 $(dirname "$4")." | tee -a $OGLOGSESSION $OGLOGFILE
+    ogEcho log session "[5] $MSG_HELP_ogMakeDir \"$3 $(dirname "$4")."
     ogMakeDir "$3" $(dirname "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3 /$4"; echo $?)
     IMGDIR=$(ogGetParentPath "$3" "/$4") || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3 /$4"; echo $?)
 fi
 IMGFILE=$IMGDIR/$(basename "/$4").$IMGEXT
+
 # Renombrar el fichero de imagen si ya existe.
 if [ -f "$IMGFILE" ]; then
-	echo "[10] $MSG_SCRIPTS_FILE_RENAME \"$IMGFILE\" ->  \"$IMGFILE.ant\"." | tee -a $OGLOGSESSION $OGLOGFILE
-	mv "$IMGFILE" "$IMGFILE.ant"
+    ogEcho log session "[10] $MSG_SCRIPTS_FILE_RENAME \"$IMGFILE\" ->  \"$IMGFILE.ant\"."
+    mv "$IMGFILE" "$IMGFILE.ant"
     mv "$IMGFILE.torrent" "$IMGFILE.torrent.ant" 2>/dev/null
+    mv "$IMGFILE.sum" "$IMGFILE.sum.ant" 2>/dev/null
 fi
 
 #Comprobar espacio que requerira la imagen para ser almacenada
 echo " " > $OGLOGCOMMAND
 if ogMount $1 $2 &>/dev/null
 then
-	SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
-	#Aplicar factor de compresion
-	FACTORGZIP=55/100
-	FACTORLZOP=65/100
-	let SIZEREQUIRED=$SIZEDATA*$FACTORLZOP
-	#Comprobar espacio libre en el contenedor.
-	[ "$3" == "CACHE" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
-	[ "$3" == "REPO" ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
+    SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
+    #Aplicar factor de compresion
+    FACTORGZIP=55/100
+    FACTORLZOP=65/100
+    let SIZEREQUIRED=$SIZEDATA*$FACTORLZOP
+    #Comprobar espacio libre en el contenedor.
+    [ "$3" == "CACHE" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
+    [ "$3" == "REPO" ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
 else
- 	ogRaiseError $OG_ERR_PARTITION "$1 $2"
+    ogRaiseError $OG_ERR_PARTITION "$1 $2"
     exit $?
-fi	
-echo "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
+fi
+
+ogEcho log session "[16] $PROG: $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE"
 [ "$SIZEREQUIRED" -gt "$SIZEFREE" ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
 
-
-# TODO: que hacer si la cache no tiene espacio libre.
-
+# Ejecuta script personalizado de preconfiguración del sistema operativo modelo. 
+if which createImageCustomPre &>/dev/null; then
+    createImageCustomPre "$1" "$2" "$3" "$4"
+fi
 
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
 SIZEFS=$(ogGetFsSize  $1 $2)
-echo "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGLOGFILE
-ogUnmount $1 $2
+ogEcho log session "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB)"
+ogUnmount $1 $2 2>/dev/null
 ogCheckFs $1 $2 || exit $(ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2" && echo $?)
 
-
-
-if [ "$IMGREDUCE" == "TRUE"   ]
+# Evaluar variable de engine.cfg para reducir el sistema de archivos en la creacion
+if [ "$IMGREDUCE" == "TRUE" ]
 then 
-	echo "[30]: $MSG_HELP_ogReduceFs  "  | tee -a $OGLOGSESSION $OGLOGFILE
-	ogReduceFs $1 $2 || exit $(ogRaiseError $OG_ERR_REDUCEFS "$1 $2"; echo $?)
-	NEWSIZEFS=$(ogGetFsSize  $1 $2)
-	TIMEAUX=$[SECONDS-TIME1]
-	echo "      $MSG_SCRIPTS_TIME_PARTIAL ( $NEWSIZEFS KB ) : $[TIMEAUX/60]m $[TIMEAUX%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+    ogEcho log session "[30]: $MSG_HELP_ogReduceFs"
+    ogReduceFs $1 $2 &>> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_REDUCEFS "$1 $2"; echo $?)
+    NEWSIZEFS=$(ogGetFsSize  $1 $2)
+    TIMEAUX=$[SECONDS-TIME1]
+    ogEcho log session "      $MSG_SCRIPTS_TIME_PARTIAL ( $NEWSIZEFS KB ) : $[TIMEAUX/60]m $[TIMEAUX%60]s"
 fi
-
-
 
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
-echo "[40] $MSG_HELP_ogCreateImage : ogCreateImage $1 $2 $3 $4 $IMGPROG $IMGCOMP" | tee -a $OGLOGSESSION $OGLOGFILE
-ogCreateImage $1 "$2" $3 $4 "$IMGPROG" "$IMGCOMP" || exit $(ogRaiseError $OG_ERR_IMAGE "ogCreteImage"; echo $?)
-RESUMECREATEIMAGE=$(cat $OGLOGCOMMAND | grep "Total Time:")
+ogEcho log session "[40] $MSG_HELP_ogCreateImage : ogCreateImage $1 $2 $3 $4 $IMGPROG $IMGCOMP"
+ogCreateImage "$1" "$2" "$3" "/$4" "$IMGPROG" "$IMGCOMP" &>> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_IMAGE "ogCreteImage"; echo $?)
+RESUMECREATEIMAGE=$(grep "Total Time:" $OGLOGCOMMAND)
 TIMEAUX2=$[SECONDS-TIME2]
-echo "      $RESUMECREATEIMAGE " | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "      $RESUMECREATEIMAGE "
+ogEcho log session "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s"
 
-
-
-#Extender sistema de archivos
+# Extender sistema de archivos
 TIME3=$SECONDS
-echo "[90] Extender sistema de archivos." | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[90] Extender sistema de archivos."
 ogExtendFs $1 $2 || exit $(ogRaiseError $OG_ERR_EXTENDFS "$1 $2"; echo $?)
 SIZEFS2=$(ogGetFsSize  $1 $2)
 TIMEAUX3=$[SECONDS-TIME3]
-echo "      $MSG_HELP_ogExtendFs  $NEWSIZEFS ->  $SIZEFS = $SIZEFS2: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
+ogEcho log session "      $MSG_HELP_ogExtendFs  $NEWSIZEFS ->  $SIZEFS = $SIZEFS2: $[TIMEAUX3/60]m $[TIMEAUX3%60]s"
 
 #TODO que hacer si error al extender sistemade archivos
 
-
-
 #resumen de la operacion
-IMGSIZE=$(ls -s `ogGetPath $3 $4.img`| cut -f1 -d" ")
-IMGOS=$(ogGetImageInfo `ogGetPath $3 $4.img`)
+IMGSIZE=$(ls -s `ogGetPath $3 /$4.img`| cut -f1 -d" ")
+IMGOS=$(ogGetImageInfo `ogGetPath $3 /$4.img`)
 
 TIME=$[SECONDS-TIME1]
-echo "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      FileSystem $PART with $NEWSIZEFS KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS $ogprotocol " | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      Image-file $4 metada: $IMGOS " | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s"
+ogEcho log session "      FileSystem $PART with $NEWSIZEFS KB data created onto file-image as $4 and used $IMGSIZE KB across DFS $ogprotocol"
+ogEcho log session "      Image-file $4 metada: $IMGOS"
+
+# Ejecuta scripts personalizado de postconfiguracion del sistema operativo modelo. 
+if which createImageCustomPost &>/dev/null; then
+    createImageCustomPost "$1" "$2" "$3" "$4"
+fi
+
diff --git a/client/shared/scripts/updateCache b/client/shared/scripts/updateCache
--- a/client/shared/scripts/updateCache
+++ b/client/shared/scripts/updateCache
@@ -1,6 +1,4 @@
 #!/bin/bash
-
-
 #/**
 #         updateCache
 #@brief   Actualiza la cache del cliente con imagen o fichero iso.
@@ -25,90 +23,145 @@
 #@version 1.0.1 - Control de espacio requerido
 #@author  Antonio J.Doblas Viso
 #@date   2011-05-10
+#@version 2.0.1 - Imagenes sincronizadas
+#@date    2013-02-20
 #*/ ##
 
 PROG="$(basename $0)"
 if [ $# -lt 3 ]; then
-    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG str_REPO _str_Relative_Path_OGIMG_with_/ PROTOCOLO OPCIONES_PROTOCOLO OPCIONES_UPDATECACHE"
+    ogRaiseError session $OG_ERR_FORMAT "$MSG_FORMAT: $PROG str_REPO _str_Relative_Path_OGIMG_with_/ PROTOCOLO OPCIONES_PROTOCOLO OPCIONES_UPDATECACHE"
     exit $?
 fi
 
 #Carga del configurador del engine
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
-REPOSITORIO="$1"
-PROTOCOLO="$3"
+# Clear temporary file used as log track by httpdlog
+# Limpia los ficheros temporales usados como log de seguimiento para httpdlog
+echo " " > $OGLOGCOMMAND
+[ "$(ogGetCaller)" == "deployImage" -o "$(ogGetCaller)" == "restoreBaseImage" -o "$(ogGetCaller)" == "restoreDiffImage" ] || echo -n "" > $OGLOGSESSION;
+
+REPOSITORIO="${1^^}"
+PROTOCOLO="${3^^}"
 OPTPROTOCOLO="$4"
 REPOIP=$(ogGetRepoIp)
-echo $REPOSITORIO $REPOIP $PROTOCOLO $OPTPROTOCOLO
+ogEcho log session  $REPOSITORIO $REPOIP $PROTOCOLO $OPTPROTOCOLO
 
 # Si el repositorio local CACHE no existe error 15.
 if ! $(ogFindCache >/dev/null); then
-        ogRaiseError $OG_ERR_NOTCACHE "CACHE"
+        ogRaiseError session $OG_ERR_NOTCACHE "CACHE"
         exit $?
 fi
 
-echo "$MSG_SCRIPTS_UPDATECACHE_DOUPDATE "
-#TODO: ogUpdateCacheIsNecesary debe borrar la imagen que tenga igual nombre pero distinto sum-
-ogUpdateCacheIsNecesary $1 $2; RETVAL=$?
+# comprobar si la imagen existe (.img, .img.diff o directorio)
+REPOFILE=$(ogGetPath "REPO" "/$2") || exit $(ogRaiseError session $OG_ERR_NOTFOUND "REPO /$2"; echo $?) 
+
+ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_DOUPDATE"
+# Distingo si es monolitica o sincronizable
+file "$REPOFILE" | grep -i -e " BTRFS Filesystem " -e " ext4 filesystem " -e " directory" 2>&1 > /dev/null
+if [ $? == 0 ]; then
+	IMGSYNC=TRUE
+	# Para imagen sincronizada, si hay imagen en cache siempre protocolo = rsync.
+	CACHEFILE="$(ogGetPath "CACHE" "/$2")"  && PROTOCOLO="RSYNC"
+	# Si es sincronizada tipo directorio  siempre protocolo = rsync.
+	[ -d $REPOFILE ] && PROTOCOLO="RSYNC" && IMGTYPE="dir"
+
+	# Si es imagen sincronizada siempre da distinto md5. No podemos comprobar -> actualizamos.
+	RETVAL=0
+else
+	# Si la imagen es monolitica y ha elegido protocolo = RSYNC salimos con error.
+	[ $PROTOCOLO == "RSYNC" ] && exit $(ogRaiseError session $OG_ERR_DONTSYNC_IMAGE "REPO $2"; echo $?)
+	IMGSYNC=FALSE
+	#TODO: ogUpdateCacheIsNecesary debe borrar la imagen que tenga igual nombre pero distinto sum-
+	ogUpdateCacheIsNecesary $1 $2
+	RETVAL=$?
+fi
 # si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
 [ "$RETVAL" == "1" ] && exit 0
-[ "$RETVAL" -gt  "1" ] && exit 1
+[ "$RETVAL" -gt  "1" ] && exit $OG_ERR_UPDATECACHE
 
+ogEcho log session  "$MSG_SCRIPTS_UPDATECACHE_CHECKSIZECACHE" 
 CACHESIZE=$(ogGetCacheSize)
 CACHESIZEFREE=$(ogGetFreeSize `ogFindCache`)
 FILESIZE=$(ls -sk $(ogGetPath $REPOSITORIO "$2") | cut -f1 -d" ")
-
-
-echo "$MSG_SCRIPTS_UPDATECACHE_CHECKSIZECACHE"
-#ERROR CACHESIZE 16
-if [ "$FILESIZE" -ge "$CACHESIZE" ]  
-then
-	echo "WARNING: $MSG_ERR_CACHESIZE:  $2 = $FILESIZE > CACHE = $CACHESIZE" | tee -a $OGLOGSESSION $OGLOGFILE
-	ogRaiseError $OG_ERR_CACHESIZE "CACHE"
-    exit $?
+if [ "$IMGTYPE" == "dir" ]; then
+	ogEcho log session "   * $MSG_SCRIPTS_UPDATECACHE_CHECKSIZEDIR"
+	ogEcho log session "     du -sk $REPOFILE"
+	REALFILESIZE=$(du -sk "$REPOFILE"|awk '{print $1}')
+else
+	REALFILESIZE=$(ls -l --block-size=1024 $REPOFILE | cut -f5 -d" ")
 fi
 
-echo "$MSG_SCRIPTS_UPDATECACHE_IFNOTCACHEDO"
+# La sincronizada, si existe la imagen en cache el espacio necesario
+#	 es la nueva menos lo que ocupa la que ya hay.
+if [ "$PROTOCOLO" == "RSYNC" ]; then
+	if [ "$CACHEFILE" == "" ]; then
+		CACHEFILESIZE=0
+	else
+	   if [ "$IMGTYPE" == "dir" ]; then
+		ogEcho log session "   * $MSG_SCRIPTS_UPDATECACHE_CHECKSIZEDIR $CACHEFILESIZE"
+		ogEcho log session "     du -sk $CACHEFILE"
+		CACHEFILESIZE=$(du -sk $CACHEFILE |awk '{print $1}')
+	   else
+		CACHEFILESIZE=$(ls -l --block-size=1024 "$CACHEFILE" | cut -f5 -d" ")
+	   fi
+	fi
+	let SIZEREQUIRED=$REALFILESIZE-$CACHEFILESIZE
+	[ $SIZEREQUIRED -lt 0 ] && SIZEREQUIRED=0
+else
+	SIZEREQUIRED=$FILESIZE
+fi
+
 #ERROR CACHESIZE 16
-if [ "$FILESIZE" -ge "$CACHESIZEFREE" ]  
+if [ "$SIZEREQUIRED" -ge "$CACHESIZE" ]  
 then
-	# echo "[ ] No hay espacio sufiente en la CACHE, detectar que hacer con engine.cfg"  | tee -a $OGLOGSESSION $OGLOGFILE
-	case $ACTIONCACHEFULL in 
+	ogEcho log session "$MSG_WARNING: $MSG_ERR_CACHESIZE:  $2 = $SIZEREQUIRED > CACHE = $CACHESIZE"
+	ogRaiseError session $OG_ERR_CACHESIZE "CACHE"
+	exit $?
+fi
+
+ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_IFNOTCACHEDO"
+#ERROR CACHESIZE 16
+if [ "$SIZEREQUIRED" -ge "$CACHESIZEFREE" ]  
+then
+	# ogEcho log session "[ ] No hay espacio sufiente en la CACHE, detectar que hacer con engine.cfg"
+	case "$ACTIONCACHEFULL" in 
 	NONE)
 		NEXTOPERATION=UNICAST
 	;;
 	FORMAT)
-	    echo "[51] $MSG_HELP_ogFormatCache "  | tee -a $OGLOGSESSION $OGLOGFILE
+	    ogEcho log session  "[51] $MSG_HELP_ogFormatCache "
 	    ogUnmountCache
 	    ogFormatCache
 	    ogMountCache
 	    NEXTOPERATION=REPEAT
 	;;
 	DELETE)
-		echo "[51] #MSG_HELP_ogDeleteTree $OGCAC$OGIMG/* "  | tee -a $OGLOGSESSION $OGLOGFILE
+	    ogEcho log session "[51] #MSG_HELP_ogDeleteTree $OGCAC$OGIMG/* "
 	    rm -fr  $OGCAC$OGIMG/*
 	    NEXOPERATION=REPEAT
 	;;
 	*)
-	 	echo "WARNING: $MSG_ERR_CACHESIZE:  $2 = $FILESIZE > CACHE = $CACHESIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
-		ogRaiseError $OG_ERR_CACHESIZE "CACHE"
-    	exit $?
+	 	ogEcho log session "$MSG_WARNING: $MSG_ERR_CACHESIZE:  $2 = $FILESIZE > CACHE = $CACHESIZEFREE"
+		ogRaiseError session $OG_ERR_CACHESIZE "CACHE"
+		exit $?
 	;;
 	esac	
 fi
 
-ogUpdateCacheIsNecesary $REPOSITORIO "$2"; RETVAL=$?
+# Comprobamos que imagen cache igual a la del repo. Si sincronizada no podemos comprobar. 
+[ "$IMGSYNC" == "TRUE" ] || ogUpdateCacheIsNecesary $REPOSITORIO "$2"
+RETVAL=$?
 # si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
 [ "$RETVAL" == "1" ] && exit 0
-[ "$RETVAL" -gt  "1" ] && exit 1
+[ "$RETVAL" -gt  "1" ] && exit $OG_ERR_UPDATECACHE
 
 ogMountCache >/dev/null
 
 ## Si no existe, crear subdirectorio para el fichero en la cache.
 IMGDIR=$(ogGetParentPath CACHE "/$2")
 if [ $? != 0 ]; then
-    echo "[5] $MSG_HELP_ogMakeDir  \"$2 $(dirname "$2")."
+    ogEcho log session "[5] $MSG_HELP_ogMakeDir  \"$2 $(dirname "$2")."
     ogMakeDir CACHE $(dirname "/$2")
     IMGDIR=$(ogGetParentPath CACHE "/$2") || exit $?
 fi
@@ -116,68 +169,131 @@ fi
 TIME1=$SECONDS
 
 case "$PROTOCOLO" in
-	torrent | TORRENT )
-		echo "ogCopyFile $1 $2.torrent absolute $OGCAC/$OGIMG"
+	TORRENT)
+		ogEcho log session "ogCopyFile $1 $2.torrent absolute $OGCAC/$OGIMG"
 		# tiempos 
 		timewait=$(expr $(printf '%d\n' 0x$(ogGetMacAddress | awk -F: '{print $5$6}')) \* 120 / 65535)                         
-		ogCopyFile $REPOSITORIO "$2.torrent" "$IMGDIR"
+		ogCopyFile $REPOSITORIO "$2.torrent" "$IMGDIR" 2>&1 | tee -a   $OGLOGCOMMAND
 		#TODO: comprobar que el tracker definido en el fichero es correcto.
-    	#TODO comprobar que el fichero torrent está en cache
+    		#TODO comprobar que el fichero torrent está en cache
 		# retardamos el inicio -aleatorio de 0 a 120 segundos- al tracker para gestionar mas de +-40 equipos 
 		P2PWAIT=$[ ( $RANDOM % 120 )  + 1 ]
-		echo "   [ ] $MSG_SCRIPTS_TASK_SLEEP :  $P2PWAIT seconds ogTorrentStart CACHE $2.torrent $4" | tee -a $OGLOGSESSION $OGLOGFILE
+		ogEcho log session "   [ ] $MSG_SCRIPTS_TASK_SLEEP :  $P2PWAIT seconds ogTorrentStart CACHE $2.torrent $4"
 		sleep $P2PWAIT
-		echo "   [  ] $MSG_SCRIPTS_TASK_START:  ogTorrentStart CACHE $2.torrent $4" | tee -a $OGLOGSESSION $OGLOGFILE
-		ogTorrentStart CACHE "$2.torrent" $4
-		RESUMEUPDATECACHE=$(cat $OGLOGCOMMAND | grep -B1 "Download") 
+		ogEcho log session "   [  ] $MSG_SCRIPTS_TASK_START:  ogTorrentStart CACHE $2.torrent $4"
+		ogTorrentStart CACHE "$2.torrent" $4 2>&1 | tee -a   $OGLOGCOMMAND
+		RESUMEUPDATECACHE=$(grep -m 1 -B1 "Download" $OGLOGCOMMAND) 
+		RESUMEUPDATECACHEbf=$(grep -m 1 "Download" $OGLOGCOMMAND) 
+		if [ "$RESUMEUPDATECACHEbf" == "Download complete." ]; then
+			rm $IMGDIR$2".torrent.bf" 2>&1 | tee -a   $OGLOGCOMMAND
+		fi
 	;;
-	multicast | MULTICAST )
+	MULTICAST)
 		PORT=$(echo $OPTPROTOCOLO | cut -f1 -d":")
 		let PORTAUX=$PORT+1
-		echo "$MSG_SCRIPTS_UPDATECACHE_CHECKMCASTSESSION : $REPOIP:$PORTAUX:$PORT"
-        #TODO: ticket 379
+		ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_CHECKMCASTSESSION : $REPOIP:$PORTAUX:$PORT"
+		#TODO: ticket 379
 		NUMBER=$[ ( $RANDOM % 30 )  + 1 ]
 		sleep $NUMBER
 		#FIN TODO
 		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
 		then 
-	   		ogMcastReceiverFile $PORT CACHE "$2"
+	   		ogMcastReceiverFile $PORT CACHE "$2" 2>&1  | tee -a   $OGLOGCOMMAND
+
 		else
 		    # TODO ticket 379 Realizar la petición basada en identificador de operacion
-	   		echo "$MSG_SCRIPTS_TASK_START :  hose $REPOIP 2009 --out sh -c "echo -ne START_MULTICAST $2 $OPTPROTOCOLO""
+	   		ogEcho log session "$MSG_SCRIPTS_TASK_START :  hose $REPOIP 2009 --out sh -c \"echo -ne START_MULTICAST $2 $OPTPROTOCOLO\""
 	   		hose $REPOIP 2009 --out sh -c "echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
 	   		#echo "espero y llamo a: ogMcastReceiverFile $PORT CACHE $2"
 	   		sleep 10
 	   		if (nmap -n -sU -p $PORTAUX $REPOIP | grep open)
 	   		then 
-	   			ogMcastReceiverFile $PORT CACHE "$2"
+	   			ogMcastReceiverFile $PORT CACHE "$2" 2>&1  | tee -a   $OGLOGCOMMAND
 			else
-			    echo "$MSG_SCRIPTS_TASK_ERR : hose $REPOIP 2009 --out sh -c echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
-	   		    exit 1
+				ogEcho log session "$MSG_SCRIPTS_TASK_ERR : hose $REPOIP 2009 --out sh -c echo -ne START_MULTICAST $2 $OPTPROTOCOLO"
+	   			exit $OG_ERR_UPDATECACHE
 	   		fi
 		fi
 		#cat $OGLOGCOMMAND.tmp | grep -B1 "Transfer complete"
 		sleep 5
 		#cat $OGLOGCOMMAND.tmp | grep -B1 "Transfer complete"
-		RESUMEUPDATECACHE=$(cat $OGLOGCOMMAND.tmp | grep -B1 "Transfer complete")
+		RESUMEUPDATECACHE=$(grep -m 1  -B1 "Transfer complete" $OGLOGCOMMAND.tmp)
 	;;
-	unicast | UNICAST )
-		echo "unicast"
-		ogCopyFile $REPOSITORIO "$2" "$IMGDIR"
+	UNICAST)
+		#ogEcho log session "unicast"
+		ogCopyFile $REPOSITORIO "$2" "$IMGDIR" 2>&1  | tee -a   $OGLOGCOMMAND
+		sleep 5
+		RESUMEUPDATECACHE=$(grep -m 1  "100%" $OGLOGCOMMAND.tmp)
+	;;
+	RSYNC)
+	   # Si parametro de protocolo no era rsync, mensaje de cambio protocolo
+	   [ "${3^^}" == "RSYNC" ] || ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_RSYNCPROTOCOLCHANGE"
+	   # Opciones de rsync
+	   USERRSYNC="opengnsys"
+	   PASSWORD=" --password-file=/scripts/passrsync "
+	   OPTRSYNC=" --delete --progress "
+	   [ "$ogrsyncz" ==  "true" ] && OPTRSYNC="z $OPTRSYNC"
+	   [ "$ogrsyncw" ==  "true" ] && OPTRSYNC="w$OPTRSYNC"
+
+	   if [ -d $REPOFILE ]; then
+		# Si es sincronizada tipo directorio.
+		[ -d "$OGCAC$OGIMG/$2" ] || mkdir "$OGCAC$OGIMG/$2"
+		ogEcho log session "rsync -aHAX$OPTRSYNC  $USERRSYNC@$REPOIP::ogimages/$2/ $OGCAC$OGIMG/$2"
+		rsync -aHAX$OPTRSYNC  $PASSWORD "$USERRSYNC@$REPOIP::ogimages/$2/" "$OGCAC$OGIMG/$2" 2>> $OGLOGCOMMAND  | egrep "^sent|^sending|^total%" >>  $OGLOGCOMMAND
+           else
+		# Si es sincronizada tipo archivo.
+		[ "${2##*.}" == "img" ] && IMGTYPE="img" ||  IMGTYPE="diff"
+		IMGNAME="${2%.img*}"
+
+		DIRMOUNT=$(ogGetMountImageDir "$IMGNAME" $IMGTYPE)
+		DIRLOCAL="/tmp/$DIRMOUNT"
+		mkdir "$DIRLOCAL" 2>/dev/null
+		ogEcho log session "$MSG_SCRIPTS_UPDATECACHE_CHECKSIZEIMG"
+
+		# Si la imagen no existe la creo
+		# Si la imagen del repositorio es mayor, redimensiono la imagen de cache
+		if [ "$CACHEFILE" == "" -o  $CACHEFILESIZE -lt $REALFILESIZE ]; then
+			ogEcho log session "$MSG_HELP_ogCreateFileImage"
+			ogCreateFileImage CACHE "$IMGNAME" $IMGTYPE $REALFILESIZE 
+                	TIMEAUX3=$[SECONDS-TIMEAUX3]
+                	ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s"
+		fi
+		# Montamos las imagenes para sincronizarlas. Quitamos / inicial.
+		ogMountImage CACHE  "${IMGNAME#\/}" $IMGTYPE || exit $?
+		ogMountImage REPO  "${IMGNAME#\/}" $IMGTYPE 
+		# Esperamos que se monte la imagen en el servidor
+		ogWaitMountImage  REPO  "$IMGNAME" $IMGTYPE || exit $?
+		ogEcho log session "      rsync -aHAX$OPTRSYNC  $USERRSYNC@$REPOIP::ogimages/$DIRMOUNT/ $DIRLOCAL"
+		rsync -aHAX$OPTRSYNC  $PASSWORD "$USERRSYNC@$REPOIP::ogimages/$DIRMOUNT/" "$DIRLOCAL" 2>>$OGLOGCOMMAND  | egrep "^sent|^sending|^total|%" >>   $OGLOGCOMMAND
+		# RETVAL="1" -> OK  RETVAL="2" -> error  # valores igual que ogUpdateCacheIsNecesary
+		[ ${PIPESTATUS[0]} -eq 0 ] && RETVAL="1"|| RETVAL="2"
+		# Desmonto las imagenes
+		ogUnmountImage CACHE  "$IMGNAME" $IMGTYPE
+		ogUnmountImage REPO  "$IMGNAME" $IMGTYPE
+	   fi
 	;;
 esac
 
 TIME1=$[SECONDS-TIME1]
-echo "   [ ] $RESUMEUPDATECACHE " | tee -a $OGLOGSESSION $OGLOGFILE
-echo "   [ ] $MSG_SCRIPTS_TIME_PARTIAL updateCache $[TIME1/60]m $[TIME1%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-echo "   [ ] $MSG_SCRIPTS_TASK_START $MSG_HELP_ogCalculateChecksum " | tee -a $OGLOGSESSION $OGLOGFILE
-TIME2=$SECONDS
-ogUpdateCacheIsNecesary $REPOSITORIO "$2"; RETVAL=$?
-TIME2=$[SECONDS-TIME2]
-echo "   [ ] $MSG_SCRIPTS_TIME_PARTIAL $MSG_HELP_ogCalculateChecksum $[TIME2/60]m $[TIME2%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
-# si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizasmo-exit 0  || si RETVAL>2 exit 1
-[ "$RETVAL" == "0" ] && exit 1
+ogEcho log session "   [ ] $RESUMEUPDATECACHE "
+ogEcho log session "   [ ] $MSG_SCRIPTS_TIME_PARTIAL updateCache $[TIME1/60]m $[TIME1%60]s"
+ogEcho log session "   [ ] $MSG_SCRIPTS_TASK_START $MSG_HELP_ogCalculateChecksum "
+TIME2=$SECONDS
+# Si es imagen sincronizada siempre da distinto md5. No podemos comprobar 
+if [ "$IMGSYNC" == "TRUE" ]; then 
+	# RETVAL="1" -> OK  RETVAL="2" -> error  # valores igual que ogUpdateCacheIsNecesary
+	[ $PROTOCOLO == "RSYNC" ] || RETVAL=1
+else
+	ogUpdateCacheIsNecesary $REPOSITORIO "$2"
+	RETVAL=$?
+fi
+if [ "$(ogGetCaller)" != "deployImage" ]; then
+	TIME2=$[SECONDS-TIME2]
+	ogEcho log session "   [ ] $MSG_SCRIPTS_TIME_PARTIAL $MSG_HELP_ogCalculateChecksum $[TIME2/60]m $[TIME2%60]s"
+fi
+# si RETVAL=0 => actualizamos  si RETVAL=1 no actaulizamos-exit 0  || si RETVAL>2 exit 1
+[ "$RETVAL" == "0" ] && exit $OG_ERR_UPDATECACHE
 [ "$RETVAL" == "1" ] && exit 0
-[ "$RETVAL" -gt  "1" ] && exit 1
+[ "$RETVAL" -gt  "1" ] && exit $OG_ERR_UPDATECACHE
 
diff --git a/server/bin/setserveraddr b/server/bin/setserveraddr
--- a/server/bin/setserveraddr
+++ b/server/bin/setserveraddr
@@ -5,12 +5,17 @@
 # Uso:	setserveraddr iface
 # Autor: Ramon Gomez - Univ. Sevilla
 # Fecha: 2011-01-25
+# Versión: 1.0.5 - Regenerar ficheros de configuración.
+# Autor: Ramon Gomez - Univ. Sevilla
+# Fecha: 2014-06-06
 
+
+# Variables globales.
+PROG="$(basename $0)"
 
 # Comprobar parámetros.
-PROG="$(basename $0)"
 if [ $# -ne 1 ]; then
-	echo "$PROG: Incorrect operand. Format: $PROG device" >&2
+	echo "$PROG: Incorrect operand. Format: $PROG interface" >&2
 	exit 1
 fi
 if [ "$USER" != "root" ]; then
@@ -18,21 +23,41 @@ if [ "$USER" != "root" ]; then
 	exit 1
 fi
 
+# Aviso informando de que los clientes iniciados pueden quedarse colgados.
+read -p "WARNING: initiated clients can hang. Continue? (y/n): " ANSWER
+if [ "${ANSWER^^}" != "Y" ]; then
+	echo "Operation canceled."
+	exit 0
+fi
+
 # Detectar la interfaz de red.
 DEVICES=$(ip -o link show up|awk -F: '$2!~/lo/ {print $2}')
-FOUND=0
-for dev in $DEVICES; do
-	[ "$dev" == "$1" ] && FOUND=1;
+for DEV in $DEVICES; do
+	# Si se encuentra la interfaz de red, obtener su dirección IP.
+	[ "$DEV" == "$1" ] && SERVERIP=$(ip -o addr show dev $DEV | awk '$3~/inet$/ {sub (/\/.*/, ""); print ($4)}')
 done
 
-if [ $FOUND == 1 ]; then
+# Comprobar si se ha detectado dirección IP.
+if [ -n "$SERVERIP" ]; then
+	# Ficheros temporales.
+	tmpfile=$(mktemp /tmp/og.XXXXX)
+	MYCNF=$(mktemp /tmp/.my.cnf.XXXXX)
+	trap "rm -f $tmpfile $MYCNF" 1 2 3 6 9 15
+
 	# Comprobar si hay que modificar la configuración de DHCP.
 	CHANGE=0
-	for f in /etc/{dhcp,dhcp3}/dhcpd.conf; do
-		file="${f/./-$1.}"
-		if [ -f $file -a ! $f -ef $file ]; then
-			ln -f $file $f
-			CHANGE=1
+	for f in /etc/{dhcp,hcp3}/dhcpd.conf; do
+		if [ -f $f ]; then
+			# Cambiar el parámetro "next-server" de DHCP.
+			sed "s/next-server.*/next-server $SERVERIP/" $f >$tmpfile
+			file="${f/./-$1.}"
+			# Copiar el fichero y enlazarlo si hay cambios.
+			if ! diff -q $tmpfile $file &>/dev/null; then
+				mv $tmpfile $file
+				chmod 644 $file
+				ln -f $file $f
+				CHANGE=1
+			fi
 		fi
 	done
 	# Si ha cambiado la configuración, reiniciar DHCP.
@@ -43,33 +68,77 @@ if [ $FOUND == 1 ]; then
 	else
 		echo "Don't change the DHCP configuration."
 	fi
-	# Comprobar si hay que modificar la configuración de OpenGnsys.
+
+	# Guardar la IP anterior del repositorio.
 	OPENGNSYS=/opt/opengnsys
+	source $OPENGNSYS/etc/ogAdmRepo.cfg
+	OLDSERVERIP=$IPlocal
+
+	# Comprobar si hay que modificar la configuración de OpenGnsys.
 	CHANGE=0
-	for f in etc/{ogAdmServer,ogAdmRepo,ogAdmAgent}.cfg www/controlacceso.php client/etc/ogAdmClient.cfg; do
-		file="$OPENGNSYS/${f/./-$1.}"
-		if [ ! -f $file ]; then
+	# Procesar los ficheros de configuración de OpenGnSys.
+	for f in $OPENGNSYS/{etc/{ogAdmServer,ogAdmRepo,ogAdmAgent}.cfg,www/controlacceso.php,client/etc/ogAdmClient.cfg}; do
+		# Error si no existe algún fichero de configuración.
+		if [ ! -f $f ]; then
 			echo "$PROG: File $file does not exist." >&2
 			exit 2
 		fi
-		cfg=$OPENGNSYS/$f
-		if [ ! $cfg -ef $file ]; then
-			ln -f $file $cfg
+		# Cambiar la IP del servidor:
+		# - variables  ServidorAdm  e  IPlocal,
+		# - servidor o IP en URLs excepto si contienen "localhost".
+		sed -e "s,ServidorAdm=.*,ServidorAdm=$SERVERIP," \
+		    -e "s,IPlocal=.*,IPlocal=$SERVERIP," \
+		    -e '/localhost/!s,http://[^/]*/\(.*\),http://'$SERVERIP'/\1,' $f >$tmpfile
+		file="${f/./-$1.}"
+		# Copiar el fichero y enlazarlo si hay cambios.
+		if ! diff -q $tmpfile $file &>/dev/null; then
+			mv $tmpfile $file
+			chmod 644 $file
+			ln -f $file $f
 			CHANGE=1
 		fi
 	done
+
 	# Si ha cambiado la configuración, reiniciar OpenGnSys y actualizar la BD.
 	if [ $CHANGE == 1 ]; then
 		/etc/init.d/opengnsys restart
 		source $OPENGNSYS/etc/ogAdmServer.cfg
-		mysql -u "$USUARIO" -p"$PASSWORD" -D "$CATALOG" -N -e \
-			 "UPDATE entornos SET ipserveradm='$ServidorAdm' WHERE identorno=1"
-		echo "Default server interface set to: $1 ($ServidorAdm)"
+		# Componer fichero con credenciales de conexión.  
+ 		cat << EOT > $MYCNF
+[client]
+user=$USUARIO
+password=$PASSWORD
+EOT
+		# Actualizar IP del servidor en la BD.
+		mysql --defaults-extra-file=$MYCNF -D "$CATALOG" -e \
+			 "UPDATE entornos
+			     SET ipserveradm='$SERVERIP'
+			   WHERE identorno=1"
+
+		# Actualizar IP del repositorio en la BD.
+		mysql --defaults-extra-file=$MYCNF -D "$CATALOG" -e \
+			 "UPDATE repositorios
+			     SET ip='$SERVERIP'
+			   WHERE ip='$OLDSERVERIP'"
+
+		# Mostrar instrucciones a realizar tras la ejecución.
+		cat << EOT
+Default server interface set to: $1 ($SERVERIP)
+
+Manual tasks:
+Check DHCP configuration file and restart service, if needed.
+Log-in as Web Console organization user.
+ - Check URLs in all menus.
+ - Run Advanced Netboot in all rooms.
+
+EOT
 	else
+		# Mensaje indicando que no se han cambiado datos.
 		echo "Don't change the default interface: $1"
 	fi
 else
-	echo "$PROG: Network device not found. Format: $PROG device" >&2
+	# Error: interfaz de red no encontrado.
+	echo "$PROG: Network device not found. Format: $PROG interface" >&2
 	exit 1
 fi
 
