#565 Imagenes sincronizadas: control de errores
git-svn-id: https://opengnsys.es/svn/branches/version1.0@3742 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createBaseImage b/client/shared/scripts/createBaseImage
--- a/client/shared/scripts/createBaseImage
+++ b/client/shared/scripts/createBaseImage
@@ -16,16 +16,27 @@
 #@exception OG_ERR_NOTWRITE   # 14 error de escritura
 #@exception OG_ERR_NOTCACHE   # 15 si cache no existe 15
 #@exception OG_ERR_CACHESIZE  # 16 si espacio de la cache local o remota no tiene espacio 16
-#@note  se toma como punto de partida el script createImage, cambiando solo lo especifico para la imagen squash
+#@exception OG_ERR_DONTMOUNT_IMAGE # 70 Error al montar una imagen sincronizada
+#@note  se toma como punto de partida el script createImage, cambiando solo lo especifico para la imagen sincronizada
 #@todo: que hacer, si el tamaño de la cache es sufciente, pero no tiene espacio libre
-#@version 1.0 - creación imagen con mksquasfs
+#@version 1.0 - creación imagen con btrfs
 #@author  
 #@date   2012-12-04
 #*/ ##
 
-trap "ogUnlockImage $3 \"/$4.$IMGEXT\"; ogUnlock $1 $2;  hose $REPOIP 2009 --out sh -c 	\"echo -ne UMOUNT_IMAGE $4 $IMGEXT\" ; umount \"$DIRMOUNT\"; exit 1" 1 2 3 6 9 14 15
-#ogUnmountImage $3 "$4" $IMGEXT
+trap "onexit $1 $2 $3 \"$4\"" 1 2 3 6 9 14 15 ERR
 
+# Si salimos con error demontamos la imagen y desbloqueamos la imagen y la particion
+function onexit() {
+    local exit_status=$?
+    ogUnmountImage $3 "$4" $IMGEXT &>/dev/null
+    # Si la partición/imagen no estaba bloqueada -> la desbloqueo
+    [ $exit_status -ne 4 ] || ogUnlockImage "$3" "/$4.$IMGEXT" || ogUnlock $1 $2
+    echo ogUnmountImage $3 "$4" $IMGEXT 
+    echo ogUnlockImage "$3" "/$4.$IMGEXT"
+    echo ogUnlock $1 $2
+    exit $exit_status
+}
 
 TIME1=$SECONDS
 #Carga el configurador del engine desde el fichero engine.cfg
@@ -35,10 +46,16 @@ TIME1=$SECONDS
 CREATESPEED=${CREATESPEED:-"100000*4"}
 
 PROG="$(basename $0)"
-if [ $# -ne 4 ]; then
-    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE imagen"
-    exit $?
+echo $PROG
+# Si se solicita, mostrar ayuda.
+if [ "$*" == "help" ]; then
+    ogHelp  "$PROG: $MSG_HELP_createBaseImage" \
+	    "$PROG ndisco nparticion REPO|CACHE base_image" \
+            "$PROG 1 1 REPO Windows7"
+   exit 0
 fi
+
+[ $# -ne 4 ] && ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE imagen" 
 
 # Valores por defecto en etc/engine.cfg
 IMGEXT="img"
@@ -50,22 +67,22 @@ echo  -n ""> $OGLOGSESSION
 echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION  $OGLOGFILE
 
 # Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$3" "$4.$IMGEXT" && echo  "$MSG_ERR_LOCKED $3 $4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE && exit $(ogRaiseError $OG_ERR_LOCKED "$3 $4.$IMGEXT" ; echo $?)
-ogIsLocked "$1" "$2" &&  echo  "$MSG_ERR_LOCKED $1 $2"  | tee -a $OGLOGSESSION $OGLOGFILE && exit $(ogRaiseError $OG_ERR_LOCKED  "$1 $2"; echo $?)
+ogIsImageLocked "$3" "$4.$IMGEXT" && ogRaiseError $OG_ERR_LOCKED "$3 $4.$IMGEXT"
+ogIsLocked "$1" "$2" && ogRaiseError $OG_ERR_LOCKED  "$1 $2"
 
 # Si el repositorio es CACHE comprobamos que exista
 if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
-	! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE " | tee -a $OGLOGSESSION $OGLOGFILE ; echo $?)
+	! ogFindCache >/dev/null && ogRaiseError $OG_ERR_NOTCACHE "CACHE "
 fi
 
 echo " " > $OGLOGCOMMAND
 
 # Obtener información de los parámetros de entrada.
-PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2"; echo $?)
+PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || ogRaiseError $OG_ERR_PARTITION "$1 $2"
 
 #Comprobamos acceso de escritura.
 DIRTEMP=$(date +%Y%m%d-%H%M%S)
-ogMakeDir $3 /$4$DIRTEMP 2>/dev/null || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3"; echo $?) && ogDeleteTree $3 /$4$DIRTEMP 
+ogMakeDir $3 /$4$DIRTEMP 2>/dev/null || ogRaiseError $OG_ERR_NOTWRITE "$3" && ogDeleteTree $3 /$4$DIRTEMP 
 
 #Comprobar espacio que requerira la imagen para ser almacenada
 echo " " > $OGLOGCOMMAND
@@ -82,10 +99,9 @@ then
 	[ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
 else
  	ogRaiseError $OG_ERR_PARTITION "$1 $2"
-    	exit $?
 fi
 echo "[16]$MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
-[ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3" || echo $?)
+[ $SIZEREQUIRED -gt $SIZEFREE ] && ogRaiseError $OG_ERR_CACHESIZE "$3"
 
 IMGDIR=$(ogGetParentPath "$3" "/$4")
 IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
@@ -93,10 +109,9 @@ IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
 SIZEFS=$(ogGetFsSize  $1 $2)
-#FSTYPE=$(ogGetFsType $1 $2)   
 echo "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGLOGFILE
 ogUnmount $1 $2
-ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2" && echo $?)
+ogCheckFs $1 $2 &> $OGLOGCOMMAND || ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2"
 
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
@@ -113,14 +128,13 @@ ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
 echo "[50] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
 echo "      $MSG_HELP_ogCreateInfoImage"  | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateInfoImage $1 $2 $IMGEXT
+echo $?
 
 TIMEAUX3=$[SECONDS-TIME2]
 echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
-
 # Esperamos que el servidor termine de crear y montar la imagen
-#ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED || exit $(ogRaiseError "Error al montar la imagen $1 $2 $3: time_out $TIMEAUX seg."; echo $?)
-ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED  || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out $TIMEAUX seg."; echo $?)
+ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED  || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out."
 
 
 # Sincronizamos los datos de la particion con la imagen.
@@ -136,8 +150,7 @@ TIMEAUX5=$[SECONDS-TIMEAUX3]
 echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Comprobamos que la imagen esta bien detectacdo que es un sistema de ficheros.
-file $IMGFILE|grep "BTRFS Filesystem" 2>&1 >/dev/null
-[ $? == 0 ] || exit $(ogRaiseError $OG_ERR_IMAGE "$3 $4" ; echo $?)
+file $IMGFILE|grep "BTRFS Filesystem" 2>&1 >/dev/null || ogRaiseError $OG_ERR_IMAGE "$3 $4" 
 
 TIMEAUX7=$[SECONDS-TIME2]
 echo "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
diff --git a/client/shared/scripts/restoreBaseImage b/client/shared/scripts/restoreBaseImage
--- a/client/shared/scripts/restoreBaseImage
+++ b/client/shared/scripts/restoreBaseImage
@@ -13,39 +13,49 @@
 #@exception OG_ERR_FORMAT  # 1 formato incorrecto.
 #@exception updateCache    # 15 No hay cache 
 #@exception updateCache    # 16 no hay espacio sufiente 
-#@exception "Error al montar la imagen" INTERNACIONALIZAR
-#@todo: Probar rsync desde repo sin samba
-#@todo: Se puede dar la opcion de que mantenga los ficheros nuevos.
-#@todo: Se puede dar la opcion que la trasferencia se manden los datos comprimidos.
+#@exception OG_ERR_LOCKED          # 4 Partición o fichero bloqueado.
+#@exception OG_ERR_NOTFOUND        # 2 Fichero o dispositivo no encontrado.
+#@exception OG_ERR_FILESYS         # 20 Sistema de archivos desconocido o no se puede montar
+#@exception OG_ERR_DONTSYNC_IMAGE  # 71 Imagen no sincronizable (es monolitica)
+#@exception OG_ERR_DONTMOUNT_IMAGE # 70 Error al montar una imagen sincronizada.
 #@note  se toma como punto de partida el script restoreImage
 #@version 1.0 - restauración de imagen con sincronizacion.
 #@author  
 #@date   2012-12-04
 #*/ ##
-trap "ogUnlock $3 $4; umount $DIRMOUNT; hose $REPOIP 2009 --out sh -c \"echo -ne UMOUNT_IMAGE $2 $IMGEXT\" "  1 2 3 6 9 14 15
+
+trap "onexit $1 \"$2\" $3 $4" 1 2 3 6 9 14 15 ERR
+
+# Si salimos con error demontamos la imagen y desbloqueamos la imagen y la particion
+function onexit() {
+    local exit_status=$?
+    ogUnmountImage "$1" "$2" "$IMGEXT"  &>/dev/null
+    # Si la partición/imagen no estaba bloqueada -> la desbloqueo
+    [ $exit_status -eq 4 ] && ogUnlock $3 $4 &>/dev/null
+    exit $exit_status
+}
 
 # Limpiamos los archivo de log
 echo "" >$OGLOGCOMMAND
 
 TIME1=$SECONDS
 PROG="$(basename $0)"
-if [ $# -lt 4 ]; then
-    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"
-    exit $?
+# Si se solicita, mostrar ayuda.
+if [ "$*" == "help" ]; then
+    ogHelp  "$PROG: $MSG_HELP_restoreBaseImage" \
+	    "$PROG REPO|CACHE imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]" \
+            "$PROG REPO Windows7 1 1 " \
+	    "$PROG CACHE Ubuntu12 1 6 MULTICAST 9000:full-duplex:239.194.14.00:150M:50:60"
+   exit 0
 fi
-echo "[1] $MSG_SCRIPTS_START  $0 $*" | tee -a $OGLOGFILE
 
-IMGEXT="img"
-
-# Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$1" "$2.$IMGEXT" && exit $(ogRaiseError $OG_ERR_LOCKED "$1 $2.$IMGEXT"; echo $?)
-ogIsLocked "$3" "$4" && exit $(ogRaiseError $OG_ERR_LOCKED  "$3 $4"; echo $?)
+[ $# -lt 4 ] &&     ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"
 
 # Carga del configurador del engine
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
 # Procesar parámetros de entrada
-REPOFILE=$(ogGetPath "REPO" "$2.$IMGEXT") || exit $(ogRaiseError $OG_ERR_NOTFOUND "REPO, $2.$IMGEXT"; echo $?)
+REPOFILE=$(ogGetPath "REPO" "$2.$IMGEXT") || ogRaiseError $OG_ERR_NOTFOUND "REPO, $2.$IMGEXT"
 # Comprobamos si el sistema de ficheros se puede montar
 ogMount "$3" "$4" &>/dev/null
 if [  $? -ne 0 ] ; then
@@ -55,29 +65,33 @@ if [  $? -ne 0 ] ; then
 	mount -o compress=lzo $REPOFILE $DIRMOUNT
 	FSTYPE=$(head -1 $DIRMOUNT/ogimg.info |cut -d: -f3)	
 	umount $DIRMOUNT
-	echo "      $MSG_FORMAT: $3 $4 $FSTYPE" | tee -a $OGLOGFILE
-	ogFormat "$3" "$4" "$FSTYPE" || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
-	ogMount "$3" "$4"  || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
+	echo "      $MSG_HELP_ogFormat: $3 $4 $FSTYPE" | tee -a $OGLOGFILE
+	ogFormat "$3" "$4" "$FSTYPE" || ogRaiseError $OG_ERR_FILESYS "$3 $4"
+	ogMount "$3" "$4"  || ogRaiseError $OG_ERR_FILESYS "$3 $4"
 fi
 
 
-
 # Comprobar que es sincronizable (con REPO)
-# TODO: crear mensaje de error
-file $REPOFILE | grep " BTRFS Filesystem" 2>&1 > /dev/null
-[ $? == 0 ]  ||  exit  $(ogRaiseError  "$1 $2"; echo $?)
+file $REPOFILE | grep " BTRFS Filesystem" 2>&1 > /dev/null ||  ogRaiseError $OG_ERR_DONTSYNC_IMAGE  "$1 $2"
+
+echo "[1] $MSG_SCRIPTS_START  $0 $*" | tee -a $OGLOGFILE
+IMGEXT="img"
+
+# Comprobamos si la imagen o la particion estan bloqueada:
+ogIsImageLocked "$1" "$2.$IMGEXT" && ogRaiseError $OG_ERR_LOCKED "$1 $2.$IMGEXT"
+ogIsLocked "$3" "$4" && ogRaiseError $OG_ERR_LOCKED  "$3 $4"
 
 PROTO=${5:-"UNICAST"}
 if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
    # Las imagenes sincronizables aunque sean iguales no tienen el mismo sum. 
    # Sincronizamos si existe el fichero y si no usamos updateCache.
-   echo "[10] $MSG_SCRIPTS_TASK_START updateCache REPO $2.img $PROTO $6" | tee -a $OGLOGFILE
-   echo "      updateCache REPO" "/$2.img" "$PROTO" "$6"   | tee -a $OGLOGFILE
-   updateCache REPO "/$2.img" "$PROTO" "$6"     &>> $OGLOGCOMMAND
+   echo "[10] $MSG_SCRIPTS_TASK_START updateCache REPO $2.$IMGEXT $PROTO $6" | tee -a $OGLOGFILE
+   echo "      updateCache REPO" "/$2.$IMGEXT" "$PROTO" "$6"   | tee -a $OGLOGFILE
+   updateCache REPO "/$2.$IMGEXT" "$PROTO" "$6"     &>> $OGLOGCOMMAND
    RETVAL=$?
    if [ "$RETVAL" != "0" ] 
         then 
-        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.img $5 $6 con error $RETVAL" | tee -a $OGLOGFILE 
+        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.$IMGEXT $5 $6 con error $RETVAL" | tee -a $OGLOGFILE 
         # RC=15 No hay cache 
         # RC=16 no hay espacio sufiente 
         exit $RETVAL 
@@ -87,10 +101,7 @@ if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
 
 fi 
 
-
-
 TIME2=$SECONDS
-
 
 # Restaurar la imagen.
 echo "[40] $MSG_HELP_ogRestoreImage: $1 $2 $3 $4"  | tee -a $OGLOGFILE
@@ -98,18 +109,18 @@ echo "[40] $MSG_HELP_ogRestoreImage: $1 $2 $3 $4"  | tee -a $OGLOGFILE
 ogLock $3 $4
 
 # Montamos la imagen basica.
-ogMountImage "$1" "$2" "img"  >/dev/null
+ogMountImage "$1" "$2" "$IMGEXT"  >/dev/null
 #  Comprobar que la imagen completa se ha montado.
-ogWaitMountImage "$1" "$2" "img" 
+ogWaitMountImage "$1" "$2" "$IMGEXT"  || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $IMGEXT: time_out."
 # Sincronizamos la partición con la imagen.
-echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 img $3 $4"  |tee -a $OGLOGFILE
-ogSyncRestore "$1" "$2" "img" $3 $4 
+echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 $IMGEXT $3 $4"  |tee -a $OGLOGFILE
+ogSyncRestore "$1" "$2" "$IMGEXT" $3 $4 
 
 TIMEAUX2=$[SECONDS-TIME2]
 echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a $OGLOGFILE
 
 # Desmontamos imagen basica.
-ogUnmountImage "$1" "$2" "img"
+ogUnmountImage "$1" "$2" "$IMGEXT"
 
 # Restableciendo acl
 ogUnlock $3 $4
diff --git a/client/shared/scripts/restoreDiffImage b/client/shared/scripts/restoreDiffImage
--- a/client/shared/scripts/restoreDiffImage
+++ b/client/shared/scripts/restoreDiffImage
@@ -10,45 +10,65 @@
 #@param 5 protocolo 
 #@param 6 opciones protocolo
 #@return 
-#@exception OG_ERR_FORMAT  # 1 formato incorrecto.
-#@exception updateCache    # 15 No hay cache 
-#@exception updateCache    # 16 no hay espacio sufiente 
-#@exception "Error al montar la imagen" INTERNACIONALIZAR
+#@exception OG_ERR_FORMAT   # 1 formato incorrecto.
+#@exception OG_ERR_NOTFOUND # 2 Fichero o dispositivo no encontrado
+#@exception OG_ERR_PARTITION# 3 Error en partición de disco.
+#@exception OG_ERR_LOCKED   # 4 Partición o fichero bloqueado.
+#@exception updateCache     # 15 No hay cache 
+#@exception updateCache     # 16 no hay espacio sufiente 
+#@exception OG_ERR_DONTSYNC_IMAGE   # 71 Imagen no sincronizable (es monolitica)
+#@exception OG_ERR_DONTMOUNT_IMAGE  # 70 Error al montar una imagen sincronizada.
 #@todo: Se puede dar la opcion de que mantenga los ficheros nuevos.
 #@todo: Se puede dar la opcion que la trasferencia se manden los datos comprimidos.
 #@version 1.0 - restauración de imagen con sincronizacion.
 #@author  
 #@date   2012-12-04
 #*/ ##
-trap "ogUnlockImage $1  /$2.$IMGEXT ; ogUnlock $3 $4; umount $DIRMOUNT; exit 1" 1 2 3 6 9 14 15
+trap "onexit $1 \"$2\" $3 $4" 1 2 3 6 9 14 15 ERR
+
+# Si salimos con error demontamos la imagen y desbloqueamos la imagen y la particion
+function onexit() {
+    local exit_status=$?
+    ogUnmountImage "$1" "$2" "$DIFFEXT" &>/dev/null
+    # Si la partición no estaba bloqueada -> la desbloqueo
+    [ $exit_status -eq 4 ] || ogUnlock $3 $4 &>/dev/null
+    exit $exit_status
+}
+
 
 # Limpiamos los archivo de log
 echo "" >$OGLOGCOMMAND
 
 TIME1=$SECONDS
 PROG="$(basename $0)"
-if [ $# -lt 4 ]; then
-    ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE imagen[.sujijo] ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"
-    exit $?
+# Si se solicita, mostrar ayuda.
+if [ "$*" == "help" ]; then
+    ogHelp  "$PROG: $MSG_HELP_restoreDiffImage" \
+            "$PROG REPO|CACHE diff_image ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]" \
+            "$PROG REPO Windows7_pc123 1 1 " \
+            "$PROG CACHE Ubuntu12_aula21 1 6 MULTICAST 9000:full-duplex:239.194.14.00:150M:50:60"
+    exit 0
 fi
+
+[ $# -lt 4 ] &&  ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE diff_imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"
 
 echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a  $OGLOGFILE
 
 # Procesar parámetros de entrada
 DIFFEXT="diff"
-REPODIFFFILE=$(ogGetPath "REPO" "$2.$DIFFEXT") || exit $(ogRaiseError $OG_ERR_NOTFOUND "$2.$DIFFEXT"; echo $?)
+REPODIFFFILE=$(ogGetPath "REPO" "$2.$DIFFEXT") || ogRaiseError $OG_ERR_NOTFOUND "REPO $2.$DIFFEXT"
 
 # Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$1" "$2.$DIFFEXT" && exit $(ogRaiseError $OG_ERR_LOCKED "$1 $2.$DIFFEXT"; echo $?)
-ogIsLocked "$3" "$4" && exit $(ogRaiseError $OG_ERR_LOCKED  "$3 $4"; echo $?)
+ogIsImageLocked "$1" "$2.$DIFFEXT" && ogRaiseError $OG_ERR_LOCKED "$1 $2.$DIFFEXT"
+ogIsLocked "$3" "$4" && ogRaiseError $OG_ERR_LOCKED  "$3 $4"
+
+PART=$(ogDiskToDev "$3" "$4" 2>/dev/null )  || ogRaiseError $OG_ERR_PARTITION "$1 $2"
 
 # Carga del configurador del engine
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
 # Comprobar que es sincronizable
-# TODO: crear mensaje de error.
-file $REPODIFFFILE | grep " BTRFS Filesystem" >/dev/null
-[ $? == 0 ]  ||  exit  $(ogRaiseError $OG_ERR_IMAGE "$3 $4"; echo $?)
+file $REPODIFFFILE | grep " BTRFS Filesystem" >/dev/null || ogRaiseError $OG_ERR_DONTSYNC_IMAGE "$3 $4"
 
 PROTO=${5:-"UNICAST"}
 
@@ -71,24 +91,23 @@ if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
 fi 
 TIME2=$SECONDS
 
-PART=$(ogDiskToDev "$3" "$4" 2>/dev/null )  || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2"; echo $?)
 
 # Restaurar la imagen.
 echo "[40] $MSG_RESTORE $PART"
 
 # Montamos la diferencial
-ogMountImage "$1" "$2" "diff" &>/dev/null
+ogMountImage "$1" "$2" "$DIFFEXT" &>/dev/null
 #  Comprobar que la imagen diferencial se ha montado 
-ogWaitMountImage "$1" "$2" "diff" || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 diff: time_out $TIMEAUX seg."; echo $?)
+ogWaitMountImage "$1" "$2" "$DIFFEXT" || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $DIFFEXT: time_out $TIMEAUX seg."
 
 ogMount $3 $4 >/dev/null
 ogLock $3 $4
 # Sincronizamos la partición con la imagen.
-echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 diff $3 $4"  |tee -a $OGLOGFILE
-ogSyncRestore "$1" "$2" "diff" $3 $4
+echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 $DIFFEXT $3 $4"  |tee -a $OGLOGFILE
+ogSyncRestore "$1" "$2" "$DIFFEXT" $3 $4
 
 # Desmontamos la imagen
-ogUnmountImage "$1" "$2" "diff"
+ogUnmountImage "$1" "$2" "$DIFFEXT"
 ogUnlock $3 $4
 
 TIMEAUX2=$[SECONDS-TIME2]
