#565 #537 #636 Log en tiempo real para imagenes sincronizadas.
git-svn-id: https://opengnsys.es/svn/branches/version1.0@4153 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createBaseImage b/client/shared/scripts/createBaseImage
--- a/client/shared/scripts/createBaseImage
+++ b/client/shared/scripts/createBaseImage
@@ -26,14 +26,10 @@
 
 trap "onexit $1 $2 $3 \"$4\"" 1 2 3 6 9 14 15 ERR
 
-# Establecemos factor de compresion
-# !!! Se configura en las lineas 110 y 116.
-
 # Si salimos con error demontamos la imagen y desbloqueamos la imagen y la particion
 function onexit() {
     local exit_status=$?
-    local MSG="$(ogRaiseError $exit_status \"$1 $2 $3 $4\"  2>&1)"
-    echo "$MSG" |tee -a $OGLOGFILE  $OGLOGSESSION
+    echo -e  "\n $PROG error ${MSG_INTERFACE_END#*\]} $exit_status"  |tee -a $OGLOGFILE  $OGLOGSESSION
     ogUnmountImage $3 "$4" $IMGEXT &>/dev/null
     if [ $exit_status -ne 4 ]; then
 	ogUnlockImage "$3" "/$4.$IMGEXT" 
@@ -48,8 +44,14 @@ TIME1=$SECONDS
 
 # Factor de calculo de Time out al crear imagen: valor por defecto en engine.cfg 
 CREATESPEED=${CREATESPEED:-"100000*4"}
+
 # Sistema de fichero de la imagen según kernel, menor que 3.7 EXT4. comparamos revision 
 [  $(uname -r|cut -d. -f2) -lt 7 ] &&  IMGFS="EXT4" || IMGFS="BTRFS"
+# % de compresion para estimacion tamaño imagen IMGFS="EXT4"
+ZSYNC=${ZSYNC:-"120"}
+
+# Si IMGFS="BTRFS" la compresion es mayor.
+[ $IMGFS == "BTRFS" ] && let ZSYNC=$ZSYNC-30
 
 PROG="$(basename $0)"
 # Si se solicita, mostrar ayuda.
@@ -57,18 +59,17 @@ if [ "$*" == "help" ]; then
     ogHelp  "$PROG: $MSG_HELP_createBaseImage" \
 	    "$PROG ndisco nparticion REPO|CACHE base_image" \
             "$PROG 1 1 REPO Windows7"
-   exit 0
+    exit 0
 fi
 
 [ $# -ne 4 ] && ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE imagen" 
 
 
 # Limpiamos fichero de log
-echo  -n ""> $OGLOGSESSION
 echo  " " > $OGLOGCOMMAND
+[ "$(ogGetCaller)" == "RestaurarImagenBasica" ] || echo  -n ""> $OGLOGSESSION
 
 echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION  $OGLOGFILE
-
 
 # Valores por defecto en etc/engine.cfg
 IMGEXT="img"
@@ -84,47 +85,12 @@ if [ "$3" == "CACHE" -o "$3" == "cache" ]; then
 	! ogFindCache >/dev/null && ogRaiseError $OG_ERR_NOTCACHE "CACHE "
 fi
 
-
-# Obtener información de los parámetros de entrada.
-PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || ogRaiseError $OG_ERR_PARTITION "$1 $2"
-# Comprobamos que la particion se puede montar
-ORIG=$(ogMount $1 $2) || ogRaiseError $OG_ERR_PARTITION "$1 $2"
-
 #Comprobamos acceso de escritura.
 DIRTEMP="/$4$(date +%Y%m%d-%H%M%S)"
 ogMakeDir $3 "$DIRTEMP" 2>/dev/null || ogRaiseError $OG_ERR_NOTWRITE "$3" && ogDeleteTree $3 "$DIRTEMP" 
 
-# Borramos ficheros de paginacion y configuracion
-case "$(ogGetFsType $1 $2)" in 
-    EXT[234])
-	ogCleanLinuxDevices $1 $2
-	rm -rf $ORIG/tmp/*
-	# Compresion linux && ext4 || btrfs
-        [ $IMGFS == "EXT4" ] && COMPRESS=110/100 || COMPRESS=80/100
-	;;
-    NTFS)
-        [ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys
-        [ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys
-	# Compresion windows && ext4 || btrfs
-        [ $IMGFS == "EXT4" ] && COMPRESS=120/100 || COMPRESS=90/100
-	;;
-esac
-
-#Comprobar espacio que requerira la imagen para ser almacenada
-SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
-#Aplicar factor de compresion
-let SIZEREQUIRED=$SIZEDATA*$COMPRESS
-# El tamaño mínimo del sistema de ficheros btrfs es 250M, ponemos 300
-[ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
-#Comprobar espacio libre en el contenedor.
-[ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
-[ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-echo "[16]$MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
-[ $SIZEREQUIRED -gt $SIZEFREE ] && ogRaiseError $OG_ERR_CACHESIZE "$3"
-
-IMGDIR="$(ogGetParentPath "$3" "/$4")"
-IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
-
+# Obtener información de los parámetros de entrada.
+PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || ogRaiseError $OG_ERR_PARTITION "$1 $2"
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
 SIZEFS=$(ogGetFsSize  $1 $2)
@@ -132,31 +98,67 @@ echo "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGL
 ogUnmount $1 $2
 ogCheckFs $1 $2 &> $OGLOGCOMMAND || ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2"
 
+# Comprobamos que la particion se puede montar
+ORIG=$(ogMount $1 $2) || ogRaiseError $OG_ERR_PARTITION "$1 $2"
+
+
+# Borramos ficheros de paginacion y configuracion
+case "$(ogGetFsType $1 $2)" in 
+    EXT[234])
+	ogCleanLinuxDevices $1 $2
+	rm -rf $ORIG/tmp/*
+	;;
+    NTFS)
+	[ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys
+	[ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys	
+	[ $(ogGetPath $1 $2 swapfile.sys) ] && ogDeleteFile $1 $2 swapfile.sys 
+	;;
+esac
+
+
+#Comprobar espacio que requerira la imagen para ser almacenada
+SIZEDATA=$(df -k | grep $PART | awk '{print $3}')
+#Aplicar factor de compresion
+let SIZEREQUIRED=$SIZEDATA*$ZSYNC/100
+# El tamaño mínimo del sistema de ficheros btrfs es 250M, ponemos 300
+[ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
+#Comprobar espacio libre en el contenedor.
+[ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
+[ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
+echo "      $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
+[ $SIZEREQUIRED -gt $SIZEFREE ] && ogRaiseError $OG_ERR_CACHESIZE "$3"
+
+IMGDIR="$(ogGetParentPath "$3" "/$4")"
+IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
+
+
 # Crear la imagen.
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
 
 ogLockImage "$3"  "/$4.$IMGEXT"
 
+echo "[40] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
 # Si existe el fichero de la imagen se hace copia de seguridad y se redimensiona, si  no existe se crea.
-echo "[30] $MSG_HELP_ogCreateFileImage." | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[50] $MSG_HELP_ogCreateFileImage." | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
 
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
-echo "[50] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      $MSG_HELP_ogCreateInfoImage"  | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[60] $MSG_HELP_ogCreateInfoImage"  | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateInfoImage $1 $2 $IMGEXT
 
 TIMEAUX3=$[SECONDS-TIME2]
 echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Esperamos que el servidor termine de crear y montar la imagen
-ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED  || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out."
-
+ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED 
 
 # Sincronizamos los datos de la particion con la imagen.
-echo "      $MSG_HELP_ogSyncCreate."  | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[70] $MSG_HELP_ogSyncCreate."  | tee -a $OGLOGSESSION $OGLOGFILE
 ogSyncCreate $1 $2 $3 "$4"  $IMGEXT
+
+TIMEAUX5=$[SECONDS-TIMEAUX3]
+echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX5/60]m $[TIMEAUX5%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Reducimos la imagen: solo para kernel <= 3.7, imagenes con FS ext4.
 echo "[80] $MSG_HELP_ogReduceImage: $3 /$4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE
@@ -166,18 +168,12 @@ ogReduceImage $3 "$4" $IMGEXT
 ogUnmountImage $3 "$4" $IMGEXT
 ogUnlockImage "$3" "/$4.$IMGEXT"
 ogUnlock $1 $2
-TIMEAUX5=$[SECONDS-TIMEAUX3]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
+echo  " " > $OGLOGCOMMAND
 # Comprobamos que la imagen esta bien detectacdo que es un sistema de ficheros.
 echo "[95] $MSG_HELP_ogCheckSyncImage" | tee -a $OGLOGSESSION $OGLOGFILE
-ogCheckSyncImage $3 "$4" "img" | tee -a $OGLOGSESSION $OGLOGFILE
-RETVAL=${PIPESTATUS[0]}
-[ "$RETVAL" == "0" ] || ogRaiseError $OG_ERR_IMAGE "$3 $4 img" 
-
-
-TIMEAUX7=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+ogCheckSyncImage $3 "$4" "img" 
+[ $? -eq 0 ] || ogRaiseError $OG_ERR_IMAGE "$3 $4 img" 
 
 
 #resumen de la operacion
diff --git a/client/shared/scripts/createDiffImage b/client/shared/scripts/createDiffImage
--- a/client/shared/scripts/createDiffImage
+++ b/client/shared/scripts/createDiffImage
@@ -28,13 +28,9 @@
 #*/ ##
 trap "onexit $1 $2 $3 \"$4\" \"$5\"" 1 2 3 6 9 14 15 ERR
 
-# Establecemos factor de compresion
-# !!! Se configura en las lineas 122 y 128.
-
 function onexit() {
     local exit_status=$?
-    local MSG="$(ogRaiseError $exit_status \"$1 $2 $3 $4 $5\" 2>&1)"
-    echo "$MSG" |tee -a $OGLOGFILE  $OGLOGSESSION
+    echo -e "\n $PROG error: ${MSG_INTERFACE_END#*\]} $exit_status" |tee -a $OGLOGFILE  $OGLOGSESSION
     ogUnmountImage $3 "$5" $DIFFTYPE &>/dev/null
     ogUnmountImage $3 "$4" $IMGEXT &>/dev/null
     if [ $exit_status -ne 4 ]; then
@@ -52,6 +48,11 @@ function onexit() {
 CREATESPEED=${CREATESPEED:-"100000*4"}
 # Sistema de fichero de la imagen según kernel, menor que 3.7 EXT4. comparamos revision 
 [  $(uname -r|cut -d. -f2) -lt 7 ] &&  IMGFS="EXT4" || IMGFS="BTRFS"
+# % de compresion para estimacion tamaño imagen IMGFS="EXT4"
+ZSYNC=${ZSYNC:-"120"}
+# Si IMGFS="BTRFS" la compresion es mayor.
+[ $IMGFS == "BTRFS" ] && let ZSYNC=$ZSYNC-30
+
 
 TIME1=$SECONDS
 
@@ -72,7 +73,8 @@ DIFFEXT="img.diff"
 DIFFTYPE="diff"
 
 # Limpiamos los archivo de log
-echo -n "" >$OGLOGCOMMAND;  echo -n ""  $OGLOGSESSION
+echo -n "" >$OGLOGCOMMAND
+[ "$(ogGetCaller)" == "RestaurarSoftIncremental" ] ||  echo -n "" > $OGLOGSESSION
 
 echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION $OGLOGFILE
 
@@ -108,7 +110,6 @@ DIFFFILE="$DIFFDIR/$5.$DIFFEXT"
 
 ogLockImage "$3"  "/$4.$IMGEXT"
 ogLockImage "$3"  "/$5.$DIFFEXT"
-LOOPDEVICE=$(losetup -f)
 
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
@@ -117,23 +118,18 @@ echo "[20] $MSG_HELP_ogCheckFs  $1 $2 $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGL
 ogUnmount $1 $2
 ogCheckFs $1 $2 >$OGLOGCOMMAND || ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2" 
 
-TIMEAUX1=$[SECONDS-TIME1]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Borramos ficheros de paginacion y configuracion
-# Establecemos factor de compresion, varia segun el sistema operativo y el kernel.
-case "$(ogGetFsType $1 $2)" in
+FSTYPE=$(ogGetFsType $1 $2)
+case "$FSTYPE" in
     EXT[234])
         ogCleanLinuxDevices $1 $2
 	rm -rf $ORIG/tmp/*
-	# Compresion linux && ext4 || btrfs
-	[ $IMGFS == "EXT4" ] && COMPRESS=110/100 || COMPRESS=80/100
         ;;
     NTFS)
-	[ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys 
-        [ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys
-	# Compresion windows && ext4 || btrfs
-	[  $IMGFS == "EXT4" ] && COMPRESS=130/100 || COMPRESS=90/100
+	[ $(ogGetPath $1 $2 pagefile.sys) ] && ogDeleteFile $1 $2 pagefile.sys
+	[ $(ogGetPath $1 $2 hiberfil.sys) ] && ogDeleteFile $1 $2 hiberfil.sys
+	[ $(ogGetPath $1 $2 swapfile.sys) ] && ogDeleteFile $1 $2 swapfile.sys
         ;;
 esac
 
@@ -142,9 +138,6 @@ echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
 echo "[40] $MSG_HELP_createDiffImage: $1 $2 $3 $4" | tee -a $OGLOGSESSION $OGLOGFILE
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
-FSTYPE=$(ogGetFsType $1 $2)
-
-IMGDIRAUX=$(ogGetMountImageDir "$4" $IMGEXT)
 
 # Montamos imagen completa (con la que vamos a comparar)
 ogMountImage $3 "$4" $IMGEXT >/dev/null
@@ -155,24 +148,14 @@ ogWaitMountImage $3 "$4" $IMGEXT || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 
 # Creamos la informacion de la imagen.
 echo "[50] $MSG_HELP_ogCreateInfoImage " | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateInfoImage $1 $2 $3 "$4" "${DIFFTYPE}"
-TIMEAUX3=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
-# Del fichero de acl de la partición extraemos las acl de los ficheros de la diferencial
-echo "[60] $MSG_HELP_ogAclFilter " | tee -a $OGLOGSESSION $OGLOGFILE
-ogAclFilter
-TIMEAUX5=$[SECONDS-TIMEAUX3]
-echo "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX5/60]m $[TIMEAUX5%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
 
 #Calculamos el tamaño de la imagen:
 ogMount $1 $2 >/dev/null
 ogLock $1 $2
-
 echo -n "     $MSG_SCRIPTS_CREATE_SIZE" | tee -a $OGLOGSESSION $OGLOGFILE
 cd $ORIG
 SIZEDATA=$(grep -v "\/$" /tmp/ogimg.info | tr '\n' '\0'| du -x -c --files0-from=- 2>/dev/null|tail -n1 |cut -f1)
-let SIZEREQUIRED=$SIZEDATA*$COMPRESS 
+let SIZEREQUIRED=$SIZEDATA*$ZSYNC/100
 # Tamaño minimo fichero imagen 300000
 [ $SIZEREQUIRED -lt 300000 ] && SIZEREQUIRED=300000
 
@@ -182,21 +165,34 @@ let SIZEREQUIRED=$SIZEDATA*$COMPRESS
 echo  " $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
 [ $SIZEREQUIRED -gt $SIZEFREE ] && ogRaiseError $OG_ERR_CACHESIZE "$3"
 
+TIMEAUX3=$[SECONDS-TIME2]
+echo "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+
+# Del fichero de acl de la partición extraemos las acl de los ficheros de la diferencial
+if [ "$FSTYPE" == "NTFS" ]; then
+	echo "[55] $MSG_HELP_ogAclFilter " | tee -a $OGLOGSESSION $OGLOGFILE
+	ogAclFilter
+	TIMEAUX4=$[SECONDS-TIMEAUX3]
+	echo "      $MSG_SCRIPTS_TASK_END $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX4/60]m $[TIMEAUX4%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+fi
+TIMEAUX5=$[SECONDS-TIMEAUX3]
+
+
 # Configuro la informacion del tamaño de los datos en /tmp/ogimg.info
 sed -i s/SIZEDATA/"$SIZEDATA"/g /tmp/ogimg.info
 
 # Creamos o redimensionamos la imagen
-echo "[70] $MSG_HELP_ogCreateFileImage."  | tee -a $OGLOGSESSION $OGLOGFILE
+echo "[60] $MSG_HELP_ogCreateFileImage."  | tee -a $OGLOGSESSION $OGLOGFILE
 ogCreateFileImage $3 "$5" $DIFFTYPE $SIZEREQUIRED
 
 # Esperamos que se monte la imagen despues de crarla en el servidor
 ogWaitMountImage "$3" "$5" "$DIFFTYPE" $SIZEREQUIRED  || ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $5 $DIFFTYPE: time_out."
-TIMEAUX6=$[SECONDS-TIMEAUX5]
-echo  -e "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX6/60]m $[TIMEAUX6%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
-echo  "[80] $MSG_HELP_ogSyncCreate" | tee -a $OGLOGSESSION $OGLOGFILE
+echo  "[70] $MSG_HELP_ogSyncCreate" | tee -a $OGLOGSESSION $OGLOGFILE
 # Copio los datos a la imagen diferecial :
 ogSyncCreate $1 $2 $3 "$5" $DIFFTYPE
+TIMEAUX6=$[SECONDS-TIMEAUX5]
+echo  -e "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX6/60]m $[TIMEAUX6%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
 
 # Reducimos la imagen diferencial -> solo para kernel <= 3.7, imagenes con FS ext4
 echo "[80] $MSG_HELP_ogReduceImage: $3 /$4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE
@@ -206,23 +202,16 @@ ogReduceImage  $3 "$5" $DIFFTYPE
 ogUnmountImage $3 "$5" $DIFFTYPE
 ogUnmountImage $3 "$4" $IMGEXT
 
-
-TIMEAUX7=$[SECONDS-TIMEAUX6]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX7/60]m $[TIMEAUX7%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
-
-TIMEAUX8=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX8/60]m $[TIMEAUX8%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-
+# Desbloqueo las imagenes y la particion.
 ogUnlockImage "$3" "/$4.$IMGEXT"
 ogUnlockImage "$3" "/$5.$DIFFEXT"
 ogUnlock $1 $2
 
+echo " " > $OGLOGCOMMAND
 # Comprobamos que la imagen esta bien
 echo "[95] $MSG_HELP_ogCheckSyncImage" | tee -a $OGLOGSESSION $OGLOGFILE
-ogCheckSyncImage $3 "$5" diff | tee -a $OGLOGSESSION $OGLOGFILE
-RETVAL=${PIPESTATUS[0]}
-[ "$RETVAL" == "0" ] ||  ogRaiseError $OG_ERR_IMAGE "$3 $5 diff"
+ogCheckSyncImage $3 "$5" diff 
+[ ${PIPESTATUS[0]} -eq 0 ] ||  ogRaiseError $OG_ERR_IMAGE "$3 $5 diff"
 
 #resumen de la operacion
 IMGSIZE=$(ls -l --block-size=1024 "${DIFFFILE}"| cut -f5 -d" ")
