#636 #565 mensajes log en tiempo real y corrige problema al crear imágenes sincronizada tipo archivo con cliente en modo usuario
git-svn-id: https://opengnsys.es/svn/branches/version1.0@4189 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/createBaseImage b/client/shared/scripts/createBaseImage
--- a/client/shared/scripts/createBaseImage
+++ b/client/shared/scripts/createBaseImage
@@ -17,7 +17,7 @@
 #@exception OG_ERR_NOTCACHE   # 15 si cache no existe 15
 #@exception OG_ERR_CACHESIZE  # 16 si espacio de la cache local o remota no tiene espacio 16
 #@exception OG_ERR_DONTMOUNT_IMAGE # 70 Error al montar una imagen sincronizada
-#@note  se toma como punto de partida el script createImage, cambiando solo lo especifico para la imagen sincronizada
+#@note  No necesario permiso se escritura por samba en repo.
 #@todo: que hacer, si el tamaño de la cache es sufciente, pero no tiene espacio libre
 #@version 1.0 - creación imagen con btrfs
 #@author  
@@ -31,7 +31,11 @@ function onexit() {
     local exit_status=$?
     ogUnmountImage $3 "$4" $IMGEXT &>/dev/null
     if [ $exit_status -ne 4 ]; then
-	ogUnlockImage "$3" "/$4.$IMGEXT" 
+	if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
+		ogUnlockImage "$3" "/$4.$IMGEXT" 
+	else
+		hose $REPOIP 2009 --out sh -c "echo -ne UNLOCK_IMAGE \"$4.$IMGEXT\" "	
+	fi
 	ogUnlock $1 $2
     fi
     exit $exit_status
@@ -61,13 +65,13 @@ if [ "$*" == "help" ]; then
     exit 0
 fi
 
-[ $# -ne 4 ] && exit $(ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE imagen" ; echo $?)
+[ $# -ne 4 ] && exit $(ogRaiseError session $OG_ERR_FORMAT "$MSG_FORMAT: $PROG ndisco nparticion REPO|CACHE imagen" ; echo $?)
 
 # Limpiamos fichero de log
 echo  " " > $OGLOGCOMMAND
 [ "$(ogGetCaller)" == "RestaurarImagenBasica" ] || echo  -n ""> $OGLOGSESSION
 
-echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a $OGLOGSESSION  $OGLOGFILE
+ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*"
 
 # Valores por defecto en etc/engine.cfg
 IMGEXT="img"
@@ -75,29 +79,25 @@ REPOIP=$(ogGetRepoIp)
 
 
 # Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$3" "$4.$IMGEXT" && exit $(ogRaiseError $OG_ERR_LOCKED "$3 $4.$IMGEXT"; echo $?)
-ogIsLocked "$1" "$2" && exit $(ogRaiseError $OG_ERR_LOCKED  "$1 $2"; echo $?)
+ogIsImageLocked "$3" "$4.$IMGEXT" && exit $(ogRaiseError session $OG_ERR_LOCKED "$3 $4.$IMGEXT"; echo $?)
+ogIsLocked "$1" "$2" && exit $(ogRaiseError session $OG_ERR_LOCKED  "$1 $2"; echo $?)
 
 # Si el repositorio es CACHE comprobamos que exista
 if [ "$3" == "CACHE" -o "$3" == "cache" ]; then 
-	! ogFindCache >/dev/null && exit $(ogRaiseError $OG_ERR_NOTCACHE "CACHE "; echo $?)
+	! ogFindCache >/dev/null && exit $(ogRaiseError session $OG_ERR_NOTCACHE "CACHE "; echo $?)
 fi
 
-#Comprobamos acceso de escritura.
-DIRTEMP="/$4$(date +%Y%m%d-%H%M%S)"
-ogMakeDir $3 "$DIRTEMP" 2>/dev/null  && ogDeleteTree $3 "$DIRTEMP" || exit $(ogRaiseError $OG_ERR_NOTWRITE "$3" ; echo $?)
-
 # Obtener información de los parámetros de entrada.
-PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2" ; echo $?)
+PART=$(ogDiskToDev "$1" "$2" 2>/dev/null) || exit $(ogRaiseError session $OG_ERR_PARTITION "$1 $2" ; echo $?)
 # Comprobar consistencia del sistema de archivos.
 echo " " > $OGLOGCOMMAND
 SIZEFS=$(ogGetFsSize  $1 $2)
-echo "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) " | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[20] $MSG_HELP_ogCheckFs  $PART $SIZEFS (KB) "
 ogUnmount $1 $2
-ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError $OG_ERR_PARTITION "ogCheckFs $1 $2"; echo $?)
+ogCheckFs $1 $2 &> $OGLOGCOMMAND || exit $(ogRaiseError session $OG_ERR_PARTITION "ogCheckFs $1 $2"; echo $?)
 
 # Comprobamos que la particion se puede montar
-ORIG=$(ogMount $1 $2) || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $2" ; echo $?)
+ORIG=$(ogMount $1 $2) || exit $(ogRaiseError session $OG_ERR_PARTITION "$1 $2" ; echo $?)
 
 # Borramos ficheros de paginacion y configuracion
 case "$(ogGetFsType $1 $2)" in 
@@ -121,8 +121,8 @@ let SIZEREQUIRED=$SIZEDATA*$ZSYNC/100
 #Comprobar espacio libre en el contenedor.
 [ "$3" == "CACHE" -o "$3" == "cache" ] && SIZEFREE=$(ogGetFreeSize `ogFindCache`)
 [ "$3" == "REPO"  -o "$3" == "repo"  ] && SIZEFREE=$(df -k | grep $OGIMG | awk '{print $4}')
-echo "      $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE" | tee -a $OGLOGSESSION $OGLOGFILE
-[ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError $OG_ERR_CACHESIZE "$3"; echo $?)
+ogEcho log session "      $MSG_SCRIPTS_CREATE_SIZE  $SIZEREQUIRED $SIZEFREE"
+[ $SIZEREQUIRED -gt $SIZEFREE ] && exit $(ogRaiseError session $OG_ERR_CACHESIZE "$3"; echo $?)
 IMGDIR="$(ogGetParentPath "$3" "/$4")"
 IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
 
@@ -130,47 +130,47 @@ IMGFILE=${IMGDIR[$3]}/$(basename "/$4").$IMGEXT
 echo " " > $OGLOGCOMMAND
 TIME2=$SECONDS
 
-ogLockImage "$3"  "/$4.$IMGEXT"
+if [ "$3" == "CACHE" -o "$3" == "cache" ]; then
+	ogLockImage "$3"  "/$4.$IMGEXT"
+else
+	hose $REPOIP 2009 --out sh -c "echo -ne LOCK_IMAGE \"$4.$IMGEXT\" "	
+fi
 
-echo "[40] $MSG_HELP_ogCreateImage $1 $2 $3 $4 " | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[40] $MSG_HELP_ogCreateImage $1 $2 $3 $4 "
 # Si existe el fichero de la imagen se hace copia de seguridad y se redimensiona, si  no existe se crea.
-echo "[50] $MSG_HELP_ogCreateFileImage." | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[50] $MSG_HELP_ogCreateFileImage."
 ogCreateFileImage $3 "$4" $IMGEXT $SIZEREQUIRED
 
 # Creamos la lista del contenido y lo situamos en la particion a copiar.
-echo "[60] $MSG_HELP_ogCreateInfoImage"  | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[60] $MSG_HELP_ogCreateInfoImage" 
 ogCreateInfoImage $1 $2 $IMGEXT
 
 TIMEAUX3=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX3/60]m $[TIMEAUX3%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX3/60]m $[TIMEAUX3%60]s"
 
 # Esperamos que el servidor termine de crear y montar la imagen
-ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out."; echo $?)
+ogWaitMountImage "$3" "$4" $IMGEXT $SIZEREQUIRED || exit $(ogRaiseError session $OG_ERR_DONTMOUNT_IMAGE "$3 $4 $IMGEXT: time_out."; echo $?)
 
 # Sincronizamos los datos de la particion con la imagen.
-echo "[70] $MSG_HELP_ogSyncCreate."  | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[70] $MSG_HELP_ogSyncCreate." 
 ogSyncCreate $1 $2 $3 "$4"  $IMGEXT
 
 TIMEAUX5=$[SECONDS-TIMEAUX3]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX5/60]m $[TIMEAUX5%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL: $[TIMEAUX5/60]m $[TIMEAUX5%60]s"
 
-# Reducimos la imagen: solo para kernel <= 3.7, imagenes con FS ext4.
-echo "[80] $MSG_HELP_ogReduceImage: $3 /$4.$IMGEXT" | tee -a $OGLOGSESSION $OGLOGFILE
+# Reducimos la imagen: solo para kernel <= 3.7, imagenes con FS ext4. (Desmonta y desbloquea la imagen)
+ogEcho log session "[80] $MSG_HELP_ogReduceImage: $3 /$4.$IMGEXT"
 ogReduceImage $3 "$4" $IMGEXT
-
-# Desmontamos la Imagen
-ogUnmountImage $3 "$4" $IMGEXT
-ogUnlockImage "$3" "/$4.$IMGEXT"
-ogUnlock $1 $2
+sleep 10
 
 echo  " " > $OGLOGCOMMAND
 # Comprobamos que la imagen esta bien detectacdo que es un sistema de ficheros.
-echo "[95] $MSG_HELP_ogCheckSyncImage" | tee -a $OGLOGSESSION $OGLOGFILE
-ogCheckSyncImage $3 "$4" "img" || exit $(ogRaiseError $OG_ERR_IMAGE "$3 $4 img" ; echo $?)
+ogEcho log session "[95] $MSG_HELP_ogCheckSyncImage"
+ogCheckSyncImage $3 "$4" "img" || exit $(ogRaiseError session $OG_ERR_IMAGE "$3 $4 img" ; echo $?)
 
 #resumen de la operacion
 IMGSIZE=$(ls -l --block-size=1024 "$IMGFILE" | cut -f5 -d" ")
 
 TIME=$[SECONDS-TIME1]
-echo "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s" | tee -a $OGLOGSESSION $OGLOGFILE
-echo "      FileSystem $PART with $SIZEDATA KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync " | tee -a $OGLOGSESSION $OGLOGFILE
+ogEcho log session "[100] $MSG_SCRIPTS_TIME_TOTAL $[TIME/60]m $[TIME%60]s"
+ogEcho log session "      FileSystem $PART with $SIZEDATA KB data created onto file-image as $4 and used $IMGSIZE KB acros DFS rsync "
diff --git a/client/shared/scripts/restoreBaseImage b/client/shared/scripts/restoreBaseImage
--- a/client/shared/scripts/restoreBaseImage
+++ b/client/shared/scripts/restoreBaseImage
@@ -39,7 +39,7 @@ echo -n "" >$OGLOGCOMMAND;
 [ "$(ogGetCaller)" == "RestaurarImagenBasica" -o "$(ogGetCaller)" == "restoreDiffImage" ] ||  echo -n "" > $OGLOGSESSION
 
 # Mensaje de inicio de script salvo si es llamado desde restoreDiffImage.
-[ "$(ogGetCaller)" == "restoreDiffImage" ] || echo "[1] $MSG_SCRIPTS_START  $0 $*" | tee -a $OGLOGFILE  $OGLOGSESSION
+[ "$(ogGetCaller)" == "restoreDiffImage" ] || ogEcho log session "[1] $MSG_SCRIPTS_START  $0 $*" 
 
 TIME1=$SECONDS
 PROG="$(basename $0)"
@@ -52,90 +52,95 @@ if [ "$*" == "help" ]; then
     exit 0
 fi
 
-[ $# -lt 4 ] &&     exit $(ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"; echo $?)
+[ $# -lt 4 ] &&     exit $(ogRaiseError session $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"; echo $?)
 
 # Carga del configurador del engine
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
 # Procesar parámetros de entrada
-REPOFILE="$(ogGetPath "REPO" "$2.$IMGEXT")" || exit $(ogRaiseError $OG_ERR_NOTFOUND "REPO, $2.$IMGEXT"; echo $?)
+REPOFILE="$(ogGetPath "REPO" "$2.$IMGEXT")" || exit $(ogRaiseError session $OG_ERR_NOTFOUND "REPO, $2.$IMGEXT"; echo $?)
 
 # Comprobar que es sincronizable (con REPO)
-ogIsSyncImage REPO "$2" $IMGEXT  ||  exit $(ogRaiseError $OG_ERR_DONTSYNC_IMAGE  "$1 $2"; echo $?)
+ogIsSyncImage REPO "$2" $IMGEXT  ||  exit $(ogRaiseError session $OG_ERR_DONTSYNC_IMAGE  "$1 $2"; echo $?)
+
+# Detectamos el sistema de ficheros de la imagen
+# TODO ogGetImageInfo
+DIRMOUNT=$(ogMountImage "$1" "$2")
+ogWaitMountImage "$1" "$2" "$IMGEXT"  || exit $(ogRaiseError session $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $IMGEXT: time_out."; echo $?)
+IMGFSTYPE=$(head -1 $DIRMOUNT/ogimg.info |cut -d: -f3)
 
 # Comprobamos si el sistema de ficheros se puede montar
 ogMount "$3" "$4" &>/dev/null || RETVAL=$?
 # Si da error formateamos el sistema de ficheros.
 if [  "$RETVAL" ] ; then
-	# TODO ogGetImageInfo
-	DIRMOUNT=$(ogMountImage "$1" "$2")
-	ogWaitMountImage "$1" "$2" "$IMGEXT"  || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $IMGEXT: time_out."; echo $?)
-	FSTYPE=$(head -1 $DIRMOUNT/ogimg.info |cut -d: -f3)	
 	ogUnmountImage $1 "$2"
-	echo "      $MSG_HELP_ogFormat: $3 $4 $FSTYPE" | tee -a $OGLOGFILE
-	ogFormat "$3" "$4" "$FSTYPE" || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
-	ogMount "$3" "$4"  || exit $(ogRaiseError $OG_ERR_FILESYS "$3 $4"; echo $?)
+	ogEcho log session "      $MSG_HELP_ogFormat: $3 $4 $IMGFSTYPE" 
+	ogFormat "$3" "$4" "$IMGFSTYPE" || exit $(ogRaiseError session $OG_ERR_FILESYS "$3 $4"; echo $?)
+	ogMount "$3" "$4"  || exit $(ogRaiseError session $OG_ERR_FILESYS "$3 $4"; echo $?)
 fi
+
+# Warning si el sistema de ficheros de la imagen es distinto del de la particion destino
+[ "$IMGFSTYPE" == "$(ogGetFsType $3 $4)" ] || ogEcho session warning "$MSG_SYNC_DIFFERENTFS"
 
 IMGEXT="img"
 
 # Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$1" "$2.$IMGEXT" && exit $(ogRaiseError $OG_ERR_LOCKED "$1 $2.$IMGEXT"; echo $?)
-ogIsLocked "$3" "$4" && exit $(ogRaiseError $OG_ERR_LOCKED  "$3 $4"; echo $?)
+ogIsImageLocked "$1" "$2.$IMGEXT" && exit $(ogRaiseError session $OG_ERR_LOCKED "$1 $2.$IMGEXT"; echo $?)
+ogIsLocked "$3" "$4" && exit $(ogRaiseError session $OG_ERR_LOCKED  "$3 $4"; echo $?)
 
 PROTO=${5:-"UNICAST"}
 if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
    # Las imagenes sincronizables aunque sean iguales no tienen el mismo sum. 
    # Sincronizamos si existe el fichero y si no usamos updateCache.
-   echo "[10] $MSG_SCRIPTS_TASK_START updateCache REPO $2.$IMGEXT $PROTO $6" | tee -a $OGLOGFILE $OGLOGSESSION
-   echo "      updateCache REPO" "/$2.$IMGEXT" "$PROTO" "$6"   | tee -a $OGLOGFILE $OGLOGSESSION
+   ogEcho log session "[10] $MSG_SCRIPTS_TASK_START updateCache REPO $2.$IMGEXT $PROTO $6" 
+   ogEcho log session "      updateCache REPO" "/$2.$IMGEXT" "$PROTO" "$6"  
    updateCache REPO "/$2.$IMGEXT" "$PROTO" "$6" 
    RETVAL=$?
    if [ "$RETVAL" != "0" ] 
         then 
-        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.$IMGEXT $5 $6 con error $RETVAL" | tee -a $OGLOGFILE $OGLOGSESSION
+        ogEcho log session "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $2.$IMGEXT $5 $6 con error $RETVAL"
         # RC=15 No hay cache 
         # RC=16 no hay espacio sufiente 
         exit $RETVAL 
    fi 
    TIMEAUX1=$[SECONDS-TIME]
-   echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGFILE
+   ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" 
 
 fi 
 
 TIME2=$SECONDS
 
 # Restaurar la imagen.
-echo "[40] $MSG_HELP_ogRestoreImage: $1 $2 $3 $4"  | tee -a $OGLOGFILE $OGLOGSESSION
+ogEcho log session "[40] $MSG_HELP_ogRestoreImage: $1 $2 $3 $4"  
 
 ogLock $3 $4
 
 # Montamos la imagen basica.
 ogMountImage "$1" "$2" "$IMGEXT"  >/dev/null
 #  Comprobar que la imagen completa se ha montado.
-ogWaitMountImage "$1" "$2" "$IMGEXT"  || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $IMGEXT: time_out."; echo $?)
+ogWaitMountImage "$1" "$2" "$IMGEXT"  || exit $(ogRaiseError session $OG_ERR_DONTMOUNT_IMAGE "$1 $2 $IMGEXT: time_out."; echo $?)
 # Sincronizamos la partición con la imagen.
-echo  "[60] $MSG_HELP_ogSyncRestore: $1 $2 $IMGEXT $3 $4"  |tee -a $OGLOGFILE $OGLOGSESSION
+ogEcho log session  "[60] $MSG_HELP_ogSyncRestore: $1 $2 $IMGEXT $3 $4" 
 ogSyncRestore "$1" "$2" "$IMGEXT" $3 $4
 
 TIMEAUX2=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a $OGLOGFILE $OGLOGSESSION
+ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" 
 
 # Desmontamos imagen basica.
 ogUnmountImage "$1" "$2" "$IMGEXT"
 
 # Restableciendo acl
 ogUnlock $3 $4
-echo "[70] $MSG_HELP_ogRestoreInfoImage" |tee -a $OGLOGFILE $OGLOGSESSION
+ogEcho log session "[70] $MSG_HELP_ogRestoreInfoImage" 
 ogRestoreInfoImage $3 $4
 
 # Llamar al script de post-configuración del sistema operativo.
 # Si a este script lo ha llamado el script restoreDiffImage no post-configuramos
 if [ "$(ogGetCaller)" != "restoreDiffImage" ];then
-	echo "[90] $MSG_HELP_configureOs" |tee -a $OGLOGFILE $OGLOGSESSION
+	ogEcho log session "[90] $MSG_HELP_configureOs" 
 	configureOs $3 $4 
 fi
 
 TIME=$[SECONDS-TIME1]
-echo "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s" |tee -a $OGLOGFILE $OGLOGSESSION
+ogEcho log session "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s" 
 
diff --git a/client/shared/scripts/restoreDiffImage b/client/shared/scripts/restoreDiffImage
--- a/client/shared/scripts/restoreDiffImage
+++ b/client/shared/scripts/restoreDiffImage
@@ -52,26 +52,26 @@ if [ "$*" == "help" ]; then
     exit 0
 fi
 
-[ $# -lt 5 ] &&  exit $(ogRaiseError $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE base_image diff_imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"; echo $?)
+[ $# -lt 5 ] &&  exit $(ogRaiseError session $OG_ERR_FORMAT "$MSG_FORMAT: $PROG REPO|CACHE base_image diff_imagen ndisco nparticion [ UNICAST|MULTICAST|TORRENT ] [opciones protocolo]"; echo $?)
 
-echo "[1] $MSG_SCRIPTS_START $0 $*" | tee -a  $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "[1] $MSG_SCRIPTS_START $0 $*" 
 
 # Procesar parámetros de entrada
 DIFFTYPE="diff"
 DIFFEXT="img.diff"
-REPODIFFFILE="$(ogGetPath "REPO" "$3.$DIFFEXT")" || exit $(ogRaiseError $OG_ERR_NOTFOUND "REPO $3.$DIFFEXT";echo $?)
+REPODIFFFILE="$(ogGetPath "REPO" "$3.$DIFFEXT")" || exit $(ogRaiseError session $OG_ERR_NOTFOUND "REPO $3.$DIFFEXT";echo $?)
 
 # Comprobamos si la imagen o la particion estan bloqueada:
-ogIsImageLocked "$1" "$3.$DIFFEXT" && exit $(ogRaiseError $OG_ERR_LOCKED "$1 $3.$DIFFEXT";echo $?)
-ogIsLocked "$4" "$5" && exit $(ogRaiseError $OG_ERR_LOCKED  "$4 $5";echo $?)
+ogIsImageLocked "$1" "$3.$DIFFEXT" && exit $(ogRaiseError session $OG_ERR_LOCKED "$1 $3.$DIFFEXT";echo $?)
+ogIsLocked "$4" "$5" && exit $(ogRaiseError session $OG_ERR_LOCKED  "$4 $5";echo $?)
 
-PART=$(ogDiskToDev "$4" "$5" 2>/dev/null )  || exit $(ogRaiseError $OG_ERR_PARTITION "$1 $3";echo $?)
+PART=$(ogDiskToDev "$4" "$5" 2>/dev/null )  || exit $(ogRaiseError session $OG_ERR_PARTITION "$1 $3";echo $?)
 
 # Carga del configurador del engine
 [ -z $OGENGINECONFIGURATE ] && source /opt/opengnsys/etc/engine.cfg
 
 # Comprobar que es sincronizable
-ogIsSyncImage REPO "$3" diff || exit $(ogRaiseError $OG_ERR_DONTSYNC_IMAGE "$1 $3";echo $?)
+ogIsSyncImage REPO "$3" diff || exit $(ogRaiseError session $OG_ERR_DONTSYNC_IMAGE "$1 $3";echo $?)
 
 # Restauramos la imagen Basica.
 restoreBaseImage $1 "$2" "$4" "$5" "$6" "$7"
@@ -79,35 +79,35 @@ restoreBaseImage $1 "$2" "$4" "$5" "$6" "$7"
 PROTO=${6:-"UNICAST"}
 
 if [ "$1" == "CACHE" -o "$1" == "cache" ]; then
-   echo "[10] $MSG_HELP_updateCache." | tee -a  $OGLOGFILE  $OGLOGSESSION
-   echo "     updateCache REPO" "/$3.$DIFFEXT" "$PROTO" "$7"  | tee -a  $OGLOGFILE  $OGLOGSESSION
+   ogEcho log session "[10] $MSG_HELP_updateCache." 
+   ogEcho log session "     updateCache REPO" "/$3.$DIFFEXT" "$PROTO" "$7"  
    updateCache REPO "/$3.$DIFFEXT" "$PROTO" "$7"
    RETVAL=$?
    if [ "$RETVAL" != "0" ] 
         then 
-        echo "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $3.$DIFFEXT $6 $7 con error $RETVAL" | tee -a  $OGLOGFILE 
+        ogEcho log session "[39] $MSG_SCRIPTS_TASK_END updateCache REPO $3.$DIFFEXT $6 $7 con error $RETVAL" 
         # RC=15 No hay cache 
         # RC=16 no hay espacio sufiente 
         exit $RETVAL 
    fi 
 
    TIMEAUX1=$[SECONDS-TIME]
-   echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" | tee -a $OGLOGFILE  $OGLOGSESSION
+   ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX1/60]m $[TIMEAUX1%60]s" 
 fi 
 TIME2=$SECONDS
 
 # Restaurar la imagen.
-echo "[40] $MSG_RESTORE $PART" | tee -a $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "[40] $MSG_RESTORE $PART" 
 
 # Montamos la diferencial
 ogMountImage "$1" "$3" "$DIFFTYPE" &>/dev/null
 #  Comprobar que la imagen diferencial se ha montado 
-ogWaitMountImage "$1" "$3" "$DIFFTYPE" || exit $(ogRaiseError $OG_ERR_DONTMOUNT_IMAGE "$1 $3 $DIFFTYPE: time_out $TIMEAUX seg.";echo $?)
+ogWaitMountImage "$1" "$3" "$DIFFTYPE" || exit $(ogRaiseError session $OG_ERR_DONTMOUNT_IMAGE "$1 $3 $DIFFTYPE: time_out $TIMEAUX seg.";echo $?)
 
 ogMount $4 $5 >/dev/null
 ogLock $4 $5
 # Sincronizamos la partición con la imagen.
-echo  "[60] $MSG_HELP_ogSyncRestore: $1 $3 $DIFFTYPE $4 $5"  |tee -a $OGLOGFILE  $OGLOGSESSION
+ogEcho log session  "[60] $MSG_HELP_ogSyncRestore: $1 $3 $DIFFTYPE $4 $5" 
 ogSyncRestore "$1" "$3" "$DIFFTYPE" $4 $5
 
 # Desmontamos la imagen
@@ -115,16 +115,16 @@ ogUnmountImage "$1" "$3" "$DIFFTYPE"
 ogUnlock $4 $5
 
 TIMEAUX2=$[SECONDS-TIME2]
-echo "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" | tee -a  $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "      $MSG_SCRIPTS_TASK_END, $MSG_SCRIPTS_TIME_PARTIAL : $[TIMEAUX2/60]m $[TIMEAUX2%60]s" 
 
 # creando enlaces y restableciendo ACL (en windows)
-echo "[70] $MSG_HELP_ogRestoreInfoImage" |tee -a $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "[70] $MSG_HELP_ogRestoreInfoImage"
 ogRestoreInfoImage  "$4" "$5" &>$OGLOGCOMMAND
 
 # Llamar al script de post-configuración del sistema operativo.
-echo "[90] $MSG_HELP_configureOs." | tee -a  $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "[90] $MSG_HELP_configureOs." 
 configureOs $4 $5 
 
 TIME=$[SECONDS-TIME1]
-echo "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s" |tee -a $OGLOGFILE  $OGLOGSESSION
+ogEcho log session "[100] $MSG_SCRIPTS_END $MSG_SCRIPTS_TIME_TOTAL: $[TIME/60]m $[TIME%60]s"
 
