version 1.0.1  #381  codigos error
git-svn-id: https://opengnsys.es/svn/branches/version1.0@1948 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/deployImage b/client/shared/scripts/deployImage
--- a/client/shared/scripts/deployImage
+++ b/client/shared/scripts/deployImage
@@ -10,11 +10,16 @@ fi
 #controlar param1 REPO
 
 updateCache REPO $2.img $5 $6
-if [ $? != "0" ]
+RC=$?
+if [ "$RC" != "0" ]
 then
-	echo "fin del updateCache REPO $2.img $5 $6 con errores"
-	exit 1
+	echo "fin del updateCache REPO $2.img $5 $6 con error $RC"
+	# RC=15 No hay cache
+	# RC=16 no hay espacio sufiente
+	exit $RC
+	
 else
-	echo "comenzamos con restoreImage CACHE $2 $3 $4"
-	restoreImage CACHE $2 $3 $4 
+	echo "iniciando un ogRestore CACHE desde deployImage"
+	ogRestoreImage CACHE $2 $3 $4 
+	ogExtendFs $3 $4
 fi
