Mejoras en script Restauración de Imagenes Básicas
git-svn-id: https://opengnsys.es/svn/branches/version1.0@3587 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/shared/scripts/ogRestaurarImagenBasica b/client/shared/scripts/ogRestaurarImagenBasica
--- a/client/shared/scripts/ogRestaurarImagenBasica
+++ b/client/shared/scripts/ogRestaurarImagenBasica
@@ -76,7 +76,6 @@
 
 	# Sincronización desde repositorio
 	if [ $METCLONA = 1 ]; then
-
 		if [ $COPIACACHE = 0 ]; then	
 			echo "Restaurando imagen basica desde repositorio $IPREPOSITORIO" | tee -a $OGLOGSESSION $OGLOGFILE
 			ORIGEN="$REPOSITORIO/$NOMBREIMG/"	
@@ -84,19 +83,32 @@
 			# Restauración de la imagen básica
 			echo "Sincronizando imagen entre $ORIGEN y $DESTINO" | tee -a $OGLOGSESSION $OGLOGFILE
 			restaurarImagen $ORIGEN $DESTINO $SISTEMAFICHERO 1
-			restauraListaAcl $ORIGEN $DESTINO $SISTEMAFICHERO $DISCO $NPART
+
 			RETVAL=$?
-			exit $RETVAL	
+			if [ $RETVAL -ne 0 ]; then
+	 				echo "***Error:$RETVAL. restaurando imagen basica desde repositorio $IPREPOSITORIO" | tee -a $OGLOGSESSION $OGLOGFILE
+				 exit $OG_ERR_IMAGE
+			fi	
+			restauraListaAcl $ORIGEN $DESTINO $SISTEMAFICHERO $DISCO $NPART
+		
+			RETVAL=$?
+			if [ $RETVAL -ne 0 ]; then
+	 				echo "***Error:$RETVAL. restaurando listas ACL desde repositorio $IPREPOSITORIO" | tee -a $OGLOGSESSION $OGLOGFILE
+				 exit $OG_ERR_IMAGE
+			fi
+			echo "!!! Finaliza correctamente !!! la restauración de imagen basica desde repositorio $IPREPOSITORIO" | tee -a $OGLOGSESSION $OGLOGFILE
+			exit 0	
 		fi		
 	fi	
 	
-	# Restauración desde la caché
-	echo "Restaurando desde la cache" | tee -a $OGLOGSESSION $OGLOGFILE
-	
+	if [ $METCLONA = 0 ]; then
+		# Restauración desde la caché
+		echo "Restaurando desde la cache" | tee -a $OGLOGSESSION $OGLOGFILE
+	fi	
 	# Comprobar si existe caché
 	CACHE=$(montaCache)
 	if [ -z $CACHE ]; then
-		echo "No se ha podido restaurar la imagen desde la cache" | tee -a $OGLOGSESSION $OGLOGFILE
+		echo "No se puede restaurar la imagen desde la cache ya que no existe" | tee -a $OGLOGSESSION $OGLOGFILE
         ogRaiseError $OG_ERR_NOTCACHE "CACHE"
         exit $?
 	fi			
@@ -104,7 +116,7 @@
 	# Borrar imagen de la caché
 	if [ $BORRACACHE -eq 1 ]; then
 		echo "Borrando imagen $NOMBREIMG de la cache" | tee -a $OGLOGSESSION $OGLOGFILE
-	    rm -R $CACHE$OGIMG/$NOMBREIMG
+	  rm -R $CACHE$OGIMG/$NOMBREIMG
 	fi
 	
 	# Actualización de la caché
@@ -116,7 +128,8 @@
 
 	RETVAL=$?	
 	if [ $RETVAL -ne 0 ]; then
-	   exit $OG_ERR_IMAGE
+		echo "***Error:$RETVAL. Actualizando cache local desde repositorio $IPREPOSITORIO" | tee -a $OGLOGSESSION $OGLOGFILE
+		exit $OG_ERR_IMAGE
 	fi			
 	
 	# Restauración desde caché a la partición
@@ -126,11 +139,20 @@
 	DESTINO="$PARTICION$RUTAORIGEN/"	
 	echo "Sincronizando imagen entre $ORIGEN y $DESTINO" | tee -a $OGLOGSESSION $OGLOGFILE
 	restaurarImagen $ORIGEN $DESTINO $SISTEMAFICHERO 2	
+
+	RETVAL=$?
+	if [ $RETVAL -ne 0 ]; then
+		echo "***Error:$RETVAL. restaurando imagen basica desde cache local" | tee -a $OGLOGSESSION $OGLOGFILE
+		exit $OG_ERR_IMAGE
+	fi	
+
 	restauraListaAcl $ORIGEN $DESTINO $SISTEMAFICHERO $DISCO $NPART
 	RETVAL=$?	
 	if [ $RETVAL -ne 0 ]; then
-	   exit $OG_ERR_IMAGE
+	 	echo "***Error:$RETVAL. restaurando listas ACL desde cache local" | tee -a $OGLOGSESSION $OGLOGFILE
+		exit $OG_ERR_IMAGE
 	fi	
+	echo "!!! Finaliza correctamente !!! restauración imagen basica desde cache local" | tee -a $OGLOGSESSION $OGLOGFILE
 #___________________________________________________________________
 #
 # Retorno
