Errata en mensaje de script de generación de cliente Initrd.
git-svn-id: https://opengnsys.es/svn/trunk@1401 a21b9725-9963-47de-94b9-378ad31fedc9

diff --git a/client/boot/initrd-generator b/client/boot/initrd-generator
--- a/client/boot/initrd-generator
+++ b/client/boot/initrd-generator
@@ -74,8 +74,8 @@ function descargar
         [ -f "$f" ] && rm -f $f
         # Descargar fichero (intentar primero actualizaciones).
         wget $URL/$f || wget ${URL/-updates/}/$f
-        if [ $? != 0 ] ; then
-            echo "Error no se ha podido descarga el initrd.gz"
+        if [ $? != 0 ]; then
+            echo "Error no se ha podido descargar el fichero $f"
             exit 1
         fi
     done
